package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.api.content.dialogue.DialogueEmote
import net.dodian.uber.game.engine.systems.dialogue.DialogueService
import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client

internal object Ian : NpcModule {
    // Stats: 1779: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1779, x = 1934, y = 4458, z = 2, face = 0),
    )
    val npcIds: IntArray = npcIdsFromEntries(entries)


    override val definition = legacyNpcDefinition(
        name = "Ian",
        entries = entries,
        onFirstClick = ::onFirstClick,
        onSecondClick = ::onSecondClick,
    )

    @Suppress("UNUSED_PARAMETER")
    fun onFirstClick(client: Client, npc: Npc): Boolean {
        DialogueService.start(client) {
            npcChat(npc.id, DialogueEmote.LAUGH1, "What are you even doing in here?!", "Begone from me!")
            finish()
        }
        return true
    }

    @Suppress("UNUSED_PARAMETER")
    fun onSecondClick(client: Client, npc: Npc): Boolean {
        DialogueService.start(client) {
            npcChat(npc.id, DialogueEmote.LAUGH1, "What are you even doing in here?!", "Begone from me!")
            finish()
        }
        return true
    }
}
