package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Man : NpcModule {
    // Stats: 1: r=1 a=0 d=0 s=0 hp=7 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1, x = 2574, y = 9625, z = 0, face = 0),
    )


    override val definition = simpleNpcDefinition(
        name = "Man",
        entries = entries,
    )
}
