package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client

internal object Nathifa : NpcModule {
    // Stats: 3890: r=0 a=1 d=1 s=1 hp=0 rg=1 mg=1

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 3890, x = 3316, y = 2787, z = 0, face = 0),
    )
    val npcIds: IntArray = npcIdsFromEntries(entries)


    override val definition = legacyNpcDefinition(
        name = "Nathifa",
        entries = entries,
        onSecondClick = ::onSecondClick,
    )

    @Suppress("UNUSED_PARAMETER")
    fun onSecondClick(client: Client, npc: Npc): Boolean {
        client.WanneShop = 8
        return true
    }
}
