package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object OgreTrader : NpcModule {
    // Stats: 4401: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 4401, x = 2614, y = 9421, z = 0, face = 0),
    )


    override val definition = simpleNpcDefinition(
        name = "OgreTrader",
        entries = entries,
    )
}
