package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object PlaceholderNpc : NpcModule {
    // Stats: 56: r=1 a=0 d=0 s=0 hp=1 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 56, x = 3229, y = 3214, z = 0, face = 0),
    )


    override val definition = simpleNpcDefinition(
        name = "PlaceholderNpc",
        entries = entries,
    )
}
