package net.dodian.uber.net.codec.login

const val STATUS_EXCHANGE_DATA = 0
const val STATUS_DELAY = 1
const val STATUS_OK = 2
const val STATUS_INVALID_CREDENTIALS = 3
const val STATUS_ACCOUNT_DISABLED = 4
const val STATUS_ACCOUNT_ONLINE = 5
const val STATUS_GAME_UPDATED = 6
const val STATUS_SERVER_FULL = 7
const val STATUS_LOGIN_SERVER_OFFLINE = 8
const val STATUS_TOO_MANY_CONNECTIONS = 9
const val STATUS_BAD_SESSION_ID = 10
const val STATUS_LOGIN_SERVER_REJECTED_SESSION = 11
const val STATUS_MEMBERS_ACCOUNT_REQUIRED = 12
const val STATUS_COULD_NOT_COMPLETE = 13
const val STATUS_UPDATING = 14
const val STATUS_RECONNECTION_OK = 15
const val STATUS_TOO_MANY_LOGINS = 16
const val STATUS_IN_MEMBERS_AREA = 17
const val STATUS_INVALID_LOGIN_SERVER = 20
const val STATUS_PROFILE_TRANSFER = 21

const val TYPE_STANDARD = 16
const val TYPE_RECONNECTING = 18