package net.dodian.uber.game.content.npc

import net.dodian.uber.game.plugin.annotations.RegisterNpcContent

@RegisterNpcContent(module = Aubury::class, ownsSpawnDefinitions = true, explicitName = "Aubury")
@RegisterNpcContent(module = Banker::class, explicitName = "Banker")
@RegisterNpcContent(module = Monk::class, explicitName = "Monk")
@RegisterNpcContent(module = CustomsOfficer::class, explicitName = "CustomsOfficer")
@RegisterNpcContent(module = Mac::class, explicitName = "Mac")
@RegisterNpcContent(module = Saniboch::class, explicitName = "Saniboch")
@RegisterNpcContent(module = BabaYaga::class, explicitName = "BabaYaga")
@RegisterNpcContent(module = TzhaarMejJal::class, explicitName = "TzhaarMejJal")
@RegisterNpcContent(module = GnomeTrainer::class, explicitName = "GnomeTrainer")
@RegisterNpcContent(module = PiratePete::class, explicitName = "PiratePete")
@RegisterNpcContent(module = Sheep::class, explicitName = "Sheep")
@RegisterNpcContent(module = PartyAnnouncer::class, explicitName = "PartyAnnouncer")
@RegisterNpcContent(module = PopulationAnnouncer::class, explicitName = "PopulationAnnouncer")
@RegisterNpcContent(module = Zogre::class, explicitName = "Zogre")
@RegisterNpcContent(module = LegendsGuard::class, explicitName = "LegendsGuard")
@RegisterNpcContent(module = BeginnerStore::class, explicitName = "BeginnerStore")
@RegisterNpcContent(module = PremiumStore::class, explicitName = "PremiumStore")
@RegisterNpcContent(module = Wydin::class, explicitName = "Wydin")
@RegisterNpcContent(module = Dori::class, explicitName = "Dori")
@RegisterNpcContent(module = AliHag::class, explicitName = "AliHag")
@RegisterNpcContent(module = AgilityWerewolfMaster::class, explicitName = "AgilityWerewolfMaster")
@RegisterNpcContent(module = UnknownNpc683::class, explicitName = "UnknownNpc683")
@RegisterNpcContent(module = CaptainTobias::class, explicitName = "CaptainTobias")
@RegisterNpcContent(module = DukeHoracio::class, explicitName = "DukeHoracio")
@RegisterNpcContent(module = PartyPete::class, explicitName = "PartyPete")
@RegisterNpcContent(module = ShopKeeper::class, explicitName = "ShopKeeper")
@RegisterNpcContent(module = ShopAssistant::class, explicitName = "ShopAssistant")
@RegisterNpcContent(module = Cow::class, explicitName = "Cow")
@RegisterNpcContent(module = SurvivalExpert::class, explicitName = "SurvivalExpert")
@RegisterNpcContent(module = Farmer::class, explicitName = "Farmer")
@RegisterNpcContent(module = MasterFarmer::class, explicitName = "MasterFarmer")
@RegisterNpcContent(module = Sedridor::class, explicitName = "Sedridor")
@RegisterNpcContent(module = WizardCromperty::class, explicitName = "WizardCromperty")
@RegisterNpcContent(module = WizardDistentor::class, explicitName = "WizardDistentor")
@RegisterNpcContent(module = Ian::class, explicitName = "Ian")
@RegisterNpcContent(module = ThievingSkillcapeShop::class, explicitName = "ThievingSkillcapeShop")
@RegisterNpcContent(module = Wolfman::class, explicitName = "Wolfman")
@RegisterNpcContent(module = Peksa::class, explicitName = "Peksa")
@RegisterNpcContent(module = Rufu::class, explicitName = "Rufu")
@RegisterNpcContent(module = Nathifa::class, explicitName = "Nathifa")
@RegisterNpcContent(module = Horvik::class, explicitName = "Horvik")
@RegisterNpcContent(module = BowArrowSalesman::class, explicitName = "BowArrowSalesman")
@RegisterNpcContent(module = Gerrant::class, explicitName = "Gerrant")
@RegisterNpcContent(module = Tanner::class, explicitName = "Tanner")
@RegisterNpcContent(module = ArmourSalesman::class, explicitName = "ArmourSalesman")
@RegisterNpcContent(module = Shantay::class, explicitName = "Shantay")
@RegisterNpcContent(module = Mazchna::class, explicitName = "Mazchna")
@RegisterNpcContent(module = Vannaka::class, explicitName = "Vannaka")
@RegisterNpcContent(module = Duradel::class, explicitName = "Duradel")
@RegisterNpcContent(module = Jatix::class, explicitName = "Jatix")
@RegisterNpcContent(module = Zahur::class, explicitName = "Zahur")
@RegisterNpcContent(module = RugMerchant::class, explicitName = "RugMerchant")
@RegisterNpcContent(module = Turael::class, explicitName = "Turael")
@RegisterNpcContent(module = MakeoverMage::class, ownsSpawnDefinitions = true, explicitName = "MakeoverMage")
object NpcPluginModuleDeclarations
