package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object AberrantSpectre {
    // Stats: 2: r=35 a=80 d=80 s=80 hp=120 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2, x = 2648, y = 9861, z = 0, face = 0),
        NpcSpawnDef(npcId = 2, x = 2645, y = 9861, z = 0, face = 0),
        NpcSpawnDef(npcId = 2, x = 2646, y = 9864, z = 0, face = 0),
        NpcSpawnDef(npcId = 2, x = 2648, y = 9865, z = 0, face = 0),
        NpcSpawnDef(npcId = 2, x = 2643, y = 9866, z = 0, face = 0),
        NpcSpawnDef(npcId = 2, x = 2640, y = 9864, z = 0, face = 0),
        NpcSpawnDef(npcId = 2, x = 2642, y = 9862, z = 0, face = 0),
        NpcSpawnDef(npcId = 2, x = 2644, y = 9869, z = 0, face = 0),
    )
}
