package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BattleMage {
    // Stats: 1611: r=30 a=60 d=80 s=45 hp=75 rg=50 mg=3500

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1611, x = 2625, y = 3080, z = 0, face = 0),
        NpcSpawnDef(npcId = 1611, x = 2624, y = 3083, z = 0, face = 0),
        NpcSpawnDef(npcId = 1611, x = 2626, y = 3078, z = 0, face = 0),
        NpcSpawnDef(npcId = 1611, x = 2628, y = 3084, z = 0, face = 0),
        NpcSpawnDef(npcId = 1611, x = 2629, y = 3078, z = 0, face = 0),
    )
}
