package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BillyGoat {
    // Stats: 1794: r=150 a=40 d=40 s=40 hp=42 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1794, x = 3160, y = 3043, z = 0, face = 0),
    )
}
