package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ChaosDruid {
    // Stats: 2878: r=25 a=25 d=20 s=20 hp=30 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2878, x = 2925, y = 3479, z = 0, face = 0),
        NpcSpawnDef(npcId = 2878, x = 2923, y = 3485, z = 0, face = 0),
        NpcSpawnDef(npcId = 2878, x = 2922, y = 3482, z = 0, face = 0),
        NpcSpawnDef(npcId = 2878, x = 2928, y = 3481, z = 0, face = 0),
        NpcSpawnDef(npcId = 2878, x = 2928, y = 3485, z = 0, face = 0),
        NpcSpawnDef(npcId = 2878, x = 2926, y = 3487, z = 0, face = 0),
    )
}
