package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dagannoth {
    // Stats: 1338: r=60 a=0 d=0 s=0 hp=71 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1338, x = 1842, y = 4494, z = 0, face = 0),
    )
}
