package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DesertLizard {
    // Stats: 459: r=50 a=22 d=22 s=22 hp=33 rg=0 mg=0; 461: r=50 a=22 d=22 s=22 hp=33 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 459, x = 3411, y = 3038, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3416, y = 3039, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3414, y = 3041, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3412, y = 3043, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3424, y = 3038, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3419, y = 3048, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3415, y = 3047, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3412, y = 3048, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3409, y = 3045, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3408, y = 3041, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3405, y = 3043, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3405, y = 3039, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3408, y = 3037, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3418, y = 3043, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3422, y = 3045, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3422, y = 3041, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3426, y = 3039, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3429, y = 3043, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3426, y = 3045, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3429, y = 3048, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3425, y = 3050, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3434, y = 3050, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3434, y = 3046, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3433, y = 3042, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3429, y = 3039, z = 0, face = 0),
        NpcSpawnDef(npcId = 461, x = 3436, y = 3039, z = 0, face = 0),
        NpcSpawnDef(npcId = 459, x = 3420, y = 3038, z = 0, face = 0),
    )
}
