package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object FireGiant {
    // Stats: 2075: r=40 a=65 d=65 s=80 hp=105 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2075, x = 2614, y = 9488, z = 0, face = 0),
        NpcSpawnDef(npcId = 2075, x = 2611, y = 9488, z = 0, face = 0),
        NpcSpawnDef(npcId = 2075, x = 2610, y = 9485, z = 0, face = 0),
        NpcSpawnDef(npcId = 2075, x = 2615, y = 9483, z = 0, face = 0),
        NpcSpawnDef(npcId = 2075, x = 2611, y = 9483, z = 0, face = 0),
        NpcSpawnDef(npcId = 2075, x = 2616, y = 9486, z = 0, face = 0),
        NpcSpawnDef(npcId = 2075, x = 3275, y = 9835, z = 0, face = 0),
    )
}
