package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ghost {
    // Stats: 92: r=30 a=10 d=15 s=20 hp=20 rg=0 mg=0; 103: r=30 a=0 d=0 s=0 hp=50 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 92, x = 3202, y = 9881, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3206, y = 9883, z = 0, face = 0),
        NpcSpawnDef(npcId = 103, x = 3209, y = 9878, z = 0, face = 0),
        NpcSpawnDef(npcId = 103, x = 3205, y = 9881, z = 0, face = 0),
        NpcSpawnDef(npcId = 103, x = 3209, y = 9885, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3205, y = 9907, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3208, y = 9904, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3214, y = 9905, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3211, y = 9907, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3218, y = 9907, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3226, y = 9903, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3222, y = 9906, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3225, y = 9909, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3230, y = 9906, z = 0, face = 0),
        NpcSpawnDef(npcId = 103, x = 3248, y = 9916, z = 0, face = 0),
        NpcSpawnDef(npcId = 103, x = 3251, y = 9915, z = 0, face = 0),
        NpcSpawnDef(npcId = 103, x = 3256, y = 9916, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3277, y = 9892, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3284, y = 9891, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3282, y = 9897, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 2591, y = 9486, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 2593, y = 9489, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 2590, y = 9487, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 2589, y = 9489, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 2584, y = 9489, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 2586, y = 9487, z = 0, face = 0),
        NpcSpawnDef(npcId = 92, x = 3238, y = 9867, z = 0, face = 0),
    )
}
