package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object GiantSpider {
    // Stats: 59: r=60 a=0 d=0 s=0 hp=2 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 59, x = 3220, y = 9888, z = 0, face = 0),
        NpcSpawnDef(npcId = 59, x = 3217, y = 9890, z = 0, face = 0),
        NpcSpawnDef(npcId = 59, x = 3211, y = 9894, z = 0, face = 0),
        NpcSpawnDef(npcId = 59, x = 3212, y = 9886, z = 0, face = 0),
    )
}
