package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object GiantRat {
    // Stats: 2856: r=20 a=5 d=1 s=8 hp=6 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2856, x = 2600, y = 3103, z = 0, face = 4),
        NpcSpawnDef(npcId = 2856, x = 3240, y = 9867, z = 0, face = 0),
        NpcSpawnDef(npcId = 2856, x = 2601, y = 3103, z = 0, face = 4),
        NpcSpawnDef(npcId = 2856, x = 2602, y = 3103, z = 0, face = 4),
        NpcSpawnDef(npcId = 2856, x = 2599, y = 3103, z = 0, face = 4),
    )
}
