package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Goat {
    // Stats: 1795: r=50 a=20 d=20 s=20 hp=23 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1795, x = 3162, y = 3045, z = 0, face = 0),
        NpcSpawnDef(npcId = 1795, x = 3160, y = 3046, z = 0, face = 0),
        NpcSpawnDef(npcId = 1795, x = 3158, y = 3045, z = 0, face = 0),
        NpcSpawnDef(npcId = 1795, x = 3157, y = 3043, z = 0, face = 0),
        NpcSpawnDef(npcId = 1795, x = 3159, y = 3041, z = 0, face = 0),
        NpcSpawnDef(npcId = 1795, x = 3162, y = 3041, z = 0, face = 0),
        NpcSpawnDef(npcId = 1795, x = 3163, y = 3043, z = 0, face = 0),
    )
}
