package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object GreenDragon {
    // Stats: 260: r=40 a=65 d=60 s=70 hp=80 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 260, x = 3250, y = 9371, z = 0, face = 0),
        NpcSpawnDef(npcId = 260, x = 3251, y = 9367, z = 0, face = 0),
        NpcSpawnDef(npcId = 260, x = 3250, y = 9362, z = 0, face = 0),
        NpcSpawnDef(npcId = 260, x = 3251, y = 9357, z = 0, face = 0),
        NpcSpawnDef(npcId = 260, x = 3235, y = 9361, z = 0, face = 0),
        NpcSpawnDef(npcId = 260, x = 3233, y = 9358, z = 0, face = 0),
        NpcSpawnDef(npcId = 260, x = 3235, y = 9353, z = 0, face = 0),
        NpcSpawnDef(npcId = 260, x = 3238, y = 9350, z = 0, face = 0),
    )
}
