package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Guard {
    // Stats: 3094: r=30 a=10 d=15 s=22 hp=20 rg=0 mg=0; 32: r=60 a=0 d=0 s=0 hp=22 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 3094, x = 2615, y = 3106, z = 0, face = 0),
        NpcSpawnDef(npcId = 32, x = 3244, y = 9915, z = 0, face = 0),
        NpcSpawnDef(npcId = 32, x = 3242, y = 9916, z = 0, face = 0),
        NpcSpawnDef(npcId = 3094, x = 2619, y = 3104, z = 0, face = 0),
        NpcSpawnDef(npcId = 3094, x = 2617, y = 3106, z = 0, face = 0),
        NpcSpawnDef(npcId = 3094, x = 2620, y = 3106, z = 0, face = 0),
        NpcSpawnDef(npcId = 3094, x = 2615, y = 3103, z = 0, face = 0),
        NpcSpawnDef(npcId = 3094, x = 2617, y = 3104, z = 0, face = 0),
    )
}
