package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object HeadMourner {
    // Stats: 5311: r=90 a=132 d=122 s=230 hp=280 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 5311, x = 2552, y = 3278, z = 0, face = 0),
    )
}
