package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Hero {
    // Stats: 3106: r=35 a=45 d=40 s=45 hp=83 rg=1 mg=1

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 3106, x = 2542, y = 3090, z = 0, face = 2),
        NpcSpawnDef(npcId = 3106, x = 2540, y = 3089, z = 0, face = 2),
        NpcSpawnDef(npcId = 3106, x = 2541, y = 3097, z = 0, face = 0),
        NpcSpawnDef(npcId = 3106, x = 2539, y = 3098, z = 0, face = 0),
        NpcSpawnDef(npcId = 3106, x = 2543, y = 3088, z = 0, face = 0),
        NpcSpawnDef(npcId = 3106, x = 2539, y = 3095, z = 0, face = 0),
        NpcSpawnDef(npcId = 3106, x = 2539, y = 3091, z = 0, face = 0),
    )
}
