package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Koftik {
    // Stats: 972: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 973: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 974: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 975: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 972, x = 2912, y = 4390, z = 0, face = 0),
        NpcSpawnDef(npcId = 973, x = 2916, y = 4390, z = 0, face = 0),
        NpcSpawnDef(npcId = 974, x = 2917, y = 4387, z = 0, face = 0),
        NpcSpawnDef(npcId = 975, x = 2917, y = 4384, z = 0, face = 0),
    )
}
