package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object LocustRiderRanged {
    // Stats: 801: r=30 a=1 d=60 s=80 hp=62 rg=145 mg=300; 796: r=60 a=20 d=80 s=110 hp=92 rg=210 mg=300

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 801, x = 3237, y = 2775, z = 0, face = 0),
        NpcSpawnDef(npcId = 796, x = 3237, y = 2780, z = 0, face = 0),
        NpcSpawnDef(npcId = 801, x = 3310, y = 2831, z = 0, face = 0),
        NpcSpawnDef(npcId = 801, x = 3308, y = 2829, z = 0, face = 0),
        NpcSpawnDef(npcId = 801, x = 3313, y = 2834, z = 0, face = 0),
        NpcSpawnDef(npcId = 801, x = 3315, y = 2831, z = 0, face = 0),
        NpcSpawnDef(npcId = 801, x = 3312, y = 2828, z = 0, face = 0),
        NpcSpawnDef(npcId = 801, x = 3308, y = 2834, z = 0, face = 0),
        NpcSpawnDef(npcId = 801, x = 3311, y = 2837, z = 0, face = 0),
    )
}
