package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object LocustRiderMelee {
    // Stats: 795: r=60 a=70 d=90 s=130 hp=110 rg=100 mg=0; 800: r=30 a=50 d=60 s=70 hp=70 rg=70 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 795, x = 3241, y = 2779, z = 0, face = 0),
        NpcSpawnDef(npcId = 800, x = 3241, y = 2775, z = 0, face = 0),
        NpcSpawnDef(npcId = 800, x = 3322, y = 2823, z = 0, face = 0),
        NpcSpawnDef(npcId = 800, x = 3326, y = 2827, z = 0, face = 0),
        NpcSpawnDef(npcId = 800, x = 3328, y = 2824, z = 0, face = 0),
        NpcSpawnDef(npcId = 800, x = 3326, y = 2821, z = 0, face = 0),
        NpcSpawnDef(npcId = 800, x = 3321, y = 2828, z = 0, face = 0),
        NpcSpawnDef(npcId = 800, x = 3319, y = 2825, z = 0, face = 0),
        NpcSpawnDef(npcId = 800, x = 3317, y = 2828, z = 0, face = 0),
    )
}
