package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Mummy {
    // Stats: 950: r=40 a=75 d=75 s=90 hp=100 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 950, x = 2577, y = 9502, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2581, y = 9503, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2583, y = 9501, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2577, y = 9498, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2579, y = 9500, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2586, y = 9500, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2579, y = 9504, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2575, y = 9500, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2584, y = 9497, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2580, y = 9497, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2582, y = 9499, z = 0, face = 0),
        NpcSpawnDef(npcId = 950, x = 2588, y = 9498, z = 0, face = 0),
    )
}
