package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object OchreBlamishSnail {
    // Stats: 1229: r=60 a=0 d=0 s=0 hp=20 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1229, x = 2988, y = 9640, z = 0, face = 0),
        NpcSpawnDef(npcId = 1229, x = 2984, y = 9639, z = 0, face = 0),
        NpcSpawnDef(npcId = 1229, x = 2985, y = 9633, z = 0, face = 0),
        NpcSpawnDef(npcId = 1229, x = 2985, y = 9635, z = 0, face = 0),
        NpcSpawnDef(npcId = 1229, x = 2985, y = 9632, z = 0, face = 0),
    )
}
