package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object PollnivneachBanditBoss {
    // Stats: 738: r=155 a=75 d=75 s=110 hp=122 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 738, x = 3365, y = 2992, z = 0, face = 0),
    )
}
