package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object SandSnakeHard {
    // Stats: 7894: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 7894, x = 2445, y = 9892, z = 0, face = 0),
        NpcSpawnDef(npcId = 7894, x = 2442, y = 9881, z = 0, face = 0),
        NpcSpawnDef(npcId = 7894, x = 2391, y = 9877, z = 0, face = 0),
    )
}
