package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Scorpion {
    // Stats: 2479: r=60 a=55 d=60 s=50 hp=55 rg=0 mg=0; 3024: r=40 a=10 d=10 s=14 hp=22 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2479, x = 2524, y = 4776, z = 0, face = 0),
        NpcSpawnDef(npcId = 3024, x = 3314, y = 2870, z = 0, face = 0),
        NpcSpawnDef(npcId = 3024, x = 3313, y = 2875, z = 0, face = 0),
        NpcSpawnDef(npcId = 3024, x = 3310, y = 2873, z = 0, face = 0),
        NpcSpawnDef(npcId = 3024, x = 3310, y = 2869, z = 0, face = 0),
        NpcSpawnDef(npcId = 3024, x = 3313, y = 2866, z = 0, face = 0),
        NpcSpawnDef(npcId = 3024, x = 3317, y = 2867, z = 0, face = 0),
        NpcSpawnDef(npcId = 3024, x = 3321, y = 2869, z = 0, face = 0),
        NpcSpawnDef(npcId = 3024, x = 3323, y = 2866, z = 0, face = 0),
        NpcSpawnDef(npcId = 3024, x = 3319, y = 2864, z = 0, face = 0),
        NpcSpawnDef(npcId = 3024, x = 3315, y = 2864, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3160, y = 2911, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3158, y = 2909, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3161, y = 2905, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3159, y = 2902, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3164, y = 2901, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3167, y = 2898, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3169, y = 2895, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3173, y = 2897, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3176, y = 2895, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3178, y = 2898, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3182, y = 2900, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3183, y = 2905, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3185, y = 2908, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3183, y = 2911, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3185, y = 2915, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3184, y = 2918, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3182, y = 2921, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3180, y = 2923, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3177, y = 2926, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3172, y = 2927, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3166, y = 2924, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3164, y = 2922, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3161, y = 2920, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3162, y = 2917, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3158, y = 2915, z = 0, face = 0),
        NpcSpawnDef(npcId = 2479, x = 3155, y = 2912, z = 0, face = 0),
    )
}
