package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ShadowWarrior {
    // Stats: 2853: r=60 a=45 d=55 s=50 hp=65 rg=60 mg=60

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2853, x = 2719, y = 9754, z = 0, face = 0),
        NpcSpawnDef(npcId = 2853, x = 2723, y = 9750, z = 0, face = 0),
        NpcSpawnDef(npcId = 2853, x = 2725, y = 9755, z = 0, face = 0),
        NpcSpawnDef(npcId = 2853, x = 2714, y = 9749, z = 0, face = 0),
    )
}
