package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Skeleton {
    // Stats: 90: r=60 a=0 d=0 s=0 hp=29 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 90, x = 3203, y = 9881, z = 0, face = 0),
    )
}
