package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ThrowerTroll {
    // Stats: 1103: r=60 a=0 d=0 s=0 hp=96 rg=0 mg=0; 1105: r=60 a=0 d=0 s=0 hp=96 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1103, x = 3229, y = 3108, z = 0, face = 0),
        NpcSpawnDef(npcId = 1105, x = 3589, y = 3477, z = 0, face = 0),
    )
}
