package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Vampyre {
    // Stats: 3137: r=60 a=60 d=45 s=78 hp=85 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 3137, x = 3549, y = 3505, z = 0, face = 0),
        NpcSpawnDef(npcId = 3137, x = 3553, y = 3506, z = 0, face = 0),
        NpcSpawnDef(npcId = 3137, x = 3556, y = 3503, z = 0, face = 0),
        NpcSpawnDef(npcId = 3137, x = 3556, y = 3500, z = 0, face = 0),
        NpcSpawnDef(npcId = 3137, x = 3553, y = 3498, z = 0, face = 0),
        NpcSpawnDef(npcId = 3137, x = 3550, y = 3495, z = 0, face = 0),
        NpcSpawnDef(npcId = 3137, x = 3548, y = 3500, z = 0, face = 0),
        NpcSpawnDef(npcId = 3137, x = 3546, y = 3496, z = 0, face = 0),
        NpcSpawnDef(npcId = 3137, x = 3544, y = 3499, z = 0, face = 0),
        NpcSpawnDef(npcId = 3137, x = 3545, y = 3503, z = 0, face = 0),
        NpcSpawnDef(npcId = 3137, x = 3552, y = 3501, z = 0, face = 0),
    )
}
