package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Venenati {
    // Stats: 6610: r=250 a=160 d=250 s=170 hp=900 rg=1 mg=666

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 6610, x = 3220, y = 9933, z = 0, face = 0),
    )
}
