package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Wolf {
    // Stats: 106: r=60 a=30 d=30 s=30 hp=70 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 106, x = 2846, y = 3459, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2843, y = 3464, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2840, y = 3466, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2848, y = 3478, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2846, y = 3490, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2842, y = 3490, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2846, y = 3497, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2839, y = 3503, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2689, y = 9809, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2688, y = 9805, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2686, y = 9803, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2695, y = 9820, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2694, y = 9824, z = 0, face = 0),
        NpcSpawnDef(npcId = 106, x = 2695, y = 9830, z = 0, face = 0),
    )
}
