package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object AberrantSpectre {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 625, spawn = NpcSpawnDef(npcId = 2, x = 2648, y = 9861, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 626, spawn = NpcSpawnDef(npcId = 2, x = 2645, y = 9861, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 627, spawn = NpcSpawnDef(npcId = 2, x = 2646, y = 9864, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 628, spawn = NpcSpawnDef(npcId = 2, x = 2648, y = 9865, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 629, spawn = NpcSpawnDef(npcId = 2, x = 2643, y = 9866, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 630, spawn = NpcSpawnDef(npcId = 2, x = 2640, y = 9864, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 631, spawn = NpcSpawnDef(npcId = 2, x = 2642, y = 9862, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 893, spawn = NpcSpawnDef(npcId = 2, x = 2644, y = 9869, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
    )
}
