package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object AbyssalDemon {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 149, spawn = NpcSpawnDef(npcId = 415, x = 2869, y = 9777, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 150, spawn = NpcSpawnDef(npcId = 415, x = 2870, y = 9775, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 153, spawn = NpcSpawnDef(npcId = 415, x = 2873, y = 9777, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 221, spawn = NpcSpawnDef(npcId = 415, x = 2875, y = 9774, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 505, spawn = NpcSpawnDef(npcId = 415, x = 2870, y = 9780, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 506, spawn = NpcSpawnDef(npcId = 415, x = 2873, y = 9782, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 507, spawn = NpcSpawnDef(npcId = 415, x = 2875, y = 9784, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 508, spawn = NpcSpawnDef(npcId = 415, x = 2872, y = 9786, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 509, spawn = NpcSpawnDef(npcId = 415, x = 2870, y = 9784, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 510, spawn = NpcSpawnDef(npcId = 415, x = 2867, y = 9783, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 511, spawn = NpcSpawnDef(npcId = 415, x = 2875, y = 9787, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 512, spawn = NpcSpawnDef(npcId = 415, x = 2875, y = 9779, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 405)),
        SpawnEntry(index = 939, spawn = NpcSpawnDef(npcId = 415, x = 2868, y = 9772, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 200)),
        SpawnEntry(index = 941, spawn = NpcSpawnDef(npcId = 415, x = 2866, y = 9775, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 200)),
        SpawnEntry(index = 942, spawn = NpcSpawnDef(npcId = 415, x = 2865, y = 9778, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 200)),
        SpawnEntry(index = 943, spawn = NpcSpawnDef(npcId = 415, x = 2864, y = 9781, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 200)),
        SpawnEntry(index = 944, spawn = NpcSpawnDef(npcId = 415, x = 2868, y = 9779, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 200)),
        SpawnEntry(index = 945, spawn = NpcSpawnDef(npcId = 415, x = 2877, y = 9772, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 200)),
        SpawnEntry(index = 946, spawn = NpcSpawnDef(npcId = 415, x = 2876, y = 9769, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 200)),
        SpawnEntry(index = 947, spawn = NpcSpawnDef(npcId = 415, x = 2880, y = 9769, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 110, defence = 110, strength = 80, hitpoints = 200, ranged = 0, magic = 0), hitpoints = 200)),
    )
}
