package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object AbyssalGuardian {
    // Stats: 2585: r=90 a=80 d=130 s=65 hp=120 rg=0 mg=2650

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2585, x = 2627, y = 3082, z = 0, face = 0),
    )
}
