package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object AbyssalGuardian {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 8, spawn = NpcSpawnDef(npcId = 2585, x = 2627, y = 3082, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 90, attack = 80, defence = 130, strength = 65, hitpoints = 120, ranged = 0, magic = 2650), hitpoints = 200)),
    )
}
