package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ardougne {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 332, spawn = NpcSpawnDef(npcId = 3108, x = 2660, y = 3301, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 30, defence = 20, strength = 40, hitpoints = 52, ranged = 0, magic = 0), hitpoints = 52)),
        SpawnEntry(index = 333, spawn = NpcSpawnDef(npcId = 3108, x = 2665, y = 3301, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 30, defence = 20, strength = 40, hitpoints = 52, ranged = 0, magic = 0), hitpoints = 52)),
        SpawnEntry(index = 334, spawn = NpcSpawnDef(npcId = 3108, x = 2663, y = 3304, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 30, defence = 20, strength = 40, hitpoints = 52, ranged = 0, magic = 0), hitpoints = 52)),
        SpawnEntry(index = 335, spawn = NpcSpawnDef(npcId = 3108, x = 2659, y = 3310, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 30, defence = 20, strength = 40, hitpoints = 52, ranged = 0, magic = 0), hitpoints = 52)),
        SpawnEntry(index = 336, spawn = NpcSpawnDef(npcId = 3108, x = 2664, y = 3311, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 30, defence = 20, strength = 40, hitpoints = 52, ranged = 0, magic = 0), hitpoints = 52)),
        SpawnEntry(index = 337, spawn = NpcSpawnDef(npcId = 3108, x = 2658, y = 3306, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 30, defence = 20, strength = 40, hitpoints = 52, ranged = 0, magic = 0), hitpoints = 52)),
        SpawnEntry(index = 338, spawn = NpcSpawnDef(npcId = 3108, x = 2667, y = 3306, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 30, defence = 20, strength = 40, hitpoints = 52, ranged = 0, magic = 0), hitpoints = 52)),
        SpawnEntry(index = 630, spawn = NpcSpawnDef(npcId = 3108, x = 2662, y = 3309, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 30, defence = 20, strength = 40, hitpoints = 52, ranged = 0, magic = 0), hitpoints = 52)),
    )
}
