package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Aubury {
    // Stats: 637: r=0 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 637, x = 2594, y = 3104, z = 0, face = 0),
        NpcSpawnDef(npcId = 637, x = 3253, y = 3402, z = 0, face = 0),
    )
}
