package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BanditBoss {
    // Stats: 690: r=155 a=82 d=85 s=110 hp=138 rg=69 mg=69

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 690, x = 3177, y = 2987, z = 0, face = 0),
    )
}
