package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BerserkBarbarianSpirit {
    // Stats: 5565: r=35 a=100 d=100 s=90 hp=190 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 5565, x = 2578, y = 9811, z = 0, face = 0),
        NpcSpawnDef(npcId = 5565, x = 2665, y = 9806, z = 0, face = 0),
        NpcSpawnDef(npcId = 5565, x = 2659, y = 9806, z = 0, face = 0),
        NpcSpawnDef(npcId = 5565, x = 2666, y = 9810, z = 0, face = 0),
        NpcSpawnDef(npcId = 5565, x = 2659, y = 9811, z = 0, face = 0),
        NpcSpawnDef(npcId = 5565, x = 2662, y = 9809, z = 0, face = 0),
        NpcSpawnDef(npcId = 5565, x = 2655, y = 9807, z = 0, face = 0),
        NpcSpawnDef(npcId = 5565, x = 2664, y = 9796, z = 0, face = 0),
        NpcSpawnDef(npcId = 5565, x = 2660, y = 9795, z = 0, face = 0),
        NpcSpawnDef(npcId = 5565, x = 2659, y = 9798, z = 0, face = 0),
        NpcSpawnDef(npcId = 5565, x = 2663, y = 9799, z = 0, face = 0),
    )
}
