package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BillyGoat {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1229, spawn = NpcSpawnDef(npcId = 1794, x = 3160, y = 3043, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 150, attack = 40, defence = 40, strength = 40, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
