package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BloodBlamishSnail {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 193, spawn = NpcSpawnDef(npcId = 1228, x = 2962, y = 9633, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 194, spawn = NpcSpawnDef(npcId = 1228, x = 2962, y = 9635, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 10)),
    )
}
