package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Bloodveld {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 574, spawn = NpcSpawnDef(npcId = 1618, x = 2448, y = 4359, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 90, defence = 70, strength = 120, hitpoints = 180, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 575, spawn = NpcSpawnDef(npcId = 1618, x = 2454, y = 4361, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 90, defence = 70, strength = 120, hitpoints = 180, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 576, spawn = NpcSpawnDef(npcId = 1618, x = 2452, y = 4365, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 90, defence = 70, strength = 120, hitpoints = 180, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 593, spawn = NpcSpawnDef(npcId = 484, x = 2643, y = 9847, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 0, defence = 0, strength = 0, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 595, spawn = NpcSpawnDef(npcId = 484, x = 2648, y = 9843, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 0, defence = 0, strength = 0, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 602, spawn = NpcSpawnDef(npcId = 484, x = 2657, y = 9843, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 0, defence = 0, strength = 0, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 603, spawn = NpcSpawnDef(npcId = 484, x = 2664, y = 9852, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 0, defence = 0, strength = 0, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 604, spawn = NpcSpawnDef(npcId = 484, x = 2666, y = 9842, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 0, defence = 0, strength = 0, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 605, spawn = NpcSpawnDef(npcId = 484, x = 2666, y = 9850, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 0, defence = 0, strength = 0, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 606, spawn = NpcSpawnDef(npcId = 484, x = 2661, y = 9843, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 0, defence = 0, strength = 0, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 607, spawn = NpcSpawnDef(npcId = 484, x = 2652, y = 9843, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 0, defence = 0, strength = 0, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
    )
}
