package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BlueDragon {
    // Stats: 265: r=40 a=90 d=90 s=95 hp=110 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 265, x = 3247, y = 9360, z = 0, face = 0),
        NpcSpawnDef(npcId = 265, x = 3247, y = 9368, z = 0, face = 0),
        NpcSpawnDef(npcId = 265, x = 3242, y = 9371, z = 0, face = 0),
        NpcSpawnDef(npcId = 265, x = 3229, y = 9368, z = 0, face = 0),
        NpcSpawnDef(npcId = 265, x = 3236, y = 9374, z = 0, face = 0),
        NpcSpawnDef(npcId = 265, x = 3238, y = 9380, z = 0, face = 0),
        NpcSpawnDef(npcId = 265, x = 3242, y = 9383, z = 0, face = 0),
        NpcSpawnDef(npcId = 265, x = 3239, y = 9385, z = 0, face = 0),
        NpcSpawnDef(npcId = 265, x = 3237, y = 9387, z = 0, face = 0),
        NpcSpawnDef(npcId = 265, x = 3234, y = 9370, z = 0, face = 3),
    )
}
