package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BlueDragon {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 146, spawn = NpcSpawnDef(npcId = 265, x = 3247, y = 9360, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 95, hitpoints = 110, ranged = 0, magic = 0), hitpoints = 175)),
        SpawnEntry(index = 147, spawn = NpcSpawnDef(npcId = 265, x = 3247, y = 9368, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 95, hitpoints = 110, ranged = 0, magic = 0), hitpoints = 175)),
        SpawnEntry(index = 148, spawn = NpcSpawnDef(npcId = 265, x = 3242, y = 9371, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 95, hitpoints = 110, ranged = 0, magic = 0), hitpoints = 175)),
        SpawnEntry(index = 528, spawn = NpcSpawnDef(npcId = 265, x = 3229, y = 9368, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 95, hitpoints = 110, ranged = 0, magic = 0), hitpoints = 175)),
        SpawnEntry(index = 529, spawn = NpcSpawnDef(npcId = 265, x = 3236, y = 9374, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 95, hitpoints = 110, ranged = 0, magic = 0), hitpoints = 175)),
        SpawnEntry(index = 530, spawn = NpcSpawnDef(npcId = 265, x = 3238, y = 9380, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 95, hitpoints = 110, ranged = 0, magic = 0), hitpoints = 175)),
        SpawnEntry(index = 531, spawn = NpcSpawnDef(npcId = 265, x = 3242, y = 9383, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 95, hitpoints = 110, ranged = 0, magic = 0), hitpoints = 175)),
        SpawnEntry(index = 532, spawn = NpcSpawnDef(npcId = 265, x = 3239, y = 9385, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 95, hitpoints = 110, ranged = 0, magic = 0), hitpoints = 175)),
        SpawnEntry(index = 533, spawn = NpcSpawnDef(npcId = 265, x = 3237, y = 9387, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 95, hitpoints = 110, ranged = 0, magic = 0), hitpoints = 175)),
        SpawnEntry(index = 544, spawn = NpcSpawnDef(npcId = 265, x = 3234, y = 9370, z = 0, face = 3, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 95, hitpoints = 110, ranged = 0, magic = 0), hitpoints = 175)),
    )
}
