package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Boss {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 448, spawn = NpcSpawnDef(npcId = 47, x = 3236, y = 9867, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 463, spawn = NpcSpawnDef(npcId = 47, x = 3227, y = 9905, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 464, spawn = NpcSpawnDef(npcId = 47, x = 3224, y = 9907, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 465, spawn = NpcSpawnDef(npcId = 47, x = 3231, y = 9908, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 466, spawn = NpcSpawnDef(npcId = 47, x = 3210, y = 9903, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 467, spawn = NpcSpawnDef(npcId = 47, x = 3210, y = 9910, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 468, spawn = NpcSpawnDef(npcId = 47, x = 3184, y = 9891, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 469, spawn = NpcSpawnDef(npcId = 47, x = 3177, y = 9895, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 470, spawn = NpcSpawnDef(npcId = 47, x = 3172, y = 9884, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 471, spawn = NpcSpawnDef(npcId = 47, x = 3178, y = 9881, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 1053, spawn = NpcSpawnDef(npcId = 3551, x = 3350, y = 2949, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 155, attack = 75, defence = 75, strength = 110, hitpoints = 122, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1164, spawn = NpcSpawnDef(npcId = 738, x = 3365, y = 2992, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 155, attack = 75, defence = 75, strength = 110, hitpoints = 122, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1228, spawn = NpcSpawnDef(npcId = 690, x = 3177, y = 2987, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 155, attack = 82, defence = 85, strength = 110, hitpoints = 138, ranged = 69, magic = 69), hitpoints = 70)),
    )
}
