package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Boss {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 351, spawn = NpcSpawnDef(npcId = 47, x = 3333, y = 3333, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 459, spawn = NpcSpawnDef(npcId = 47, x = 3238, y = 9857, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 460, spawn = NpcSpawnDef(npcId = 47, x = 3226, y = 9862, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 461, spawn = NpcSpawnDef(npcId = 47, x = 3222, y = 9859, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 462, spawn = NpcSpawnDef(npcId = 47, x = 3219, y = 9865, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 463, spawn = NpcSpawnDef(npcId = 47, x = 3225, y = 9874, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 479, spawn = NpcSpawnDef(npcId = 47, x = 3227, y = 9905, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 480, spawn = NpcSpawnDef(npcId = 47, x = 3224, y = 9907, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 481, spawn = NpcSpawnDef(npcId = 47, x = 3231, y = 9908, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 482, spawn = NpcSpawnDef(npcId = 47, x = 3210, y = 9903, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 483, spawn = NpcSpawnDef(npcId = 47, x = 3210, y = 9910, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 484, spawn = NpcSpawnDef(npcId = 47, x = 3184, y = 9891, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 485, spawn = NpcSpawnDef(npcId = 47, x = 3177, y = 9895, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 486, spawn = NpcSpawnDef(npcId = 47, x = 3172, y = 9884, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 487, spawn = NpcSpawnDef(npcId = 47, x = 3178, y = 9881, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 1, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
    )
}
