package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BruiseBlamishSnail {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 200, spawn = NpcSpawnDef(npcId = 1230, x = 2989, y = 9634, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 13, ranged = 0, magic = 0), hitpoints = 13)),
        SpawnEntry(index = 201, spawn = NpcSpawnDef(npcId = 1230, x = 2988, y = 9637, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 13, ranged = 0, magic = 0), hitpoints = 13)),
        SpawnEntry(index = 202, spawn = NpcSpawnDef(npcId = 1230, x = 2987, y = 9640, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 13, ranged = 0, magic = 0), hitpoints = 13)),
        SpawnEntry(index = 203, spawn = NpcSpawnDef(npcId = 1230, x = 2985, y = 9638, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 13, ranged = 0, magic = 0), hitpoints = 13)),
    )
}
