package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ChaosDwarf {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 242, spawn = NpcSpawnDef(npcId = 291, x = 2955, y = 9794, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 43, defence = 43, strength = 43, hitpoints = 62, ranged = 0, magic = 0), hitpoints = 98)),
        SpawnEntry(index = 243, spawn = NpcSpawnDef(npcId = 291, x = 2961, y = 9785, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 43, defence = 43, strength = 43, hitpoints = 62, ranged = 0, magic = 0), hitpoints = 98)),
        SpawnEntry(index = 244, spawn = NpcSpawnDef(npcId = 291, x = 2966, y = 9794, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 43, defence = 43, strength = 43, hitpoints = 62, ranged = 0, magic = 0), hitpoints = 98)),
        SpawnEntry(index = 245, spawn = NpcSpawnDef(npcId = 291, x = 2955, y = 9775, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 43, defence = 43, strength = 43, hitpoints = 62, ranged = 0, magic = 0), hitpoints = 98)),
        SpawnEntry(index = 246, spawn = NpcSpawnDef(npcId = 291, x = 2961, y = 9780, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 43, defence = 43, strength = 43, hitpoints = 62, ranged = 0, magic = 0), hitpoints = 98)),
        SpawnEntry(index = 247, spawn = NpcSpawnDef(npcId = 291, x = 2966, y = 9775, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 43, defence = 43, strength = 43, hitpoints = 62, ranged = 0, magic = 0), hitpoints = 98)),
    )
}
