package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ChaosDruidWarrior {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 224, spawn = NpcSpawnDef(npcId = 2890, x = 2581, y = 3106, z = 0, face = 5, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 886, spawn = NpcSpawnDef(npcId = 2890, x = 2581, y = 3100, z = 0, face = 4, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 24)),
        SpawnEntry(index = 887, spawn = NpcSpawnDef(npcId = 2890, x = 2579, y = 3101, z = 0, face = 4, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 24)),
        SpawnEntry(index = 890, spawn = NpcSpawnDef(npcId = 2890, x = 2579, y = 3104, z = 0, face = 6, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 891, spawn = NpcSpawnDef(npcId = 2890, x = 2578, y = 3106, z = 0, face = 3, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 904, spawn = NpcSpawnDef(npcId = 2890, x = 2581, y = 3103, z = 0, face = 3, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 936, spawn = NpcSpawnDef(npcId = 2890, x = 2577, y = 3103, z = 0, face = 2, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 24)),
    )
}
