package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ChaosDruidWarrior {
    // Stats: 2890: r=30 a=18 d=22 s=32 hp=24 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2890, x = 2581, y = 3106, z = 0, face = 5),
        NpcSpawnDef(npcId = 2890, x = 2581, y = 3100, z = 0, face = 4),
        NpcSpawnDef(npcId = 2890, x = 2579, y = 3101, z = 0, face = 4),
        NpcSpawnDef(npcId = 2890, x = 2579, y = 3104, z = 0, face = 6),
        NpcSpawnDef(npcId = 2890, x = 2578, y = 3106, z = 0, face = 3),
        NpcSpawnDef(npcId = 2890, x = 2581, y = 3103, z = 0, face = 3),
        NpcSpawnDef(npcId = 2890, x = 2577, y = 3103, z = 0, face = 2),
    )
}
