package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Chicken {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1309, spawn = NpcSpawnDef(npcId = 3661, x = 2677, y = 3317, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 20, attack = 1, defence = 0, strength = 1, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 1310, spawn = NpcSpawnDef(npcId = 3661, x = 2680, y = 3317, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 20, attack = 1, defence = 0, strength = 1, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 1311, spawn = NpcSpawnDef(npcId = 3661, x = 2678, y = 3315, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 20, attack = 1, defence = 0, strength = 1, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 1312, spawn = NpcSpawnDef(npcId = 3661, x = 2677, y = 3313, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 20, attack = 1, defence = 0, strength = 1, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 1313, spawn = NpcSpawnDef(npcId = 3661, x = 2679, y = 3311, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 20, attack = 1, defence = 0, strength = 1, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 1314, spawn = NpcSpawnDef(npcId = 3661, x = 2682, y = 3312, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 20, attack = 1, defence = 0, strength = 1, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 1315, spawn = NpcSpawnDef(npcId = 3661, x = 2683, y = 3314, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 20, attack = 1, defence = 0, strength = 1, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 1316, spawn = NpcSpawnDef(npcId = 3661, x = 2682, y = 3316, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 20, attack = 1, defence = 0, strength = 1, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
    )
}
