package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Chicken {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 27, spawn = NpcSpawnDef(npcId = 2692, x = 2870, y = 2951, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 6, attack = 0, defence = 0, strength = 0, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 28, spawn = NpcSpawnDef(npcId = 2692, x = 2871, y = 2953, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 6, attack = 0, defence = 0, strength = 0, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 29, spawn = NpcSpawnDef(npcId = 2692, x = 2872, y = 2954, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 6, attack = 0, defence = 0, strength = 0, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 510, spawn = NpcSpawnDef(npcId = 3375, x = 1845, y = 4509, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 180, attack = 175, defence = 150, strength = 160, hitpoints = 550, ranged = 0, magic = 0), hitpoints = 550)),
        SpawnEntry(index = 574, spawn = NpcSpawnDef(npcId = 2692, x = 2748, y = 3471, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 6, attack = 0, defence = 0, strength = 0, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 677, spawn = NpcSpawnDef(npcId = 2692, x = 2746, y = 3472, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 6, attack = 0, defence = 0, strength = 0, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 688, spawn = NpcSpawnDef(npcId = 2692, x = 2750, y = 3475, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 6, attack = 0, defence = 0, strength = 0, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 689, spawn = NpcSpawnDef(npcId = 2692, x = 2745, y = 3475, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 6, attack = 0, defence = 0, strength = 0, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 690, spawn = NpcSpawnDef(npcId = 2692, x = 2748, y = 3476, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 6, attack = 0, defence = 0, strength = 0, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 691, spawn = NpcSpawnDef(npcId = 2692, x = 2749, y = 3473, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 6, attack = 0, defence = 0, strength = 0, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
        SpawnEntry(index = 692, spawn = NpcSpawnDef(npcId = 2692, x = 2747, y = 3474, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 6, attack = 0, defence = 0, strength = 0, hitpoints = 3, ranged = 0, magic = 0), hitpoints = 3)),
    )
}
