package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Count {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 665, spawn = NpcSpawnDef(npcId = 1225, x = 1837, y = 4534, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 24)),
    )
}
