package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Cow {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 35, spawn = NpcSpawnDef(npcId = 2805, x = 2604, y = 3114, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 1, strength = 1, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 36, spawn = NpcSpawnDef(npcId = 2805, x = 2609, y = 3115, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 1, strength = 1, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 37, spawn = NpcSpawnDef(npcId = 2805, x = 2608, y = 3112, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 1, strength = 1, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 678, spawn = NpcSpawnDef(npcId = 2805, x = 2602, y = 3116, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 1, strength = 1, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 679, spawn = NpcSpawnDef(npcId = 2805, x = 2601, y = 3113, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 1, strength = 1, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 693, spawn = NpcSpawnDef(npcId = 2805, x = 2605, y = 3116, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 1, strength = 1, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
    )
}
