package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Crocodile {
    // Stats: 4184: r=60 a=65 d=55 s=70 hp=78 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 4184, x = 3282, y = 2865, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3279, y = 2866, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3276, y = 2866, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3273, y = 2864, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3272, y = 2861, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3284, y = 2862, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3351, y = 2920, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3345, y = 2921, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3341, y = 2921, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3338, y = 2919, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3338, y = 2923, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3333, y = 2917, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3330, y = 2919, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3325, y = 2917, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3329, y = 2915, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3338, y = 2914, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3344, y = 2918, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3349, y = 2918, z = 0, face = 0),
        NpcSpawnDef(npcId = 4184, x = 3348, y = 2923, z = 0, face = 0),
    )
}
