package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dad {
    // Stats: 4130: r=180 a=80 d=90 s=110 hp=120 rg=1 mg=1

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 4130, x = 2541, y = 3092, z = 0, face = 3),
    )
}
