package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dad {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 57, spawn = NpcSpawnDef(npcId = 4130, x = 2541, y = 3092, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 180, attack = 60, defence = 40, strength = 80, hitpoints = 150, ranged = 1, magic = 1), hitpoints = 150)),
        SpawnEntry(index = 499, spawn = NpcSpawnDef(npcId = 4130, x = 1844, y = 4522, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 180, attack = 60, defence = 40, strength = 80, hitpoints = 150, ranged = 1, magic = 1), hitpoints = 150)),
    )
}
