package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dad {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 51, spawn = NpcSpawnDef(npcId = 4130, x = 2541, y = 3092, z = 0, face = 3, preset = NpcDataPreset(respawnTicks = 180, attack = 80, defence = 90, strength = 110, hitpoints = 120, ranged = 1, magic = 1), hitpoints = 150)),
    )
}
