package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DagannothPrime {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 498, spawn = NpcSpawnDef(npcId = 2266, x = 2907, y = 9727, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 120, attack = 180, defence = 200, strength = 180, hitpoints = 360, ranged = 250, magic = 0), hitpoints = 320)),
    )
}
