package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DagannothPrime {
    // Stats: 2266: r=120 a=180 d=200 s=180 hp=360 rg=250 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2266, x = 2907, y = 9727, z = 0, face = 0),
    )
}
