package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dagannoth {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 579, spawn = NpcSpawnDef(npcId = 1338, x = 1842, y = 4494, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 71, ranged = 0, magic = 0), hitpoints = 71)),
    )
}
