package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DeadlyRedSpider {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 363, spawn = NpcSpawnDef(npcId = 63, x = 3213, y = 9890, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 364, spawn = NpcSpawnDef(npcId = 63, x = 3210, y = 9897, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 591, spawn = NpcSpawnDef(npcId = 3021, x = 3600, y = 3481, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 972, spawn = NpcSpawnDef(npcId = 3021, x = 3604, y = 3481, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 974, spawn = NpcSpawnDef(npcId = 3021, x = 3601, y = 3478, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 975, spawn = NpcSpawnDef(npcId = 3021, x = 3603, y = 3484, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 976, spawn = NpcSpawnDef(npcId = 3021, x = 3596, y = 3481, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 977, spawn = NpcSpawnDef(npcId = 3021, x = 3593, y = 3483, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 978, spawn = NpcSpawnDef(npcId = 3021, x = 3591, y = 3479, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 979, spawn = NpcSpawnDef(npcId = 3021, x = 3593, y = 3476, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 980, spawn = NpcSpawnDef(npcId = 3021, x = 3595, y = 3473, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 981, spawn = NpcSpawnDef(npcId = 3021, x = 3598, y = 3474, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 982, spawn = NpcSpawnDef(npcId = 3021, x = 3601, y = 3472, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 983, spawn = NpcSpawnDef(npcId = 3021, x = 3603, y = 3475, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 984, spawn = NpcSpawnDef(npcId = 3021, x = 3596, y = 3477, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 38, strength = 68, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 50)),
    )
}
