package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DeathSpawn {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 270, spawn = NpcSpawnDef(npcId = 10, x = 2512, y = 3303, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 271, spawn = NpcSpawnDef(npcId = 10, x = 2512, y = 3307, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 272, spawn = NpcSpawnDef(npcId = 10, x = 2515, y = 3309, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 273, spawn = NpcSpawnDef(npcId = 10, x = 2512, y = 3311, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 274, spawn = NpcSpawnDef(npcId = 10, x = 2511, y = 3315, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 275, spawn = NpcSpawnDef(npcId = 10, x = 2514, y = 3315, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 276, spawn = NpcSpawnDef(npcId = 10, x = 2516, y = 3318, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 277, spawn = NpcSpawnDef(npcId = 10, x = 2513, y = 3319, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 278, spawn = NpcSpawnDef(npcId = 10, x = 2519, y = 3319, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 279, spawn = NpcSpawnDef(npcId = 10, x = 2519, y = 3322, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 280, spawn = NpcSpawnDef(npcId = 10, x = 2508, y = 3301, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 281, spawn = NpcSpawnDef(npcId = 10, x = 2508, y = 3297, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 282, spawn = NpcSpawnDef(npcId = 10, x = 2504, y = 3305, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
        SpawnEntry(index = 283, spawn = NpcSpawnDef(npcId = 10, x = 2516, y = 3297, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 60, defence = 30, strength = 25, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 93)),
    )
}
