package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DesertLizard {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1260, spawn = NpcSpawnDef(npcId = 459, x = 3411, y = 3038, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1261, spawn = NpcSpawnDef(npcId = 459, x = 3416, y = 3039, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1262, spawn = NpcSpawnDef(npcId = 459, x = 3414, y = 3041, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1263, spawn = NpcSpawnDef(npcId = 459, x = 3412, y = 3043, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1264, spawn = NpcSpawnDef(npcId = 461, x = 3424, y = 3038, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1265, spawn = NpcSpawnDef(npcId = 459, x = 3419, y = 3048, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1266, spawn = NpcSpawnDef(npcId = 459, x = 3415, y = 3047, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1267, spawn = NpcSpawnDef(npcId = 459, x = 3412, y = 3048, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1268, spawn = NpcSpawnDef(npcId = 459, x = 3409, y = 3045, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1269, spawn = NpcSpawnDef(npcId = 459, x = 3408, y = 3041, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1270, spawn = NpcSpawnDef(npcId = 459, x = 3405, y = 3043, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1271, spawn = NpcSpawnDef(npcId = 459, x = 3405, y = 3039, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1272, spawn = NpcSpawnDef(npcId = 459, x = 3408, y = 3037, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1273, spawn = NpcSpawnDef(npcId = 459, x = 3418, y = 3043, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1274, spawn = NpcSpawnDef(npcId = 461, x = 3422, y = 3045, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1275, spawn = NpcSpawnDef(npcId = 461, x = 3422, y = 3041, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1276, spawn = NpcSpawnDef(npcId = 461, x = 3426, y = 3039, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1277, spawn = NpcSpawnDef(npcId = 461, x = 3429, y = 3043, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1278, spawn = NpcSpawnDef(npcId = 461, x = 3426, y = 3045, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1279, spawn = NpcSpawnDef(npcId = 461, x = 3429, y = 3048, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1280, spawn = NpcSpawnDef(npcId = 461, x = 3425, y = 3050, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1281, spawn = NpcSpawnDef(npcId = 461, x = 3434, y = 3050, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1282, spawn = NpcSpawnDef(npcId = 461, x = 3434, y = 3046, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1283, spawn = NpcSpawnDef(npcId = 461, x = 3433, y = 3042, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1284, spawn = NpcSpawnDef(npcId = 461, x = 3429, y = 3039, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1285, spawn = NpcSpawnDef(npcId = 461, x = 3436, y = 3039, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
        SpawnEntry(index = 1286, spawn = NpcSpawnDef(npcId = 459, x = 3420, y = 3038, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 22, defence = 22, strength = 22, hitpoints = 33, ranged = 0, magic = 0), hitpoints = 33)),
    )
}
