package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DesertWolf {
    // Stats: 4649: r=60 a=50 d=50 s=60 hp=66 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 4649, x = 3327, y = 3027, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3329, y = 3035, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3325, y = 3032, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3321, y = 3030, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3323, y = 3037, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3319, y = 3038, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3316, y = 3035, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3314, y = 3032, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3316, y = 3029, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3319, y = 3027, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3328, y = 3040, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3324, y = 3042, z = 0, face = 0),
        NpcSpawnDef(npcId = 4649, x = 3319, y = 3043, z = 0, face = 0),
    )
}
