package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DesertWolf {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1045, spawn = NpcSpawnDef(npcId = 4649, x = 3327, y = 3027, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1050, spawn = NpcSpawnDef(npcId = 4649, x = 3329, y = 3035, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1051, spawn = NpcSpawnDef(npcId = 4649, x = 3325, y = 3032, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1056, spawn = NpcSpawnDef(npcId = 4649, x = 3321, y = 3030, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1106, spawn = NpcSpawnDef(npcId = 4649, x = 3323, y = 3037, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1107, spawn = NpcSpawnDef(npcId = 4649, x = 3319, y = 3038, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1108, spawn = NpcSpawnDef(npcId = 4649, x = 3316, y = 3035, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1109, spawn = NpcSpawnDef(npcId = 4649, x = 3314, y = 3032, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1110, spawn = NpcSpawnDef(npcId = 4649, x = 3316, y = 3029, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1111, spawn = NpcSpawnDef(npcId = 4649, x = 3319, y = 3027, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1112, spawn = NpcSpawnDef(npcId = 4649, x = 3328, y = 3040, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1113, spawn = NpcSpawnDef(npcId = 4649, x = 3324, y = 3042, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
        SpawnEntry(index = 1114, spawn = NpcSpawnDef(npcId = 4649, x = 3319, y = 3043, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 50, strength = 60, hitpoints = 66, ranged = 0, magic = 0), hitpoints = 66)),
    )
}
