package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Druid {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 81, spawn = NpcSpawnDef(npcId = 3098, x = 2897, y = 3442, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 13, attack = 30, defence = 15, strength = 15, hitpoints = 30, ranged = 0, magic = 0), hitpoints = 30)),
        SpawnEntry(index = 82, spawn = NpcSpawnDef(npcId = 3098, x = 2888, y = 3440, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 13, attack = 30, defence = 15, strength = 15, hitpoints = 30, ranged = 0, magic = 0), hitpoints = 30)),
        SpawnEntry(index = 83, spawn = NpcSpawnDef(npcId = 3098, x = 2893, y = 3433, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 13, attack = 30, defence = 15, strength = 15, hitpoints = 30, ranged = 0, magic = 0), hitpoints = 30)),
        SpawnEntry(index = 84, spawn = NpcSpawnDef(npcId = 3098, x = 2887, y = 3429, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 13, attack = 30, defence = 15, strength = 15, hitpoints = 30, ranged = 0, magic = 0), hitpoints = 30)),
        SpawnEntry(index = 85, spawn = NpcSpawnDef(npcId = 3098, x = 2891, y = 3422, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 13, attack = 30, defence = 15, strength = 15, hitpoints = 30, ranged = 0, magic = 0), hitpoints = 30)),
        SpawnEntry(index = 86, spawn = NpcSpawnDef(npcId = 3098, x = 2885, y = 3422, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 13, attack = 30, defence = 15, strength = 15, hitpoints = 30, ranged = 0, magic = 0), hitpoints = 30)),
        SpawnEntry(index = 87, spawn = NpcSpawnDef(npcId = 3098, x = 2884, y = 3430, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 13, attack = 30, defence = 15, strength = 15, hitpoints = 30, ranged = 0, magic = 0), hitpoints = 30)),
        SpawnEntry(index = 88, spawn = NpcSpawnDef(npcId = 3098, x = 2885, y = 3435, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 13, attack = 30, defence = 15, strength = 15, hitpoints = 30, ranged = 0, magic = 0), hitpoints = 30)),
    )
}
