package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Druid {
    // Stats: 3098: r=20 a=30 d=15 s=15 hp=30 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 3098, x = 2897, y = 3442, z = 0, face = 0),
        NpcSpawnDef(npcId = 3098, x = 2888, y = 3440, z = 0, face = 0),
        NpcSpawnDef(npcId = 3098, x = 2893, y = 3433, z = 0, face = 0),
        NpcSpawnDef(npcId = 3098, x = 2887, y = 3429, z = 0, face = 0),
        NpcSpawnDef(npcId = 3098, x = 2891, y = 3422, z = 0, face = 0),
        NpcSpawnDef(npcId = 3098, x = 2885, y = 3422, z = 0, face = 0),
        NpcSpawnDef(npcId = 3098, x = 2884, y = 3430, z = 0, face = 0),
        NpcSpawnDef(npcId = 3098, x = 2885, y = 3435, z = 0, face = 0),
    )
}
