package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dwarf {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 440, spawn = NpcSpawnDef(npcId = 290, x = 2625, y = 3128, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 8, defence = 5, strength = 15, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 442, spawn = NpcSpawnDef(npcId = 290, x = 2628, y = 3123, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 8, defence = 5, strength = 15, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 443, spawn = NpcSpawnDef(npcId = 290, x = 2624, y = 3123, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 8, defence = 5, strength = 15, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 444, spawn = NpcSpawnDef(npcId = 290, x = 2627, y = 3127, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 8, defence = 5, strength = 15, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 445, spawn = NpcSpawnDef(npcId = 290, x = 2625, y = 3125, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 8, defence = 5, strength = 15, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 446, spawn = NpcSpawnDef(npcId = 290, x = 2623, y = 3127, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 8, defence = 5, strength = 15, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 447, spawn = NpcSpawnDef(npcId = 290, x = 3243, y = 9867, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 8, defence = 5, strength = 15, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
