package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DwarfGangMember {
    // Stats: 1356: r=35 a=33 d=32 s=40 hp=50 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1356, x = 2555, y = 3087, z = 0, face = 0),
        NpcSpawnDef(npcId = 1356, x = 2556, y = 3089, z = 0, face = 0),
        NpcSpawnDef(npcId = 1356, x = 2555, y = 3091, z = 0, face = 0),
        NpcSpawnDef(npcId = 1356, x = 2560, y = 3087, z = 0, face = 0),
        NpcSpawnDef(npcId = 1356, x = 2557, y = 3086, z = 0, face = 0),
        NpcSpawnDef(npcId = 1356, x = 2558, y = 3092, z = 0, face = 0),
        NpcSpawnDef(npcId = 1356, x = 2560, y = 3090, z = 0, face = 0),
    )
}
