package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dwarf {
    // Stats: 290: r=30 a=8 d=5 s=15 hp=10 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 290, x = 2625, y = 3128, z = 0, face = 0),
        NpcSpawnDef(npcId = 290, x = 2628, y = 3123, z = 0, face = 0),
        NpcSpawnDef(npcId = 290, x = 2624, y = 3123, z = 0, face = 0),
        NpcSpawnDef(npcId = 290, x = 2627, y = 3127, z = 0, face = 0),
        NpcSpawnDef(npcId = 290, x = 2625, y = 3125, z = 0, face = 0),
        NpcSpawnDef(npcId = 290, x = 2623, y = 3127, z = 0, face = 0),
        NpcSpawnDef(npcId = 290, x = 3243, y = 9867, z = 0, face = 0),
    )
}
