package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object FinalBoss {
    // Stats: 47: r=60 a=0 d=0 s=1 hp=2 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 47, x = 3236, y = 9867, z = 0, face = 0),
        NpcSpawnDef(npcId = 47, x = 3227, y = 9905, z = 0, face = 0),
        NpcSpawnDef(npcId = 47, x = 3224, y = 9907, z = 0, face = 0),
        NpcSpawnDef(npcId = 47, x = 3231, y = 9908, z = 0, face = 0),
        NpcSpawnDef(npcId = 47, x = 3210, y = 9903, z = 0, face = 0),
        NpcSpawnDef(npcId = 47, x = 3210, y = 9910, z = 0, face = 0),
        NpcSpawnDef(npcId = 47, x = 3184, y = 9891, z = 0, face = 0),
        NpcSpawnDef(npcId = 47, x = 3177, y = 9895, z = 0, face = 0),
        NpcSpawnDef(npcId = 47, x = 3172, y = 9884, z = 0, face = 0),
        NpcSpawnDef(npcId = 47, x = 3178, y = 9881, z = 0, face = 0),
    )
}
