package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object FireGiant {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 52, spawn = NpcSpawnDef(npcId = 2075, x = 2614, y = 9488, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 65, defence = 65, strength = 80, hitpoints = 105, ranged = 0, magic = 0), hitpoints = 111)),
        SpawnEntry(index = 53, spawn = NpcSpawnDef(npcId = 2075, x = 2611, y = 9488, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 65, defence = 65, strength = 80, hitpoints = 105, ranged = 0, magic = 0), hitpoints = 111)),
        SpawnEntry(index = 54, spawn = NpcSpawnDef(npcId = 2075, x = 2610, y = 9485, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 65, defence = 65, strength = 80, hitpoints = 105, ranged = 0, magic = 0), hitpoints = 111)),
        SpawnEntry(index = 55, spawn = NpcSpawnDef(npcId = 2075, x = 2615, y = 9483, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 65, defence = 65, strength = 80, hitpoints = 105, ranged = 0, magic = 0), hitpoints = 111)),
        SpawnEntry(index = 56, spawn = NpcSpawnDef(npcId = 2075, x = 2611, y = 9483, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 65, defence = 65, strength = 80, hitpoints = 105, ranged = 0, magic = 0), hitpoints = 111)),
        SpawnEntry(index = 57, spawn = NpcSpawnDef(npcId = 2075, x = 2616, y = 9486, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 65, defence = 65, strength = 80, hitpoints = 105, ranged = 0, magic = 0), hitpoints = 111)),
        SpawnEntry(index = 472, spawn = NpcSpawnDef(npcId = 2075, x = 3275, y = 9835, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 65, defence = 65, strength = 80, hitpoints = 105, ranged = 0, magic = 0), hitpoints = 111)),
    )
}
