package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object FishSpot {
    // Stats: 1517: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 1511: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 1510: r=60 a=0 d=0 s=0 hp=2000 rg=0 mg=0; 1514: r=60 a=0 d=0 s=0 hp=250 rg=0 mg=0; 319: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1517, x = 2603, y = 3426, z = 0, face = 0),
        NpcSpawnDef(npcId = 1511, x = 2838, y = 3431, z = 0, face = 0),
        NpcSpawnDef(npcId = 1510, x = 2836, y = 3431, z = 0, face = 0),
        NpcSpawnDef(npcId = 1511, x = 2599, y = 3419, z = 0, face = 0),
        NpcSpawnDef(npcId = 1514, x = 2601, y = 3422, z = 0, face = 0),
        NpcSpawnDef(npcId = 1514, x = 2605, y = 3421, z = 0, face = 0),
        NpcSpawnDef(npcId = 1510, x = 2602, y = 3419, z = 0, face = 0),
        NpcSpawnDef(npcId = 1510, x = 2845, y = 3429, z = 0, face = 0),
        NpcSpawnDef(npcId = 1514, x = 2844, y = 3429, z = 0, face = 0),
        NpcSpawnDef(npcId = 1511, x = 2859, y = 3426, z = 0, face = 0),
        NpcSpawnDef(npcId = 1511, x = 2855, y = 3423, z = 0, face = 0),
        NpcSpawnDef(npcId = 1514, x = 2604, y = 3417, z = 0, face = 0),
        NpcSpawnDef(npcId = 1511, x = 2602, y = 3414, z = 0, face = 0),
        NpcSpawnDef(npcId = 1510, x = 2598, y = 3422, z = 0, face = 0),
        NpcSpawnDef(npcId = 1517, x = 2598, y = 3425, z = 0, face = 0),
        NpcSpawnDef(npcId = 319, x = 3245, y = 2789, z = 0, face = 0),
    )
}
