package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object FishSpot {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1, spawn = NpcSpawnDef(npcId = 1517, x = 2603, y = 3426, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0))),
        SpawnEntry(index = 21, spawn = NpcSpawnDef(npcId = 1510, x = 2865, y = 2972, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 2000, ranged = 0, magic = 0))),
        SpawnEntry(index = 22, spawn = NpcSpawnDef(npcId = 1510, x = 2860, y = 2972, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 2000, ranged = 0, magic = 0))),
        SpawnEntry(index = 23, spawn = NpcSpawnDef(npcId = 1511, x = 2855, y = 2974, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0))),
        SpawnEntry(index = 65, spawn = NpcSpawnDef(npcId = 1511, x = 2838, y = 3431, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0))),
        SpawnEntry(index = 66, spawn = NpcSpawnDef(npcId = 1510, x = 2836, y = 3431, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 2000, ranged = 0, magic = 0))),
        SpawnEntry(index = 136, spawn = NpcSpawnDef(npcId = 1511, x = 2599, y = 3419, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0))),
        SpawnEntry(index = 137, spawn = NpcSpawnDef(npcId = 1514, x = 2601, y = 3422, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 250, ranged = 0, magic = 0), hitpoints = 250)),
        SpawnEntry(index = 138, spawn = NpcSpawnDef(npcId = 1514, x = 2605, y = 3421, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 250, ranged = 0, magic = 0))),
        SpawnEntry(index = 139, spawn = NpcSpawnDef(npcId = 1510, x = 2602, y = 3419, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 2000, ranged = 0, magic = 0), hitpoints = 2000)),
        SpawnEntry(index = 144, spawn = NpcSpawnDef(npcId = 1510, x = 2845, y = 3429, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 2000, ranged = 0, magic = 0))),
        SpawnEntry(index = 145, spawn = NpcSpawnDef(npcId = 1514, x = 2844, y = 3429, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 250, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 146, spawn = NpcSpawnDef(npcId = 1511, x = 2859, y = 3426, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0))),
        SpawnEntry(index = 147, spawn = NpcSpawnDef(npcId = 1511, x = 2855, y = 3423, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0))),
        SpawnEntry(index = 191, spawn = NpcSpawnDef(npcId = 1514, x = 2604, y = 3417, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 250, ranged = 0, magic = 0))),
        SpawnEntry(index = 192, spawn = NpcSpawnDef(npcId = 1511, x = 2602, y = 3414, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0))),
        SpawnEntry(index = 573, spawn = NpcSpawnDef(npcId = 1510, x = 2598, y = 3422, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 2000, ranged = 0, magic = 0), hitpoints = 2000)),
        SpawnEntry(index = 694, spawn = NpcSpawnDef(npcId = 1517, x = 2598, y = 3425, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
