package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Gargoyle {
    // Stats: 412: r=35 a=95 d=70 s=95 hp=150 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 412, x = 2641, y = 9851, z = 0, face = 0),
        NpcSpawnDef(npcId = 412, x = 2649, y = 9855, z = 0, face = 0),
        NpcSpawnDef(npcId = 412, x = 2648, y = 9852, z = 0, face = 0),
        NpcSpawnDef(npcId = 412, x = 2646, y = 9848, z = 0, face = 0),
        NpcSpawnDef(npcId = 412, x = 2640, y = 9855, z = 0, face = 0),
        NpcSpawnDef(npcId = 412, x = 2646, y = 9851, z = 0, face = 0),
        NpcSpawnDef(npcId = 412, x = 2645, y = 9856, z = 0, face = 0),
        NpcSpawnDef(npcId = 412, x = 2640, y = 9856, z = 0, face = 0),
        NpcSpawnDef(npcId = 412, x = 2645, y = 9845, z = 0, face = 0),
        NpcSpawnDef(npcId = 412, x = 2644, y = 9851, z = 0, face = 0),
    )
}
