package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Gerrant {
    // Stats: 1027: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1027, x = 2871, y = 2968, z = 0, face = 0),
        NpcSpawnDef(npcId = 1027, x = 2835, y = 3442, z = 0, face = 0),
        NpcSpawnDef(npcId = 1027, x = 2597, y = 3401, z = 0, face = 0),
    )
}
