package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ghost {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 365, spawn = NpcSpawnDef(npcId = 103, x = 3209, y = 9878, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 366, spawn = NpcSpawnDef(npcId = 103, x = 3205, y = 9881, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 367, spawn = NpcSpawnDef(npcId = 103, x = 3209, y = 9885, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 383, spawn = NpcSpawnDef(npcId = 103, x = 3248, y = 9916, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 384, spawn = NpcSpawnDef(npcId = 103, x = 3251, y = 9915, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 385, spawn = NpcSpawnDef(npcId = 103, x = 3256, y = 9916, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
    )
}
