package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ghost {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 354, spawn = NpcSpawnDef(npcId = 92, x = 3202, y = 9881, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 355, spawn = NpcSpawnDef(npcId = 92, x = 3206, y = 9883, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 356, spawn = NpcSpawnDef(npcId = 103, x = 3209, y = 9878, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 357, spawn = NpcSpawnDef(npcId = 103, x = 3205, y = 9881, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 358, spawn = NpcSpawnDef(npcId = 103, x = 3209, y = 9885, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 365, spawn = NpcSpawnDef(npcId = 92, x = 3205, y = 9907, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 366, spawn = NpcSpawnDef(npcId = 92, x = 3208, y = 9904, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 367, spawn = NpcSpawnDef(npcId = 92, x = 3214, y = 9905, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 368, spawn = NpcSpawnDef(npcId = 92, x = 3211, y = 9907, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 369, spawn = NpcSpawnDef(npcId = 92, x = 3218, y = 9907, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 370, spawn = NpcSpawnDef(npcId = 92, x = 3226, y = 9903, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 371, spawn = NpcSpawnDef(npcId = 92, x = 3222, y = 9906, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 372, spawn = NpcSpawnDef(npcId = 92, x = 3225, y = 9909, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 373, spawn = NpcSpawnDef(npcId = 92, x = 3230, y = 9906, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 374, spawn = NpcSpawnDef(npcId = 103, x = 3248, y = 9916, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 375, spawn = NpcSpawnDef(npcId = 103, x = 3251, y = 9915, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 376, spawn = NpcSpawnDef(npcId = 103, x = 3256, y = 9916, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 0, defence = 0, strength = 0, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 377, spawn = NpcSpawnDef(npcId = 92, x = 3277, y = 9892, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 378, spawn = NpcSpawnDef(npcId = 92, x = 3284, y = 9891, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 379, spawn = NpcSpawnDef(npcId = 92, x = 3282, y = 9897, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 434, spawn = NpcSpawnDef(npcId = 92, x = 2591, y = 9486, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 435, spawn = NpcSpawnDef(npcId = 92, x = 2593, y = 9489, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 436, spawn = NpcSpawnDef(npcId = 92, x = 2590, y = 9487, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 437, spawn = NpcSpawnDef(npcId = 92, x = 2589, y = 9489, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 438, spawn = NpcSpawnDef(npcId = 92, x = 2584, y = 9489, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 439, spawn = NpcSpawnDef(npcId = 92, x = 2586, y = 9487, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
        SpawnEntry(index = 441, spawn = NpcSpawnDef(npcId = 92, x = 3238, y = 9867, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 10, defence = 15, strength = 20, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 29)),
    )
}
