package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ghoul {
    // Stats: 289: r=40 a=90 d=80 s=100 hp=115 rg=30 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 289, x = 2569, y = 9528, z = 0, face = 0),
        NpcSpawnDef(npcId = 289, x = 2572, y = 9526, z = 0, face = 0),
        NpcSpawnDef(npcId = 289, x = 2575, y = 9527, z = 0, face = 0),
        NpcSpawnDef(npcId = 289, x = 2575, y = 9529, z = 0, face = 0),
        NpcSpawnDef(npcId = 289, x = 2570, y = 9531, z = 0, face = 0),
        NpcSpawnDef(npcId = 289, x = 2567, y = 9526, z = 0, face = 0),
        NpcSpawnDef(npcId = 289, x = 2575, y = 9524, z = 0, face = 0),
        NpcSpawnDef(npcId = 289, x = 2578, y = 9523, z = 0, face = 0),
        NpcSpawnDef(npcId = 289, x = 2572, y = 9524, z = 0, face = 0),
    )
}
