package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ghoul {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 537, spawn = NpcSpawnDef(npcId = 289, x = 2569, y = 9528, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 85, defence = 75, strength = 90, hitpoints = 95, ranged = 30, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 538, spawn = NpcSpawnDef(npcId = 289, x = 2572, y = 9526, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 85, defence = 75, strength = 90, hitpoints = 95, ranged = 30, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 539, spawn = NpcSpawnDef(npcId = 289, x = 2575, y = 9527, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 85, defence = 75, strength = 90, hitpoints = 95, ranged = 30, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 540, spawn = NpcSpawnDef(npcId = 289, x = 2575, y = 9529, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 85, defence = 75, strength = 90, hitpoints = 95, ranged = 30, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 541, spawn = NpcSpawnDef(npcId = 289, x = 2570, y = 9531, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 85, defence = 75, strength = 90, hitpoints = 95, ranged = 30, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 542, spawn = NpcSpawnDef(npcId = 289, x = 2567, y = 9526, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 85, defence = 75, strength = 90, hitpoints = 95, ranged = 30, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 543, spawn = NpcSpawnDef(npcId = 289, x = 2575, y = 9524, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 85, defence = 75, strength = 90, hitpoints = 95, ranged = 30, magic = 0), hitpoints = 50)),
        SpawnEntry(index = 544, spawn = NpcSpawnDef(npcId = 289, x = 2578, y = 9523, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 85, defence = 75, strength = 90, hitpoints = 95, ranged = 30, magic = 0), hitpoints = 50)),
    )
}
