package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object GreaterDemon {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 254, spawn = NpcSpawnDef(npcId = 2025, x = 2916, y = 9804, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 95, defence = 95, strength = 99, hitpoints = 166, ranged = 0, magic = 0), hitpoints = 367)),
        SpawnEntry(index = 255, spawn = NpcSpawnDef(npcId = 2025, x = 2912, y = 9809, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 95, defence = 95, strength = 99, hitpoints = 166, ranged = 0, magic = 0), hitpoints = 367)),
        SpawnEntry(index = 256, spawn = NpcSpawnDef(npcId = 2025, x = 2904, y = 9799, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 95, defence = 95, strength = 99, hitpoints = 166, ranged = 0, magic = 0), hitpoints = 367)),
        SpawnEntry(index = 257, spawn = NpcSpawnDef(npcId = 2025, x = 2895, y = 9796, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 95, defence = 95, strength = 99, hitpoints = 166, ranged = 0, magic = 0), hitpoints = 222)),
        SpawnEntry(index = 545, spawn = NpcSpawnDef(npcId = 2025, x = 2914, y = 9801, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 95, defence = 95, strength = 99, hitpoints = 166, ranged = 0, magic = 0), hitpoints = 222)),
        SpawnEntry(index = 546, spawn = NpcSpawnDef(npcId = 2025, x = 2898, y = 9803, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 95, defence = 95, strength = 99, hitpoints = 166, ranged = 0, magic = 0), hitpoints = 222)),
        SpawnEntry(index = 547, spawn = NpcSpawnDef(npcId = 2025, x = 2909, y = 9798, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 95, defence = 95, strength = 99, hitpoints = 166, ranged = 0, magic = 0), hitpoints = 222)),
        SpawnEntry(index = 548, spawn = NpcSpawnDef(npcId = 2025, x = 2898, y = 9798, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 95, defence = 95, strength = 99, hitpoints = 166, ranged = 0, magic = 0), hitpoints = 222)),
        SpawnEntry(index = 549, spawn = NpcSpawnDef(npcId = 2025, x = 2902, y = 9802, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 95, defence = 95, strength = 99, hitpoints = 166, ranged = 0, magic = 0), hitpoints = 222)),
        SpawnEntry(index = 641, spawn = NpcSpawnDef(npcId = 2025, x = 2895, y = 9800, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 95, defence = 95, strength = 99, hitpoints = 166, ranged = 0, magic = 0), hitpoints = 222)),
    )
}
