package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Guardian {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 8, spawn = NpcSpawnDef(npcId = 2585, x = 2627, y = 3082, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 40, strength = 55, hitpoints = 180, ranged = 0, magic = 100), hitpoints = 200)),
        SpawnEntry(index = 395, spawn = NpcSpawnDef(npcId = 1157, x = 3510, y = 9502, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 423, spawn = NpcSpawnDef(npcId = 1157, x = 3467, y = 9489, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 424, spawn = NpcSpawnDef(npcId = 1157, x = 3466, y = 9483, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 425, spawn = NpcSpawnDef(npcId = 1157, x = 3469, y = 9479, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 426, spawn = NpcSpawnDef(npcId = 1157, x = 3480, y = 9476, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 427, spawn = NpcSpawnDef(npcId = 1157, x = 3487, y = 9476, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 428, spawn = NpcSpawnDef(npcId = 1157, x = 3497, y = 9475, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 429, spawn = NpcSpawnDef(npcId = 1157, x = 3506, y = 9482, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 430, spawn = NpcSpawnDef(npcId = 1157, x = 3511, y = 9491, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 431, spawn = NpcSpawnDef(npcId = 1157, x = 3514, y = 9499, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 432, spawn = NpcSpawnDef(npcId = 1157, x = 3505, y = 9499, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 433, spawn = NpcSpawnDef(npcId = 1157, x = 3506, y = 9493, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 434, spawn = NpcSpawnDef(npcId = 1157, x = 3514, y = 9495, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 503, spawn = NpcSpawnDef(npcId = 2585, x = 1843, y = 4512, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 40, strength = 55, hitpoints = 180, ranged = 0, magic = 100), hitpoints = 120)),
    )
}
