package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Hellhound {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 62, spawn = NpcSpawnDef(npcId = 104, x = 2705, y = 9752, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 90, hitpoints = 116, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 63, spawn = NpcSpawnDef(npcId = 104, x = 2702, y = 9748, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 90, hitpoints = 116, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 64, spawn = NpcSpawnDef(npcId = 104, x = 2705, y = 9745, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 90, hitpoints = 116, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 65, spawn = NpcSpawnDef(npcId = 104, x = 2702, y = 9742, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 90, hitpoints = 116, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 66, spawn = NpcSpawnDef(npcId = 104, x = 9705, y = 9740, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 90, hitpoints = 116, ranged = 0, magic = 0), hitpoints = 116)),
    )
}
