package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Hellhound {
    // Stats: 104: r=40 a=90 d=90 s=90 hp=116 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 104, x = 2705, y = 9752, z = 0, face = 0),
        NpcSpawnDef(npcId = 104, x = 2702, y = 9748, z = 0, face = 0),
        NpcSpawnDef(npcId = 104, x = 2705, y = 9745, z = 0, face = 0),
        NpcSpawnDef(npcId = 104, x = 2702, y = 9742, z = 0, face = 0),
        NpcSpawnDef(npcId = 104, x = 9705, y = 9740, z = 0, face = 0),
    )
}
