package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Hellhound {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 68, spawn = NpcSpawnDef(npcId = 104, x = 2705, y = 9752, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 90, hitpoints = 116, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 69, spawn = NpcSpawnDef(npcId = 104, x = 2702, y = 9748, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 90, hitpoints = 116, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 70, spawn = NpcSpawnDef(npcId = 104, x = 2705, y = 9745, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 90, hitpoints = 116, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 71, spawn = NpcSpawnDef(npcId = 104, x = 2702, y = 9742, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 90, hitpoints = 116, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 72, spawn = NpcSpawnDef(npcId = 104, x = 9705, y = 9740, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 90, defence = 90, strength = 90, hitpoints = 116, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 229, spawn = NpcSpawnDef(npcId = 5054, x = 2980, y = 9840, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 93, defence = 79, strength = 81, hitpoints = 247, ranged = 0, magic = 0), hitpoints = 295)),
        SpawnEntry(index = 242, spawn = NpcSpawnDef(npcId = 5054, x = 2911, y = 9837, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 93, defence = 79, strength = 81, hitpoints = 247, ranged = 0, magic = 0), hitpoints = 295)),
        SpawnEntry(index = 243, spawn = NpcSpawnDef(npcId = 5054, x = 2904, y = 9831, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 93, defence = 79, strength = 81, hitpoints = 247, ranged = 0, magic = 0), hitpoints = 295)),
        SpawnEntry(index = 244, spawn = NpcSpawnDef(npcId = 5054, x = 2910, y = 9829, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 93, defence = 79, strength = 81, hitpoints = 247, ranged = 0, magic = 0), hitpoints = 295)),
        SpawnEntry(index = 245, spawn = NpcSpawnDef(npcId = 5054, x = 2919, y = 9828, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 93, defence = 79, strength = 81, hitpoints = 247, ranged = 0, magic = 0), hitpoints = 295)),
        SpawnEntry(index = 246, spawn = NpcSpawnDef(npcId = 5054, x = 2927, y = 9830, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 93, defence = 79, strength = 81, hitpoints = 247, ranged = 0, magic = 0), hitpoints = 295)),
        SpawnEntry(index = 247, spawn = NpcSpawnDef(npcId = 5054, x = 2922, y = 9835, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 93, defence = 79, strength = 81, hitpoints = 247, ranged = 0, magic = 0), hitpoints = 295)),
        SpawnEntry(index = 265, spawn = NpcSpawnDef(npcId = 5054, x = 2905, y = 9839, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 93, defence = 79, strength = 81, hitpoints = 247, ranged = 0, magic = 0), hitpoints = 295)),
    )
}
