package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Hero {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 30, spawn = NpcSpawnDef(npcId = 3106, x = 2827, y = 2978, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 45, defence = 40, strength = 45, hitpoints = 83, ranged = 1, magic = 1), hitpoints = 83)),
        SpawnEntry(index = 31, spawn = NpcSpawnDef(npcId = 3106, x = 2828, y = 2982, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 45, defence = 40, strength = 45, hitpoints = 83, ranged = 1, magic = 1), hitpoints = 83)),
        SpawnEntry(index = 53, spawn = NpcSpawnDef(npcId = 3106, x = 2542, y = 3090, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 45, defence = 40, strength = 45, hitpoints = 83, ranged = 1, magic = 1), hitpoints = 83)),
        SpawnEntry(index = 54, spawn = NpcSpawnDef(npcId = 3106, x = 2540, y = 3089, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 45, defence = 40, strength = 45, hitpoints = 83, ranged = 1, magic = 1), hitpoints = 83)),
        SpawnEntry(index = 55, spawn = NpcSpawnDef(npcId = 3106, x = 2540, y = 3097, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 45, defence = 40, strength = 45, hitpoints = 83, ranged = 1, magic = 1), hitpoints = 83)),
        SpawnEntry(index = 56, spawn = NpcSpawnDef(npcId = 3106, x = 2541, y = 3096, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 45, defence = 40, strength = 45, hitpoints = 83, ranged = 1, magic = 1), hitpoints = 83)),
    )
}
