package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Highwayman {
    // Stats: 2876: r=30 a=6 d=2 s=12 hp=11 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2876, x = 2595, y = 3102, z = 0, face = 4),
    )
}
