package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Highwayman {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 318, spawn = NpcSpawnDef(npcId = 2876, x = 2595, y = 3102, z = 0, face = 4, preset = NpcDataPreset(respawnTicks = 30, attack = 6, defence = 2, strength = 12, hitpoints = 11, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
