package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client

internal object Horvik {
    // Stats: 535: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val npcIds: IntArray = intArrayOf(535)

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 535, x = 2615, y = 3083, z = 0, face = 0),
    )

    @Suppress("UNUSED_PARAMETER")
    fun onSecondClick(client: Client, npc: Npc): Boolean {
        client.WanneShop = 10
        return true
    }
}
