package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Horvik {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 521, spawn = NpcSpawnDef(npcId = 535, x = 2615, y = 3083, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
