package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object IceGiant {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 165, spawn = NpcSpawnDef(npcId = 2085, x = 2863, y = 9951, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 166, spawn = NpcSpawnDef(npcId = 2085, x = 2870, y = 9949, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 167, spawn = NpcSpawnDef(npcId = 2085, x = 2867, y = 9946, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 168, spawn = NpcSpawnDef(npcId = 2085, x = 2871, y = 9938, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 169, spawn = NpcSpawnDef(npcId = 2085, x = 2868, y = 9940, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 170, spawn = NpcSpawnDef(npcId = 2085, x = 2864, y = 9937, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 621, spawn = NpcSpawnDef(npcId = 2085, x = 2717, y = 9843, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 622, spawn = NpcSpawnDef(npcId = 2085, x = 2722, y = 9845, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 623, spawn = NpcSpawnDef(npcId = 2085, x = 2732, y = 9844, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 624, spawn = NpcSpawnDef(npcId = 2085, x = 2725, y = 9844, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 661, spawn = NpcSpawnDef(npcId = 2085, x = 2868, y = 9952, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 739, spawn = NpcSpawnDef(npcId = 2085, x = 2874, y = 9945, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 740, spawn = NpcSpawnDef(npcId = 2085, x = 2867, y = 9934, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 45, defence = 35, strength = 45, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
    )
}
