package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object IceGiant {
    // Stats: 2085: r=30 a=45 d=35 s=45 hp=70 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2085, x = 2863, y = 9951, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2870, y = 9949, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2867, y = 9946, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2871, y = 9938, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2868, y = 9940, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2864, y = 9937, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2717, y = 9843, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2722, y = 9845, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2732, y = 9844, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2725, y = 9844, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2868, y = 9952, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2874, y = 9945, z = 0, face = 0),
        NpcSpawnDef(npcId = 2085, x = 2867, y = 9934, z = 0, face = 0),
    )
}
