package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object IceQueen {
    // Stats: 4922: r=180 a=95 d=115 s=135 hp=285 rg=0 mg=1200

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 4922, x = 2865, y = 9953, z = 0, face = 0),
    )
}
