package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object IceQueen {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 164, spawn = NpcSpawnDef(npcId = 4922, x = 2865, y = 9953, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 180, attack = 95, defence = 115, strength = 135, hitpoints = 285, ranged = 0, magic = 1200), hitpoints = 250)),
    )
}
