package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object IceWarrior {
    // Stats: 2851: r=60 a=0 d=0 s=0 hp=60 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2851, x = 2855, y = 3510, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2851, y = 3509, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2842, y = 3504, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2839, y = 3502, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2837, y = 3506, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2835, y = 3508, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2832, y = 3512, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2698, y = 9837, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2695, y = 9836, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2700, y = 9841, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2706, y = 9842, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2711, y = 9844, z = 0, face = 0),
        NpcSpawnDef(npcId = 2851, x = 2709, y = 9841, z = 0, face = 0),
    )
}
