package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object IceWarrior {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 212, spawn = NpcSpawnDef(npcId = 2851, x = 2855, y = 3510, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 213, spawn = NpcSpawnDef(npcId = 2851, x = 2851, y = 3509, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 214, spawn = NpcSpawnDef(npcId = 2851, x = 2842, y = 3504, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 215, spawn = NpcSpawnDef(npcId = 2851, x = 2839, y = 3502, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 216, spawn = NpcSpawnDef(npcId = 2851, x = 2837, y = 3506, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 217, spawn = NpcSpawnDef(npcId = 2851, x = 2835, y = 3508, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 218, spawn = NpcSpawnDef(npcId = 2851, x = 2832, y = 3512, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 615, spawn = NpcSpawnDef(npcId = 2851, x = 2698, y = 9837, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 616, spawn = NpcSpawnDef(npcId = 2851, x = 2695, y = 9836, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 617, spawn = NpcSpawnDef(npcId = 2851, x = 2700, y = 9841, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 618, spawn = NpcSpawnDef(npcId = 2851, x = 2706, y = 9842, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 619, spawn = NpcSpawnDef(npcId = 2851, x = 2711, y = 9844, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 620, spawn = NpcSpawnDef(npcId = 2851, x = 2709, y = 9841, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
    )
}
