package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Jackal {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1096, spawn = NpcSpawnDef(npcId = 4185, x = 3391, y = 2943, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 30, strength = 34, hitpoints = 39, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1097, spawn = NpcSpawnDef(npcId = 4185, x = 3395, y = 2947, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 30, strength = 34, hitpoints = 39, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1098, spawn = NpcSpawnDef(npcId = 4185, x = 3391, y = 2948, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 30, strength = 34, hitpoints = 39, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1099, spawn = NpcSpawnDef(npcId = 4185, x = 3388, y = 2946, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 30, strength = 34, hitpoints = 39, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1100, spawn = NpcSpawnDef(npcId = 4185, x = 3394, y = 2944, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 30, strength = 34, hitpoints = 39, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1101, spawn = NpcSpawnDef(npcId = 4185, x = 3398, y = 2946, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 30, strength = 34, hitpoints = 39, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1102, spawn = NpcSpawnDef(npcId = 4185, x = 3398, y = 2950, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 30, strength = 34, hitpoints = 39, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1103, spawn = NpcSpawnDef(npcId = 4185, x = 3401, y = 2946, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 30, strength = 34, hitpoints = 39, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1104, spawn = NpcSpawnDef(npcId = 4185, x = 3403, y = 2950, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 30, strength = 34, hitpoints = 39, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1105, spawn = NpcSpawnDef(npcId = 4185, x = 3400, y = 2952, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 30, strength = 34, hitpoints = 39, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
