package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object JalTokJad {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 733, spawn = NpcSpawnDef(npcId = 7704, x = 3326, y = 3333, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
