package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client
import net.dodian.uber.game.content.dialogue.DialogueEmote
import net.dodian.uber.game.content.dialogue.DialogueOption
import net.dodian.uber.game.content.dialogue.DialogueService

internal object Jatix {
    // Stats: 1174: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1174, x = 2897, y = 3428, z = 0, face = 0),
    )

    val npcIds: IntArray = npcIdsFromEntries(entries)

    fun onFirstClick(client: Client, npc: Npc): Boolean {
        DialogueService.start(client) {
            npcChat(npc.id, DialogueEmote.DEFAULT, "Hello there adventurer ${client.playerName},", "is there anything you are looking for?")
            options(
                title = "What do you wish to do?",
                DialogueOption("Visit store") {
                    action { c -> c.WanneShop = 19 }
                    finish()
                },
                DialogueOption("Decant potions") {
                    action { c -> HerbloreNpcDialogue.openDecantDoseOptions(c, npc.id) }
                    finish(closeInterfaces = false)
                },
                DialogueOption("Nevermind") {
                    playerChat(DialogueEmote.ANGRY1, "Nevermind, I do not need anything.")
                    finish()
                },
            )
        }
        return true
    }

    @Suppress("UNUSED_PARAMETER")
    fun onSecondClick(client: Client, npc: Npc): Boolean {
        client.WanneShop = 19
        return true
    }
}
