package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Jelly {
    // Stats: 437: r=35 a=50 d=50 s=50 hp=75 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 437, x = 2548, y = 3315, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2542, y = 3314, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2542, y = 3318, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2538, y = 3321, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2537, y = 3318, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2538, y = 3325, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2535, y = 3328, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2530, y = 3326, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2531, y = 3323, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2535, y = 3322, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2532, y = 3319, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2528, y = 3322, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2524, y = 3325, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2527, y = 3328, z = 0, face = 0),
        NpcSpawnDef(npcId = 437, x = 2520, y = 3328, z = 0, face = 0),
    )
}
