package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Jelly {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 284, spawn = NpcSpawnDef(npcId = 437, x = 2548, y = 3315, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 285, spawn = NpcSpawnDef(npcId = 437, x = 2542, y = 3314, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 286, spawn = NpcSpawnDef(npcId = 437, x = 2542, y = 3318, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 287, spawn = NpcSpawnDef(npcId = 437, x = 2538, y = 3321, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 288, spawn = NpcSpawnDef(npcId = 437, x = 2537, y = 3318, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 289, spawn = NpcSpawnDef(npcId = 437, x = 2538, y = 3325, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 290, spawn = NpcSpawnDef(npcId = 437, x = 2535, y = 3328, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 291, spawn = NpcSpawnDef(npcId = 437, x = 2530, y = 3326, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 292, spawn = NpcSpawnDef(npcId = 437, x = 2531, y = 3323, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 293, spawn = NpcSpawnDef(npcId = 437, x = 2535, y = 3322, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 294, spawn = NpcSpawnDef(npcId = 437, x = 2532, y = 3319, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 295, spawn = NpcSpawnDef(npcId = 437, x = 2528, y = 3322, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 296, spawn = NpcSpawnDef(npcId = 437, x = 2524, y = 3325, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 297, spawn = NpcSpawnDef(npcId = 437, x = 2527, y = 3328, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
        SpawnEntry(index = 298, spawn = NpcSpawnDef(npcId = 437, x = 2520, y = 3328, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 50, defence = 50, strength = 50, hitpoints = 75, ranged = 0, magic = 0), hitpoints = 116)),
    )
}
