package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object JungleDemon {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 513, spawn = NpcSpawnDef(npcId = 1443, x = 2572, y = 9530, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 180, attack = 150, defence = 160, strength = 170, hitpoints = 350, ranged = 0, magic = 800), hitpoints = 450)),
    )
}
