package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteKing {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1308, spawn = NpcSpawnDef(npcId = 4304, x = 1711, y = 9845, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 250, attack = 1, defence = 250, strength = 66, hitpoints = 900, ranged = 290, magic = 1666), hitpoints = 0)),
    )
}
