package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteGuardian {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 385, spawn = NpcSpawnDef(npcId = 1157, x = 3510, y = 9502, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 413, spawn = NpcSpawnDef(npcId = 1157, x = 3467, y = 9489, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 414, spawn = NpcSpawnDef(npcId = 1157, x = 3466, y = 9483, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 415, spawn = NpcSpawnDef(npcId = 1157, x = 3469, y = 9479, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 416, spawn = NpcSpawnDef(npcId = 1157, x = 3480, y = 9476, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 417, spawn = NpcSpawnDef(npcId = 1157, x = 3487, y = 9476, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 418, spawn = NpcSpawnDef(npcId = 1157, x = 3497, y = 9475, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 419, spawn = NpcSpawnDef(npcId = 1157, x = 3506, y = 9482, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 420, spawn = NpcSpawnDef(npcId = 1157, x = 3511, y = 9491, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 421, spawn = NpcSpawnDef(npcId = 1157, x = 3514, y = 9499, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 422, spawn = NpcSpawnDef(npcId = 1157, x = 3505, y = 9499, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 423, spawn = NpcSpawnDef(npcId = 1157, x = 3506, y = 9493, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
        SpawnEntry(index = 424, spawn = NpcSpawnDef(npcId = 1157, x = 3514, y = 9495, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 70, attack = 80, defence = 80, strength = 90, hitpoints = 95, ranged = 0, magic = 0), hitpoints = 95)),
    )
}
