package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteSoldier {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 397, spawn = NpcSpawnDef(npcId = 1154, x = 3481, y = 9525, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 398, spawn = NpcSpawnDef(npcId = 1154, x = 3475, y = 9525, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 399, spawn = NpcSpawnDef(npcId = 1154, x = 3473, y = 9522, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 400, spawn = NpcSpawnDef(npcId = 1154, x = 3474, y = 9517, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 401, spawn = NpcSpawnDef(npcId = 1154, x = 3469, y = 9514, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 402, spawn = NpcSpawnDef(npcId = 1154, x = 3464, y = 9511, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 403, spawn = NpcSpawnDef(npcId = 1154, x = 3466, y = 9506, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 404, spawn = NpcSpawnDef(npcId = 1154, x = 3464, y = 9501, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 405, spawn = NpcSpawnDef(npcId = 1154, x = 3470, y = 9501, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 406, spawn = NpcSpawnDef(npcId = 1154, x = 3478, y = 9501, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 407, spawn = NpcSpawnDef(npcId = 1154, x = 3483, y = 9502, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 408, spawn = NpcSpawnDef(npcId = 1154, x = 3490, y = 9501, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 409, spawn = NpcSpawnDef(npcId = 1154, x = 3495, y = 9498, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 410, spawn = NpcSpawnDef(npcId = 1154, x = 3496, y = 9493, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 411, spawn = NpcSpawnDef(npcId = 1154, x = 3491, y = 9490, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 412, spawn = NpcSpawnDef(npcId = 1154, x = 3485, y = 9490, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 425, spawn = NpcSpawnDef(npcId = 1154, x = 3481, y = 9491, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 426, spawn = NpcSpawnDef(npcId = 1154, x = 3479, y = 9487, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 427, spawn = NpcSpawnDef(npcId = 1154, x = 3478, y = 9483, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 428, spawn = NpcSpawnDef(npcId = 1154, x = 3475, y = 9485, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 429, spawn = NpcSpawnDef(npcId = 1154, x = 3471, y = 9488, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 430, spawn = NpcSpawnDef(npcId = 1154, x = 3462, y = 9481, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 431, spawn = NpcSpawnDef(npcId = 1154, x = 3467, y = 9478, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 432, spawn = NpcSpawnDef(npcId = 1154, x = 3465, y = 9488, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 65, defence = 50, strength = 65, hitpoints = 70, ranged = 0, magic = 0), hitpoints = 70)),
    )
}
