package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteSoldier {
    // Stats: 1154: r=50 a=65 d=50 s=65 hp=70 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1154, x = 3481, y = 9525, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3475, y = 9525, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3473, y = 9522, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3474, y = 9517, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3469, y = 9514, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3464, y = 9511, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3466, y = 9506, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3464, y = 9501, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3470, y = 9501, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3478, y = 9501, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3483, y = 9502, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3490, y = 9501, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3495, y = 9498, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3496, y = 9493, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3491, y = 9490, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3485, y = 9490, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3481, y = 9491, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3479, y = 9487, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3478, y = 9483, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3475, y = 9485, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3471, y = 9488, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3462, y = 9481, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3467, y = 9478, z = 2, face = 0),
        NpcSpawnDef(npcId = 1154, x = 3465, y = 9488, z = 2, face = 0),
    )
}
