package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteKing {
    // Stats: 4304: r=250 a=1 d=250 s=66 hp=900 rg=290 mg=1666

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 4304, x = 1711, y = 9845, z = 0, face = 0),
    )
}
