package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteQueen {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 341, spawn = NpcSpawnDef(npcId = 4303, x = 3483, y = 9492, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 250, attack = 180, defence = 250, strength = 290, hitpoints = 900, ranged = 240, magic = 0), hitpoints = 0)),
    )
}
