package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteQueen {
    // Stats: 4303: r=250 a=180 d=250 s=290 hp=900 rg=240 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 4303, x = 3483, y = 9492, z = 0, face = 0),
    )
}
