package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ket {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 486, spawn = NpcSpawnDef(npcId = 2173, x = 2894, y = 9779, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
        SpawnEntry(index = 491, spawn = NpcSpawnDef(npcId = 2173, x = 2895, y = 9776, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
        SpawnEntry(index = 492, spawn = NpcSpawnDef(npcId = 2173, x = 2897, y = 9772, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
        SpawnEntry(index = 493, spawn = NpcSpawnDef(npcId = 2173, x = 2895, y = 9769, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
        SpawnEntry(index = 494, spawn = NpcSpawnDef(npcId = 2173, x = 2892, y = 9768, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
        SpawnEntry(index = 495, spawn = NpcSpawnDef(npcId = 2173, x = 2890, y = 9770, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
        SpawnEntry(index = 496, spawn = NpcSpawnDef(npcId = 2173, x = 2887, y = 9768, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
        SpawnEntry(index = 497, spawn = NpcSpawnDef(npcId = 2173, x = 2883, y = 9768, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
        SpawnEntry(index = 502, spawn = NpcSpawnDef(npcId = 2173, x = 2893, y = 9772, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
        SpawnEntry(index = 503, spawn = NpcSpawnDef(npcId = 2173, x = 2897, y = 9766, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
        SpawnEntry(index = 504, spawn = NpcSpawnDef(npcId = 2173, x = 2900, y = 9764, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 120, hitpoints = 155, ranged = 0, magic = 0), hitpoints = 155)),
    )
}
