package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Knight {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 680, spawn = NpcSpawnDef(npcId = 5793, x = 3049, y = 3378, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 681, spawn = NpcSpawnDef(npcId = 5793, x = 3048, y = 3378, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 682, spawn = NpcSpawnDef(npcId = 5793, x = 3047, y = 3378, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 683, spawn = NpcSpawnDef(npcId = 5793, x = 3046, y = 3378, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 684, spawn = NpcSpawnDef(npcId = 5793, x = 3045, y = 3378, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 685, spawn = NpcSpawnDef(npcId = 5793, x = 3044, y = 3378, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 686, spawn = NpcSpawnDef(npcId = 5793, x = 3043, y = 3378, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 687, spawn = NpcSpawnDef(npcId = 5793, x = 3042, y = 3378, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
