package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Knight {
    // Stats: 5793: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 5793, x = 3049, y = 3378, z = 0, face = 0),
        NpcSpawnDef(npcId = 5793, x = 3048, y = 3378, z = 0, face = 0),
        NpcSpawnDef(npcId = 5793, x = 3047, y = 3378, z = 0, face = 0),
        NpcSpawnDef(npcId = 5793, x = 3046, y = 3378, z = 0, face = 0),
        NpcSpawnDef(npcId = 5793, x = 3045, y = 3378, z = 0, face = 0),
        NpcSpawnDef(npcId = 5793, x = 3044, y = 3378, z = 0, face = 0),
        NpcSpawnDef(npcId = 5793, x = 3043, y = 3378, z = 0, face = 0),
        NpcSpawnDef(npcId = 5793, x = 3042, y = 3378, z = 0, face = 0),
    )
}
