package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Koftik {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1322, spawn = NpcSpawnDef(npcId = 972, x = 2912, y = 4390, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1323, spawn = NpcSpawnDef(npcId = 973, x = 2916, y = 4390, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1324, spawn = NpcSpawnDef(npcId = 974, x = 2917, y = 4387, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1325, spawn = NpcSpawnDef(npcId = 975, x = 2917, y = 4384, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
