package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Kolodion {
    // Stats: 910: r=300 a=0 d=0 s=0 hp=400 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 910, x = 2906, y = 9680, z = 0, face = 0),
    )
}
