package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Kolodion {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 226, spawn = NpcSpawnDef(npcId = 910, x = 2906, y = 9680, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 300, attack = 0, defence = 0, strength = 0, hitpoints = 400, ranged = 0, magic = 0), hitpoints = 900)),
        SpawnEntry(index = 672, spawn = NpcSpawnDef(npcId = 905, x = 1831, y = 4521, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 673, spawn = NpcSpawnDef(npcId = 910, x = 1830, y = 4521, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 300, attack = 0, defence = 0, strength = 0, hitpoints = 400, ranged = 0, magic = 0), hitpoints = 400)),
    )
}
