package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Leech {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 575, spawn = NpcSpawnDef(npcId = 2584, x = 2915, y = 4830, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 576, spawn = NpcSpawnDef(npcId = 2584, x = 2913, y = 4831, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 577, spawn = NpcSpawnDef(npcId = 2584, x = 2911, y = 4833, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 578, spawn = NpcSpawnDef(npcId = 2584, x = 2910, y = 4831, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 579, spawn = NpcSpawnDef(npcId = 2584, x = 2909, y = 4829, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 580, spawn = NpcSpawnDef(npcId = 2584, x = 2908, y = 4826, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 581, spawn = NpcSpawnDef(npcId = 2584, x = 2905, y = 4826, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 582, spawn = NpcSpawnDef(npcId = 2584, x = 2909, y = 4834, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 583, spawn = NpcSpawnDef(npcId = 2584, x = 2907, y = 4837, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 584, spawn = NpcSpawnDef(npcId = 2584, x = 2906, y = 4839, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 585, spawn = NpcSpawnDef(npcId = 2584, x = 2903, y = 4841, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 586, spawn = NpcSpawnDef(npcId = 2584, x = 2913, y = 4834, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 587, spawn = NpcSpawnDef(npcId = 2584, x = 2914, y = 4837, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 588, spawn = NpcSpawnDef(npcId = 2584, x = 2916, y = 4839, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 589, spawn = NpcSpawnDef(npcId = 2584, x = 2920, y = 4840, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 590, spawn = NpcSpawnDef(npcId = 2584, x = 2919, y = 4842, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 591, spawn = NpcSpawnDef(npcId = 2584, x = 2915, y = 4826, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 592, spawn = NpcSpawnDef(npcId = 2584, x = 2917, y = 4823, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 593, spawn = NpcSpawnDef(npcId = 2584, x = 2920, y = 4823, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 50, defence = 30, strength = 50, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 10)),
    )
}
