package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client

internal object LegendsGuard {
    // Stats: 3951: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 3951, x = 2727, y = 3349, z = 0, face = 0),
        NpcSpawnDef(npcId = 3951, x = 2730, y = 3349, z = 0, face = 0),
    )

    @Suppress("UNUSED_PARAMETER")
    fun onFirstClick(client: Client, npc: Npc): Boolean {
        if (client.premium) {
            client.ReplaceObject(2728, 3349, 2391, 0, 0)
            client.ReplaceObject(2729, 3349, 2392, -2, 0)
            client.showNPCChat(npc.id, 590, arrayOf("Welcome to the Guild of Legends", "Enjoy your stay."))
        } else {
            client.showNPCChat(npc.id, 595, arrayOf("You must be a premium member to enter", "Visit Dodian.net to subscribe"))
        }
        return true
    }
}
