package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object LegendsGuard {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 0, spawn = NpcSpawnDef(npcId = 3951, x = 2727, y = 3349, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 137, spawn = NpcSpawnDef(npcId = 3951, x = 2730, y = 3349, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
