package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Lizard {
    // Stats: 458: r=60 a=33 d=33 s=33 hp=55 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 458, x = 3415, y = 3062, z = 0, face = 0),
        NpcSpawnDef(npcId = 458, x = 3418, y = 3066, z = 0, face = 0),
        NpcSpawnDef(npcId = 458, x = 3422, y = 3064, z = 0, face = 0),
        NpcSpawnDef(npcId = 458, x = 3427, y = 3067, z = 0, face = 0),
        NpcSpawnDef(npcId = 458, x = 3428, y = 3064, z = 0, face = 0),
        NpcSpawnDef(npcId = 458, x = 3427, y = 3060, z = 0, face = 0),
        NpcSpawnDef(npcId = 458, x = 3423, y = 3058, z = 0, face = 0),
        NpcSpawnDef(npcId = 458, x = 3419, y = 3060, z = 0, face = 0),
        NpcSpawnDef(npcId = 458, x = 3417, y = 3058, z = 0, face = 0),
        NpcSpawnDef(npcId = 458, x = 3412, y = 3060, z = 0, face = 0),
        NpcSpawnDef(npcId = 458, x = 3412, y = 3067, z = 0, face = 0),
    )
}
