package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Mahogany {
    // Stats: 2534: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2534, x = 2677, y = 3585, z = 0, face = 0),
        NpcSpawnDef(npcId = 2534, x = 2682, y = 3596, z = 0, face = 0),
    )
}
