package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Mejkot {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 320, spawn = NpcSpawnDef(npcId = 3123, x = 2409, y = 5082, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 140, defence = 130, strength = 190, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 474, spawn = NpcSpawnDef(npcId = 3123, x = 2396, y = 5078, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 140, defence = 130, strength = 190, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 480, spawn = NpcSpawnDef(npcId = 3123, x = 2400, y = 5073, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 140, defence = 130, strength = 190, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 481, spawn = NpcSpawnDef(npcId = 3123, x = 2403, y = 5076, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 140, defence = 130, strength = 190, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 633, spawn = NpcSpawnDef(npcId = 3123, x = 2410, y = 5079, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 140, defence = 130, strength = 190, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 634, spawn = NpcSpawnDef(npcId = 3123, x = 2409, y = 5074, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 140, defence = 130, strength = 190, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 915, spawn = NpcSpawnDef(npcId = 3123, x = 2386, y = 5078, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 140, defence = 130, strength = 190, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 916, spawn = NpcSpawnDef(npcId = 3123, x = 2391, y = 5074, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 140, defence = 130, strength = 190, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 150)),
    )
}
