package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Member {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 883, spawn = NpcSpawnDef(npcId = 1356, x = 2555, y = 3087, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 33, defence = 32, strength = 40, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 100)),
        SpawnEntry(index = 884, spawn = NpcSpawnDef(npcId = 1356, x = 2556, y = 3089, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 33, defence = 32, strength = 40, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 100)),
        SpawnEntry(index = 885, spawn = NpcSpawnDef(npcId = 1356, x = 2555, y = 3091, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 33, defence = 32, strength = 40, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 100)),
        SpawnEntry(index = 888, spawn = NpcSpawnDef(npcId = 1356, x = 2560, y = 3087, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 33, defence = 32, strength = 40, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 100)),
        SpawnEntry(index = 889, spawn = NpcSpawnDef(npcId = 1356, x = 2557, y = 3086, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 33, defence = 32, strength = 40, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 100)),
        SpawnEntry(index = 905, spawn = NpcSpawnDef(npcId = 1356, x = 2558, y = 3092, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 33, defence = 32, strength = 40, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 100)),
        SpawnEntry(index = 906, spawn = NpcSpawnDef(npcId = 1356, x = 2560, y = 3090, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 33, defence = 32, strength = 40, hitpoints = 50, ranged = 0, magic = 0), hitpoints = 100)),
    )
}
