package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object MenaphiteThugBoss {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1053, spawn = NpcSpawnDef(npcId = 3551, x = 3350, y = 2949, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 155, attack = 75, defence = 75, strength = 110, hitpoints = 122, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
