package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Merchant {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1038, spawn = NpcSpawnDef(npcId = 17, x = 3287, y = 2814, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 18, ranged = 0, magic = 0), hitpoints = 18)),
        SpawnEntry(index = 1039, spawn = NpcSpawnDef(npcId = 22, x = 3401, y = 2918, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1040, spawn = NpcSpawnDef(npcId = 20, x = 3348, y = 3002, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 10, attack = 0, defence = 0, strength = 0, hitpoints = 99, ranged = 0, magic = 0), hitpoints = 99)),
        SpawnEntry(index = 1041, spawn = NpcSpawnDef(npcId = 19, x = 3181, y = 3045, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 52, ranged = 0, magic = 0), hitpoints = 52)),
    )
}
