package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object MithrilDragon {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 303, spawn = NpcSpawnDef(npcId = 2919, x = 2661, y = 9823, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 200, defence = 220, strength = 230, hitpoints = 250, ranged = 0, magic = 0), hitpoints = 230)),
        SpawnEntry(index = 304, spawn = NpcSpawnDef(npcId = 2919, x = 2656, y = 9828, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 200, defence = 220, strength = 230, hitpoints = 250, ranged = 0, magic = 0), hitpoints = 230)),
        SpawnEntry(index = 305, spawn = NpcSpawnDef(npcId = 2919, x = 2666, y = 9825, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 200, defence = 220, strength = 230, hitpoints = 250, ranged = 0, magic = 0), hitpoints = 230)),
        SpawnEntry(index = 314, spawn = NpcSpawnDef(npcId = 2919, x = 2665, y = 9832, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 200, defence = 220, strength = 230, hitpoints = 250, ranged = 0, magic = 0), hitpoints = 230)),
        SpawnEntry(index = 315, spawn = NpcSpawnDef(npcId = 2919, x = 2660, y = 9820, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 200, defence = 220, strength = 230, hitpoints = 250, ranged = 0, magic = 0), hitpoints = 220)),
    )
}
