package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object MossGiant {
    // Stats: 3851: r=35 a=30 d=30 s=40 hp=47 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 3851, x = 2575, y = 3086, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 2578, y = 3079, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 2576, y = 3076, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 2579, y = 3083, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 3155, y = 9903, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 3166, y = 9896, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 3174, y = 9896, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 3169, y = 9890, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 3164, y = 9887, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 3170, y = 9884, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 3165, y = 9879, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 3180, y = 9886, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 3184, y = 9892, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 2573, y = 3082, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 2574, y = 3079, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 2572, y = 3088, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 2579, y = 3089, z = 0, face = 0),
        NpcSpawnDef(npcId = 3851, x = 2576, y = 3089, z = 0, face = 0),
    )
}
