package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Mummy {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 74, spawn = NpcSpawnDef(npcId = 950, x = 2577, y = 9502, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 70, hitpoints = 91, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 75, spawn = NpcSpawnDef(npcId = 950, x = 2581, y = 9502, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 70, hitpoints = 91, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 76, spawn = NpcSpawnDef(npcId = 950, x = 2581, y = 9498, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 70, hitpoints = 91, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 77, spawn = NpcSpawnDef(npcId = 950, x = 2577, y = 9498, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 70, hitpoints = 91, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 78, spawn = NpcSpawnDef(npcId = 950, x = 2579, y = 9500, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 70, hitpoints = 91, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 594, spawn = NpcSpawnDef(npcId = 950, x = 2586, y = 9497, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 70, hitpoints = 91, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 595, spawn = NpcSpawnDef(npcId = 950, x = 2580, y = 9504, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 70, hitpoints = 91, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 596, spawn = NpcSpawnDef(npcId = 950, x = 2575, y = 9500, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 70, hitpoints = 91, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 601, spawn = NpcSpawnDef(npcId = 950, x = 2583, y = 9500, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 70, hitpoints = 91, ranged = 0, magic = 0), hitpoints = 91)),
    )
}
