package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Mummy {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 68, spawn = NpcSpawnDef(npcId = 950, x = 2577, y = 9502, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 69, spawn = NpcSpawnDef(npcId = 950, x = 2581, y = 9503, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 70, spawn = NpcSpawnDef(npcId = 950, x = 2583, y = 9501, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 71, spawn = NpcSpawnDef(npcId = 950, x = 2577, y = 9498, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 72, spawn = NpcSpawnDef(npcId = 950, x = 2579, y = 9500, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 571, spawn = NpcSpawnDef(npcId = 950, x = 2586, y = 9500, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 572, spawn = NpcSpawnDef(npcId = 950, x = 2579, y = 9504, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 573, spawn = NpcSpawnDef(npcId = 950, x = 2575, y = 9500, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 578, spawn = NpcSpawnDef(npcId = 950, x = 2584, y = 9497, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 737, spawn = NpcSpawnDef(npcId = 950, x = 2580, y = 9497, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 881, spawn = NpcSpawnDef(npcId = 950, x = 2582, y = 9499, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 882, spawn = NpcSpawnDef(npcId = 950, x = 2588, y = 9498, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 75, defence = 75, strength = 90, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 1191, spawn = NpcSpawnDef(npcId = 953, x = 3221, y = 2942, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1192, spawn = NpcSpawnDef(npcId = 953, x = 3226, y = 2943, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1193, spawn = NpcSpawnDef(npcId = 953, x = 3223, y = 2945, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1194, spawn = NpcSpawnDef(npcId = 953, x = 3225, y = 2940, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1195, spawn = NpcSpawnDef(npcId = 953, x = 3222, y = 2938, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1196, spawn = NpcSpawnDef(npcId = 953, x = 3219, y = 2940, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1197, spawn = NpcSpawnDef(npcId = 953, x = 3216, y = 2942, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1198, spawn = NpcSpawnDef(npcId = 953, x = 3217, y = 2946, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1199, spawn = NpcSpawnDef(npcId = 953, x = 3212, y = 2944, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1200, spawn = NpcSpawnDef(npcId = 953, x = 3214, y = 2940, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1201, spawn = NpcSpawnDef(npcId = 953, x = 3217, y = 2938, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1202, spawn = NpcSpawnDef(npcId = 953, x = 3220, y = 2936, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1203, spawn = NpcSpawnDef(npcId = 953, x = 3224, y = 2935, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1204, spawn = NpcSpawnDef(npcId = 953, x = 3228, y = 2938, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 50, attack = 68, defence = 68, strength = 85, hitpoints = 88, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
