package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object MyreBlamishSnail {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 188, spawn = NpcSpawnDef(npcId = 1227, x = 2964, y = 9636, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 189, spawn = NpcSpawnDef(npcId = 1227, x = 2962, y = 9633, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 190, spawn = NpcSpawnDef(npcId = 1227, x = 2960, y = 9632, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 191, spawn = NpcSpawnDef(npcId = 1227, x = 2963, y = 9632, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 192, spawn = NpcSpawnDef(npcId = 1227, x = 2963, y = 9635, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
    )
}
