package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Nathifa {
    // Stats: 3890: r=0 a=1 d=1 s=1 hp=0 rg=1 mg=1

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 3890, x = 3316, y = 2787, z = 0, face = 0),
    )
}
