package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Nathifa {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1023, spawn = NpcSpawnDef(npcId = 3890, x = 3316, y = 2787, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 0, attack = 1, defence = 1, strength = 1, hitpoints = 0, ranged = 1, magic = 1), hitpoints = 0)),
    )
}
