package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Nechryael {
    // Stats: 8: r=180 a=140 d=140 s=130 hp=350 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 8, x = 2698, y = 9773, z = 0, face = 0),
    )
}
