package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Nechryael {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 61, spawn = NpcSpawnDef(npcId = 8, x = 2698, y = 9773, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 180, attack = 140, defence = 140, strength = 130, hitpoints = 350, ranged = 0, magic = 0), hitpoints = 500)),
    )
}
