package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Nezikchened {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 329, spawn = NpcSpawnDef(npcId = 934, x = 3324, y = 3335, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 154, ranged = 0, magic = 0), hitpoints = 154)),
    )
}
