package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Npc2692 {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 551, spawn = NpcSpawnDef(npcId = 2692, x = 2748, y = 3471, z = 0, face = 0, hitpoints = 3)),
        SpawnEntry(index = 643, spawn = NpcSpawnDef(npcId = 2692, x = 2746, y = 3472, z = 0, face = 0, hitpoints = 3)),
        SpawnEntry(index = 654, spawn = NpcSpawnDef(npcId = 2692, x = 2750, y = 3475, z = 0, face = 0, hitpoints = 3)),
        SpawnEntry(index = 655, spawn = NpcSpawnDef(npcId = 2692, x = 2745, y = 3475, z = 0, face = 0, hitpoints = 3)),
        SpawnEntry(index = 656, spawn = NpcSpawnDef(npcId = 2692, x = 2748, y = 3476, z = 0, face = 0, hitpoints = 3)),
        SpawnEntry(index = 657, spawn = NpcSpawnDef(npcId = 2692, x = 2749, y = 3473, z = 0, face = 0, hitpoints = 3)),
        SpawnEntry(index = 658, spawn = NpcSpawnDef(npcId = 2692, x = 2747, y = 3474, z = 0, face = 0, hitpoints = 3)),
    )
}
