package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Npc4965 {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 892, spawn = NpcSpawnDef(npcId = 4965, x = 2447, y = 3431, z = 1, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
