package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Npc6990 {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 731, spawn = NpcSpawnDef(npcId = 6990, x = 3091, y = 3496, z = 0, face = 4, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
