package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Npc795 {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1062, spawn = NpcSpawnDef(npcId = 795, x = 3241, y = 2779, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 90, strength = 130, hitpoints = 110, ranged = 100, magic = 0), hitpoints = 110)),
    )
}
