package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Npc800 {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1063, spawn = NpcSpawnDef(npcId = 800, x = 3241, y = 2775, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 50, defence = 60, strength = 70, hitpoints = 70, ranged = 70, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 1246, spawn = NpcSpawnDef(npcId = 800, x = 3322, y = 2823, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 50, defence = 60, strength = 70, hitpoints = 70, ranged = 70, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 1247, spawn = NpcSpawnDef(npcId = 800, x = 3326, y = 2827, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 50, defence = 60, strength = 70, hitpoints = 70, ranged = 70, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 1248, spawn = NpcSpawnDef(npcId = 800, x = 3328, y = 2824, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 50, defence = 60, strength = 70, hitpoints = 70, ranged = 70, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 1249, spawn = NpcSpawnDef(npcId = 800, x = 3326, y = 2821, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 50, defence = 60, strength = 70, hitpoints = 70, ranged = 70, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 1250, spawn = NpcSpawnDef(npcId = 800, x = 3321, y = 2828, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 50, defence = 60, strength = 70, hitpoints = 70, ranged = 70, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 1251, spawn = NpcSpawnDef(npcId = 800, x = 3319, y = 2825, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 50, defence = 60, strength = 70, hitpoints = 70, ranged = 70, magic = 0), hitpoints = 70)),
        SpawnEntry(index = 1252, spawn = NpcSpawnDef(npcId = 800, x = 3317, y = 2828, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 50, defence = 60, strength = 70, hitpoints = 70, ranged = 70, magic = 0), hitpoints = 70)),
    )
}
