package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Npc801 {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1064, spawn = NpcSpawnDef(npcId = 801, x = 3237, y = 2775, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 60, strength = 80, hitpoints = 62, ranged = 145, magic = 300), hitpoints = 62)),
        SpawnEntry(index = 1253, spawn = NpcSpawnDef(npcId = 801, x = 3310, y = 2831, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 60, strength = 80, hitpoints = 62, ranged = 145, magic = 300), hitpoints = 62)),
        SpawnEntry(index = 1254, spawn = NpcSpawnDef(npcId = 801, x = 3308, y = 2829, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 60, strength = 80, hitpoints = 62, ranged = 145, magic = 300), hitpoints = 62)),
        SpawnEntry(index = 1255, spawn = NpcSpawnDef(npcId = 801, x = 3313, y = 2834, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 60, strength = 80, hitpoints = 62, ranged = 145, magic = 300), hitpoints = 62)),
        SpawnEntry(index = 1256, spawn = NpcSpawnDef(npcId = 801, x = 3315, y = 2831, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 60, strength = 80, hitpoints = 62, ranged = 145, magic = 300), hitpoints = 62)),
        SpawnEntry(index = 1257, spawn = NpcSpawnDef(npcId = 801, x = 3312, y = 2828, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 60, strength = 80, hitpoints = 62, ranged = 145, magic = 300), hitpoints = 62)),
        SpawnEntry(index = 1258, spawn = NpcSpawnDef(npcId = 801, x = 3308, y = 2834, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 60, strength = 80, hitpoints = 62, ranged = 145, magic = 300), hitpoints = 62)),
        SpawnEntry(index = 1259, spawn = NpcSpawnDef(npcId = 801, x = 3311, y = 2837, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 1, defence = 60, strength = 80, hitpoints = 62, ranged = 145, magic = 300), hitpoints = 62)),
    )
}
