package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Npc956 {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1085, spawn = NpcSpawnDef(npcId = 956, x = 3377, y = 2904, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1086, spawn = NpcSpawnDef(npcId = 956, x = 3375, y = 2909, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1087, spawn = NpcSpawnDef(npcId = 956, x = 3379, y = 2908, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1088, spawn = NpcSpawnDef(npcId = 956, x = 3375, y = 2902, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1089, spawn = NpcSpawnDef(npcId = 956, x = 3377, y = 2900, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1090, spawn = NpcSpawnDef(npcId = 956, x = 3374, y = 2898, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1091, spawn = NpcSpawnDef(npcId = 956, x = 3372, y = 2897, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1092, spawn = NpcSpawnDef(npcId = 956, x = 3370, y = 2902, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1093, spawn = NpcSpawnDef(npcId = 956, x = 3370, y = 2905, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1094, spawn = NpcSpawnDef(npcId = 956, x = 3371, y = 2909, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1095, spawn = NpcSpawnDef(npcId = 956, x = 3373, y = 2912, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
