package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Npc955 {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1298, spawn = NpcSpawnDef(npcId = 955, x = 3224, y = 3108, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 35)),
        SpawnEntry(index = 1299, spawn = NpcSpawnDef(npcId = 955, x = 3226, y = 3111, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 35)),
        SpawnEntry(index = 1300, spawn = NpcSpawnDef(npcId = 955, x = 3230, y = 3110, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 35)),
        SpawnEntry(index = 1301, spawn = NpcSpawnDef(npcId = 955, x = 3231, y = 3108, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 35)),
        SpawnEntry(index = 1302, spawn = NpcSpawnDef(npcId = 955, x = 3230, y = 3105, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 35)),
        SpawnEntry(index = 1303, spawn = NpcSpawnDef(npcId = 955, x = 3228, y = 3103, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 35)),
        SpawnEntry(index = 1304, spawn = NpcSpawnDef(npcId = 955, x = 3224, y = 3103, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 35)),
        SpawnEntry(index = 1305, spawn = NpcSpawnDef(npcId = 955, x = 3221, y = 3106, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 35)),
        SpawnEntry(index = 1306, spawn = NpcSpawnDef(npcId = 955, x = 3221, y = 3111, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 35)),
        SpawnEntry(index = 1307, spawn = NpcSpawnDef(npcId = 955, x = 3224, y = 3115, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 20, defence = 20, strength = 25, hitpoints = 35, ranged = 0, magic = 0), hitpoints = 35)),
    )
}
