package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Officer {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 695, spawn = NpcSpawnDef(npcId = 3648, x = 2810, y = 3422, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 0, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 762, spawn = NpcSpawnDef(npcId = 3648, x = 2772, y = 3235, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 0, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
