package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object OgreShaman {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 728, spawn = NpcSpawnDef(npcId = 4382, x = 2580, y = 9459, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 729, spawn = NpcSpawnDef(npcId = 4382, x = 2577, y = 9463, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 730, spawn = NpcSpawnDef(npcId = 4382, x = 2581, y = 9465, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 731, spawn = NpcSpawnDef(npcId = 4382, x = 2585, y = 9462, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 732, spawn = NpcSpawnDef(npcId = 4382, x = 2589, y = 9464, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 733, spawn = NpcSpawnDef(npcId = 4382, x = 2608, y = 9461, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 734, spawn = NpcSpawnDef(npcId = 4382, x = 2611, y = 9456, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 735, spawn = NpcSpawnDef(npcId = 4382, x = 2616, y = 9455, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 736, spawn = NpcSpawnDef(npcId = 4382, x = 2610, y = 9452, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 737, spawn = NpcSpawnDef(npcId = 4382, x = 2605, y = 9456, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
