package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object OgreShaman {
    // Stats: 4382: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 4382, x = 2580, y = 9459, z = 0, face = 0),
        NpcSpawnDef(npcId = 4382, x = 2577, y = 9463, z = 0, face = 0),
        NpcSpawnDef(npcId = 4382, x = 2581, y = 9465, z = 0, face = 0),
        NpcSpawnDef(npcId = 4382, x = 2585, y = 9462, z = 0, face = 0),
        NpcSpawnDef(npcId = 4382, x = 2589, y = 9464, z = 0, face = 0),
        NpcSpawnDef(npcId = 4382, x = 2608, y = 9461, z = 0, face = 0),
        NpcSpawnDef(npcId = 4382, x = 2611, y = 9456, z = 0, face = 0),
        NpcSpawnDef(npcId = 4382, x = 2616, y = 9455, z = 0, face = 0),
        NpcSpawnDef(npcId = 4382, x = 2610, y = 9452, z = 0, face = 0),
        NpcSpawnDef(npcId = 4382, x = 2605, y = 9456, z = 0, face = 0),
    )
}
