package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object OgreTrader {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 684, spawn = NpcSpawnDef(npcId = 4401, x = 2614, y = 9421, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
