package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object OgreChieftain {
    // Stats: 4362: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 4362, x = 2579, y = 9429, z = 0, face = 0),
        NpcSpawnDef(npcId = 4362, x = 2583, y = 9433, z = 0, face = 0),
        NpcSpawnDef(npcId = 4362, x = 2584, y = 9439, z = 0, face = 0),
        NpcSpawnDef(npcId = 4362, x = 2580, y = 9436, z = 0, face = 0),
        NpcSpawnDef(npcId = 4362, x = 2575, y = 9432, z = 0, face = 0),
        NpcSpawnDef(npcId = 4362, x = 2571, y = 9429, z = 0, face = 0),
        NpcSpawnDef(npcId = 4362, x = 2572, y = 9435, z = 0, face = 0),
        NpcSpawnDef(npcId = 4362, x = 2577, y = 9438, z = 0, face = 0),
        NpcSpawnDef(npcId = 4362, x = 2580, y = 9442, z = 0, face = 0),
    )
}
