package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object PiratePete {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 319, spawn = NpcSpawnDef(npcId = 2825, x = 2605, y = 3399, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 0, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
