package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object PollnivneachBandit {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1046, spawn = NpcSpawnDef(npcId = 736, x = 3362, y = 2990, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1048, spawn = NpcSpawnDef(npcId = 736, x = 3360, y = 2987, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1049, spawn = NpcSpawnDef(npcId = 736, x = 3356, y = 2988, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1152, spawn = NpcSpawnDef(npcId = 736, x = 3361, y = 2995, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1153, spawn = NpcSpawnDef(npcId = 736, x = 3365, y = 2996, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1154, spawn = NpcSpawnDef(npcId = 736, x = 3369, y = 2996, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1155, spawn = NpcSpawnDef(npcId = 736, x = 3371, y = 2994, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1156, spawn = NpcSpawnDef(npcId = 736, x = 3369, y = 2988, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1157, spawn = NpcSpawnDef(npcId = 736, x = 3364, y = 2988, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1158, spawn = NpcSpawnDef(npcId = 736, x = 3364, y = 2982, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1159, spawn = NpcSpawnDef(npcId = 736, x = 3367, y = 2979, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1160, spawn = NpcSpawnDef(npcId = 736, x = 3363, y = 2977, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1161, spawn = NpcSpawnDef(npcId = 736, x = 3359, y = 2975, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1162, spawn = NpcSpawnDef(npcId = 736, x = 3356, y = 2978, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1163, spawn = NpcSpawnDef(npcId = 736, x = 3354, y = 2975, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 35, defence = 35, strength = 35, hitpoints = 42, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
