package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object PollnivneachBanditBoss {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1164, spawn = NpcSpawnDef(npcId = 738, x = 3365, y = 2992, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 155, attack = 75, defence = 75, strength = 110, hitpoints = 122, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
