package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object PremiumStore {
    // Stats: 556: unknown

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 556, x = 3205, y = 3417, z = 0, face = 0),
    )
}
