package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object PremiumStore {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 188, spawn = NpcSpawnDef(npcId = 556, x = 3205, y = 3417, z = 0, face = 0)),
    )
}
