package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client

internal object PremiumStore {
    // Stats: 556: unknown

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 556, x = 3205, y = 3417, z = 0, face = 0),
    )

    @Suppress("UNUSED_PARAMETER")
    fun onFirstClick(client: Client, npc: Npc): Boolean {
        client.WanneShop = 31
        return true
    }
}
