package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Pyrefiend {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 112, spawn = NpcSpawnDef(npcId = 433, x = 2518, y = 3285, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 113, spawn = NpcSpawnDef(npcId = 433, x = 2522, y = 3281, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 114, spawn = NpcSpawnDef(npcId = 433, x = 2520, y = 3275, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 115, spawn = NpcSpawnDef(npcId = 433, x = 2532, y = 3274, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 116, spawn = NpcSpawnDef(npcId = 433, x = 2521, y = 3272, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 117, spawn = NpcSpawnDef(npcId = 433, x = 2518, y = 3293, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 118, spawn = NpcSpawnDef(npcId = 433, x = 2521, y = 3290, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 119, spawn = NpcSpawnDef(npcId = 433, x = 2514, y = 3286, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 120, spawn = NpcSpawnDef(npcId = 433, x = 2528, y = 3278, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 121, spawn = NpcSpawnDef(npcId = 433, x = 2530, y = 3281, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 122, spawn = NpcSpawnDef(npcId = 433, x = 2538, y = 3278, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 123, spawn = NpcSpawnDef(npcId = 433, x = 2545, y = 3281, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 124, spawn = NpcSpawnDef(npcId = 433, x = 2544, y = 3278, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 125, spawn = NpcSpawnDef(npcId = 433, x = 2537, y = 3282, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 126, spawn = NpcSpawnDef(npcId = 433, x = 2535, y = 3287, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
        SpawnEntry(index = 277, spawn = NpcSpawnDef(npcId = 433, x = 2524, y = 3293, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 12, strength = 15, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 63)),
    )
}
