package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Pyrefiend {
    // Stats: 433: r=60 a=25 d=12 s=15 hp=45 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 433, x = 2518, y = 3285, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2522, y = 3281, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2520, y = 3275, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2532, y = 3274, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2521, y = 3272, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2518, y = 3293, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2521, y = 3290, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2514, y = 3286, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2528, y = 3278, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2530, y = 3281, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2538, y = 3278, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2545, y = 3281, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2544, y = 3278, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2537, y = 3282, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2535, y = 3287, z = 0, face = 0),
        NpcSpawnDef(npcId = 433, x = 2524, y = 3293, z = 0, face = 0),
    )
}
