package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Queen {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 164, spawn = NpcSpawnDef(npcId = 4922, x = 2865, y = 9953, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 180, attack = 95, defence = 115, strength = 135, hitpoints = 285, ranged = 0, magic = 1200), hitpoints = 250)),
        SpawnEntry(index = 341, spawn = NpcSpawnDef(npcId = 4303, x = 3483, y = 9492, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 250, attack = 180, defence = 250, strength = 290, hitpoints = 900, ranged = 240, magic = 0), hitpoints = 0)),
    )
}
