package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ranger {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 443, spawn = NpcSpawnDef(npcId = 6365, x = 3331, y = 3335, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 1, ranged = 0, magic = 0), hitpoints = 1)),
        SpawnEntry(index = 444, spawn = NpcSpawnDef(npcId = 6366, x = 3332, y = 3333, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 1, ranged = 0, magic = 0), hitpoints = 1)),
    )
}
