package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object RedDragon {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 151, spawn = NpcSpawnDef(npcId = 247, x = 3243, y = 9357, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 130, defence = 130, strength = 140, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 245)),
        SpawnEntry(index = 152, spawn = NpcSpawnDef(npcId = 247, x = 3243, y = 9367, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 130, defence = 130, strength = 140, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 245)),
        SpawnEntry(index = 537, spawn = NpcSpawnDef(npcId = 247, x = 3221, y = 9375, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 130, defence = 130, strength = 140, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 245)),
        SpawnEntry(index = 538, spawn = NpcSpawnDef(npcId = 247, x = 3219, y = 9379, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 130, defence = 130, strength = 140, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 245)),
        SpawnEntry(index = 539, spawn = NpcSpawnDef(npcId = 247, x = 3222, y = 9384, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 130, defence = 130, strength = 140, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 245)),
        SpawnEntry(index = 540, spawn = NpcSpawnDef(npcId = 247, x = 3228, y = 9392, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 130, defence = 130, strength = 140, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 245)),
        SpawnEntry(index = 541, spawn = NpcSpawnDef(npcId = 247, x = 3223, y = 9393, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 130, defence = 130, strength = 140, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 245)),
        SpawnEntry(index = 542, spawn = NpcSpawnDef(npcId = 247, x = 3223, y = 9398, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 130, defence = 130, strength = 140, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 245)),
        SpawnEntry(index = 543, spawn = NpcSpawnDef(npcId = 247, x = 3231, y = 9397, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 40, attack = 130, defence = 130, strength = 140, hitpoints = 150, ranged = 0, magic = 0), hitpoints = 245)),
    )
}
