package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object RedDragon {
    // Stats: 247: r=40 a=130 d=130 s=140 hp=150 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 247, x = 3243, y = 9357, z = 0, face = 0),
        NpcSpawnDef(npcId = 247, x = 3243, y = 9367, z = 0, face = 0),
        NpcSpawnDef(npcId = 247, x = 3221, y = 9375, z = 0, face = 0),
        NpcSpawnDef(npcId = 247, x = 3219, y = 9379, z = 0, face = 0),
        NpcSpawnDef(npcId = 247, x = 3222, y = 9384, z = 0, face = 0),
        NpcSpawnDef(npcId = 247, x = 3228, y = 9392, z = 0, face = 0),
        NpcSpawnDef(npcId = 247, x = 3223, y = 9393, z = 0, face = 0),
        NpcSpawnDef(npcId = 247, x = 3223, y = 9398, z = 0, face = 0),
        NpcSpawnDef(npcId = 247, x = 3231, y = 9397, z = 0, face = 0),
    )
}
