package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object RockCrab {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 21, spawn = NpcSpawnDef(npcId = 100, x = 2794, y = 3210, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 22, spawn = NpcSpawnDef(npcId = 100, x = 2798, y = 3209, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 24, spawn = NpcSpawnDef(npcId = 100, x = 2796, y = 3212, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 25, spawn = NpcSpawnDef(npcId = 100, x = 2783, y = 3218, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 26, spawn = NpcSpawnDef(npcId = 100, x = 2785, y = 3215, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 27, spawn = NpcSpawnDef(npcId = 100, x = 2789, y = 3213, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 28, spawn = NpcSpawnDef(npcId = 100, x = 2793, y = 3213, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 342, spawn = NpcSpawnDef(npcId = 100, x = 2791, y = 3210, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 736, spawn = NpcSpawnDef(npcId = 100, x = 2780, y = 3219, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 741, spawn = NpcSpawnDef(npcId = 100, x = 2788, y = 3209, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 742, spawn = NpcSpawnDef(npcId = 100, x = 2785, y = 3210, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 743, spawn = NpcSpawnDef(npcId = 100, x = 2784, y = 3212, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 744, spawn = NpcSpawnDef(npcId = 100, x = 2781, y = 3213, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
        SpawnEntry(index = 745, spawn = NpcSpawnDef(npcId = 100, x = 2780, y = 3216, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 40, ranged = 1, magic = 1), hitpoints = 5)),
    )
}
