package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client
import net.dodian.uber.game.content.dialogue.DialogueEmote
import net.dodian.uber.game.content.dialogue.DialogueOption
import net.dodian.uber.game.content.dialogue.DialogueService
import net.dodian.uber.game.model.player.skills.agility.DesertCarpet

internal object RugMerchant {
    // Stats: 17: r=60 a=0 d=0 s=0 hp=18 rg=0 mg=0; 22: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 20: r=10 a=0 d=0 s=0 hp=99 rg=0 mg=0; 19: r=60 a=0 d=0 s=0 hp=52 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 17, x = 3287, y = 2814, z = 0, face = 0),
        NpcSpawnDef(npcId = 22, x = 3401, y = 2918, z = 0, face = 0),
        NpcSpawnDef(npcId = 20, x = 3348, y = 3002, z = 0, face = 0),
        NpcSpawnDef(npcId = 19, x = 3181, y = 3045, z = 0, face = 0),
    )

    val npcIds: IntArray = entries.map { it.npcId }.distinct().toIntArray()

    fun onFirstClick(client: Client, npc: Npc): Boolean {
        DialogueService.start(client) {
            npcChat(npc.id, DialogueEmote.NEARLY_CRYING, "Hello there Traveler.", "Do you fancy taking a carpet ride?", "It will cost 5000 coins.")
            options(
                title = "Where can your carpet take me to?",
                DialogueOption("Show destinations") {
                    val destinations = when (npc.id) {
                        17 -> arrayOf("Pollnivneach", "Nardah", "Bedabin Camp")
                        19 -> arrayOf("Pollnivneach", "Nardah", "Sophanem")
                        20 -> arrayOf("Nardah", "Bedabin Camp", "Sophanem")
                        22 -> arrayOf("Pollnivneach", "Sophanem", "Bedabin Camp")
                        else -> arrayOf("Cancel", "Cancel", "Cancel")
                    }
                    options(
                        title = "Carpet rides cost 5k coins.",
                        DialogueOption(destinations[0]) {
                            action { c -> travel(c, npc.id, 0) }
                            finish()
                        },
                        DialogueOption(destinations[1]) {
                            action { c -> travel(c, npc.id, 1) }
                            finish()
                        },
                        DialogueOption(destinations[2]) {
                            action { c -> travel(c, npc.id, 2) }
                            finish()
                        },
                        DialogueOption("Cancel") { finish() },
                    )
                },
                DialogueOption("No, thank you.") {
                    playerChat(DialogueEmote.ANGRY1, "No, thank you.")
                    finish()
                },
            )
        }
        return true
    }

    private fun travel(client: Client, npcId: Int, choice: Int) {
        var missing = 5000
        val amount = client.getInvAmt(995).toLong() + client.getBankAmt(995)
        if (amount >= 5000L) {
            if (client.getInvAmt(995) >= missing) {
                client.deleteItem(995, missing)
            } else {
                missing -= client.getInvAmt(995)
                client.deleteItem(995, client.getInvAmt(995))
            }
            if (missing > 0) {
                client.deleteItemBank(995, missing)
            }
            client.checkItemUpdate()
        } else {
            client.showNPCChat(npcId, 594, arrayOf("You do not have enough coins to do this!", "You are currently missing ${missing - amount} coins."))
            return
        }

        val carpet = DesertCarpet(client)
        when (npcId) {
            17 -> carpet.sophanem(choice)
            19 -> carpet.bedabinCamp(choice)
            20 -> carpet.pollnivneach(choice)
            22 -> carpet.nardah(choice)
        }
    }
}
