package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Salesman {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 36, spawn = NpcSpawnDef(npcId = 6059, x = 2725, y = 3369, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 500, spawn = NpcSpawnDef(npcId = 6060, x = 2589, y = 3083, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
