package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object SandSnakeHard {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 708, spawn = NpcSpawnDef(npcId = 7894, x = 2445, y = 9892, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 709, spawn = NpcSpawnDef(npcId = 7894, x = 2442, y = 9881, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 724, spawn = NpcSpawnDef(npcId = 7894, x = 2391, y = 9877, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
