package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object SandCrab {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 951, spawn = NpcSpawnDef(npcId = 5935, x = 2789, y = 3222, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 952, spawn = NpcSpawnDef(npcId = 5935, x = 3142, y = 2972, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 953, spawn = NpcSpawnDef(npcId = 5935, x = 3145, y = 2969, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 954, spawn = NpcSpawnDef(npcId = 5935, x = 3146, y = 2974, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 955, spawn = NpcSpawnDef(npcId = 5935, x = 3149, y = 2976, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 956, spawn = NpcSpawnDef(npcId = 5935, x = 3149, y = 2982, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 957, spawn = NpcSpawnDef(npcId = 5935, x = 3146, y = 2984, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 958, spawn = NpcSpawnDef(npcId = 5935, x = 3145, y = 2988, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 959, spawn = NpcSpawnDef(npcId = 5935, x = 3144, y = 2992, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 960, spawn = NpcSpawnDef(npcId = 5935, x = 3148, y = 2989, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 961, spawn = NpcSpawnDef(npcId = 5935, x = 3149, y = 2986, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 962, spawn = NpcSpawnDef(npcId = 5935, x = 3151, y = 2980, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 963, spawn = NpcSpawnDef(npcId = 5935, x = 3151, y = 2973, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 964, spawn = NpcSpawnDef(npcId = 5935, x = 3149, y = 2969, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 965, spawn = NpcSpawnDef(npcId = 5935, x = 3147, y = 2971, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 966, spawn = NpcSpawnDef(npcId = 5935, x = 3142, y = 2968, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
        SpawnEntry(index = 967, spawn = NpcSpawnDef(npcId = 5935, x = 3139, y = 2969, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 1, defence = 1, strength = 1, hitpoints = 45, ranged = 1, magic = 1), hitpoints = 0)),
    )
}
