package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ScarabMage {
    // Stats: 799: r=30 a=35 d=35 s=55 hp=58 rg=0 mg=1350; 794: r=60 a=55 d=55 s=85 hp=90 rg=0 mg=1700

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 799, x = 3311, y = 2824, z = 0, face = 0),
        NpcSpawnDef(npcId = 799, x = 3310, y = 2821, z = 0, face = 0),
        NpcSpawnDef(npcId = 794, x = 3246, y = 2779, z = 0, face = 0),
        NpcSpawnDef(npcId = 799, x = 3246, y = 2775, z = 0, face = 0),
        NpcSpawnDef(npcId = 799, x = 3314, y = 2823, z = 0, face = 0),
        NpcSpawnDef(npcId = 799, x = 3316, y = 2821, z = 0, face = 0),
        NpcSpawnDef(npcId = 799, x = 3313, y = 2819, z = 0, face = 0),
        NpcSpawnDef(npcId = 799, x = 3310, y = 2818, z = 0, face = 0),
        NpcSpawnDef(npcId = 799, x = 3307, y = 2821, z = 0, face = 0),
        NpcSpawnDef(npcId = 799, x = 3308, y = 2824, z = 0, face = 0),
    )
}
