package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ShadowWarrior {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 158, spawn = NpcSpawnDef(npcId = 2853, x = 2719, y = 9754, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 159, spawn = NpcSpawnDef(npcId = 2853, x = 2723, y = 9750, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 222, spawn = NpcSpawnDef(npcId = 2853, x = 2725, y = 9755, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 234, spawn = NpcSpawnDef(npcId = 2853, x = 2714, y = 9749, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
    )
}
