package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ShopKeeper {
    // Stats: 506: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 555: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 506, x = 2595, y = 3104, z = 0, face = 0),
        NpcSpawnDef(npcId = 506, x = 3216, y = 3416, z = 0, face = 0),
        NpcSpawnDef(npcId = 555, x = 2604, y = 3092, z = 0, face = 0),
    )
}
