package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Skeleton {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 353, spawn = NpcSpawnDef(npcId = 90, x = 3203, y = 9881, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 29, ranged = 0, magic = 0), hitpoints = 29)),
    )
}
