package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Snail {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 194, spawn = NpcSpawnDef(npcId = 1227, x = 2964, y = 9636, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 195, spawn = NpcSpawnDef(npcId = 1227, x = 2962, y = 9633, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 196, spawn = NpcSpawnDef(npcId = 1227, x = 2960, y = 9632, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 197, spawn = NpcSpawnDef(npcId = 1227, x = 2963, y = 9632, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 198, spawn = NpcSpawnDef(npcId = 1227, x = 2963, y = 9635, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 8, ranged = 0, magic = 0), hitpoints = 8)),
        SpawnEntry(index = 199, spawn = NpcSpawnDef(npcId = 1228, x = 2962, y = 9633, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 200, spawn = NpcSpawnDef(npcId = 1228, x = 2962, y = 9635, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 10, ranged = 0, magic = 0), hitpoints = 10)),
        SpawnEntry(index = 201, spawn = NpcSpawnDef(npcId = 1229, x = 2988, y = 9640, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 20)),
        SpawnEntry(index = 202, spawn = NpcSpawnDef(npcId = 1229, x = 2984, y = 9639, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 20)),
        SpawnEntry(index = 203, spawn = NpcSpawnDef(npcId = 1229, x = 2985, y = 9633, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 20)),
        SpawnEntry(index = 204, spawn = NpcSpawnDef(npcId = 1229, x = 2985, y = 9635, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 20)),
        SpawnEntry(index = 205, spawn = NpcSpawnDef(npcId = 1229, x = 2985, y = 9632, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 20, ranged = 0, magic = 0), hitpoints = 20)),
        SpawnEntry(index = 206, spawn = NpcSpawnDef(npcId = 1230, x = 2989, y = 9634, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 13, ranged = 0, magic = 0), hitpoints = 13)),
        SpawnEntry(index = 207, spawn = NpcSpawnDef(npcId = 1230, x = 2988, y = 9637, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 13, ranged = 0, magic = 0), hitpoints = 13)),
        SpawnEntry(index = 208, spawn = NpcSpawnDef(npcId = 1230, x = 2987, y = 9640, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 13, ranged = 0, magic = 0), hitpoints = 13)),
        SpawnEntry(index = 209, spawn = NpcSpawnDef(npcId = 1230, x = 2985, y = 9638, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 13, ranged = 0, magic = 0), hitpoints = 13)),
    )
}
