package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal data class SpawnEntry(
    val index: Int,
    val spawn: NpcSpawnDef,
)
