package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Spectre {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 654, spawn = NpcSpawnDef(npcId = 2, x = 2648, y = 9861, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 655, spawn = NpcSpawnDef(npcId = 2, x = 2645, y = 9861, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 656, spawn = NpcSpawnDef(npcId = 2, x = 2646, y = 9864, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 657, spawn = NpcSpawnDef(npcId = 2, x = 2648, y = 9865, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 658, spawn = NpcSpawnDef(npcId = 2, x = 2643, y = 9866, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
        SpawnEntry(index = 659, spawn = NpcSpawnDef(npcId = 2, x = 2640, y = 9864, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 120)),
        SpawnEntry(index = 660, spawn = NpcSpawnDef(npcId = 2, x = 2642, y = 9862, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 45, attack = 80, defence = 80, strength = 80, hitpoints = 120, ranged = 0, magic = 0), hitpoints = 90)),
    )
}
