package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Spider {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 368, spawn = NpcSpawnDef(npcId = 59, x = 3220, y = 9888, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 369, spawn = NpcSpawnDef(npcId = 59, x = 3217, y = 9890, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 370, spawn = NpcSpawnDef(npcId = 59, x = 3211, y = 9894, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 371, spawn = NpcSpawnDef(npcId = 59, x = 3212, y = 9886, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 2, ranged = 0, magic = 0), hitpoints = 2)),
        SpawnEntry(index = 372, spawn = NpcSpawnDef(npcId = 63, x = 3213, y = 9890, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 373, spawn = NpcSpawnDef(npcId = 63, x = 3210, y = 9897, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
    )
}
