package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Spirit {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 85, spawn = NpcSpawnDef(npcId = 5565, x = 2578, y = 9811, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 299, spawn = NpcSpawnDef(npcId = 5565, x = 2665, y = 9806, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 301, spawn = NpcSpawnDef(npcId = 5565, x = 2659, y = 9806, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 302, spawn = NpcSpawnDef(npcId = 5565, x = 2666, y = 9810, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 190)),
        SpawnEntry(index = 306, spawn = NpcSpawnDef(npcId = 5565, x = 2659, y = 9811, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 307, spawn = NpcSpawnDef(npcId = 5565, x = 2662, y = 9809, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 190)),
        SpawnEntry(index = 308, spawn = NpcSpawnDef(npcId = 5565, x = 2655, y = 9807, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 150)),
        SpawnEntry(index = 330, spawn = NpcSpawnDef(npcId = 5565, x = 2664, y = 9796, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 190)),
        SpawnEntry(index = 331, spawn = NpcSpawnDef(npcId = 5565, x = 2660, y = 9795, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 190)),
        SpawnEntry(index = 332, spawn = NpcSpawnDef(npcId = 5565, x = 2659, y = 9798, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 190)),
        SpawnEntry(index = 609, spawn = NpcSpawnDef(npcId = 5565, x = 2663, y = 9799, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 35, attack = 100, defence = 100, strength = 90, hitpoints = 190, ranged = 0, magic = 0), hitpoints = 190)),
    )
}
