package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Terrorbird {
    // Stats: 136: r=60 a=0 d=0 s=0 hp=34 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 136, x = 2463, y = 3044, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2461, y = 3049, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2469, y = 3050, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2469, y = 3045, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2466, y = 3053, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2480, y = 3046, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2486, y = 3048, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2607, y = 9432, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2605, y = 9436, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2604, y = 9441, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2609, y = 9440, z = 0, face = 0),
        NpcSpawnDef(npcId = 136, x = 2613, y = 9438, z = 0, face = 0),
    )
}
