package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ThrowerTroll {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 971, spawn = NpcSpawnDef(npcId = 1103, x = 3229, y = 3108, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 96, ranged = 0, magic = 0), hitpoints = 96)),
        SpawnEntry(index = 1319, spawn = NpcSpawnDef(npcId = 1105, x = 3589, y = 3477, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 96, ranged = 0, magic = 0), hitpoints = 96)),
    )
}
