package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Tojalon {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 58, spawn = NpcSpawnDef(npcId = 3964, x = 2614, y = 9522, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 180, attack = 130, defence = 150, strength = 120, hitpoints = 295, ranged = 0, magic = 0), hitpoints = 400)),
    )
}
