package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object TokXil {
    // Stats: 2193: r=60 a=70 d=60 s=100 hp=110 rg=140 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2193, x = 2392, y = 5098, z = 0, face = 0),
        NpcSpawnDef(npcId = 2193, x = 2400, y = 5099, z = 0, face = 0),
        NpcSpawnDef(npcId = 2193, x = 2406, y = 5103, z = 0, face = 0),
        NpcSpawnDef(npcId = 2193, x = 2411, y = 5096, z = 0, face = 0),
        NpcSpawnDef(npcId = 2193, x = 2385, y = 5099, z = 0, face = 0),
        NpcSpawnDef(npcId = 2193, x = 2390, y = 5095, z = 0, face = 0),
        NpcSpawnDef(npcId = 2193, x = 2407, y = 5090, z = 0, face = 0),
        NpcSpawnDef(npcId = 2193, x = 2395, y = 5094, z = 0, face = 0),
        NpcSpawnDef(npcId = 2193, x = 2401, y = 5094, z = 0, face = 0),
        NpcSpawnDef(npcId = 2193, x = 2386, y = 5092, z = 0, face = 0),
    )
}
