package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Troll {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 187, spawn = NpcSpawnDef(npcId = 395, x = 3174, y = 3028, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 130, ranged = 0, magic = 0), hitpoints = 130)),
        SpawnEntry(index = 970, spawn = NpcSpawnDef(npcId = 1107, x = 3375, y = 2906, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 91, ranged = 0, magic = 0), hitpoints = 91)),
        SpawnEntry(index = 971, spawn = NpcSpawnDef(npcId = 1103, x = 3229, y = 3108, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 96, ranged = 0, magic = 0), hitpoints = 96)),
        SpawnEntry(index = 1319, spawn = NpcSpawnDef(npcId = 1105, x = 3589, y = 3477, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 96, ranged = 0, magic = 0), hitpoints = 96)),
    )
}
