package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object TzhaarMej {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 635, spawn = NpcSpawnDef(npcId = 2154, x = 2480, y = 5167, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
        SpawnEntry(index = 636, spawn = NpcSpawnDef(npcId = 2154, x = 2475, y = 5166, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
        SpawnEntry(index = 637, spawn = NpcSpawnDef(npcId = 2154, x = 2470, y = 5164, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
        SpawnEntry(index = 638, spawn = NpcSpawnDef(npcId = 2154, x = 2464, y = 5163, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
        SpawnEntry(index = 639, spawn = NpcSpawnDef(npcId = 2154, x = 2461, y = 5157, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
        SpawnEntry(index = 918, spawn = NpcSpawnDef(npcId = 2154, x = 2457, y = 5160, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
        SpawnEntry(index = 919, spawn = NpcSpawnDef(npcId = 2154, x = 2455, y = 5154, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
        SpawnEntry(index = 920, spawn = NpcSpawnDef(npcId = 2154, x = 2451, y = 5151, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
        SpawnEntry(index = 921, spawn = NpcSpawnDef(npcId = 2154, x = 2452, y = 5163, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
        SpawnEntry(index = 922, spawn = NpcSpawnDef(npcId = 2154, x = 2466, y = 5168, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
        SpawnEntry(index = 923, spawn = NpcSpawnDef(npcId = 2154, x = 2470, y = 5169, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 50, defence = 85, strength = 60, hitpoints = 115, ranged = 0, magic = 1500), hitpoints = 115)),
    )
}
