package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client
import net.dodian.uber.game.content.dialogue.DialogueEmote
import net.dodian.uber.game.content.dialogue.DialogueOption
import net.dodian.uber.game.content.dialogue.DialogueService

internal object TzhaarMejJal {
    // Stats: 2180: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2180, x = 2849, y = 2991, z = 0, face = 0),
    )

    val npcIds: IntArray = npcIdsFromEntries(entries)

    fun onFirstClick(client: Client, npc: Npc): Boolean {
        DialogueService.start(client) {
            if (client.checkUnlock(1)) {
                npcChat(npc.id, DialogueEmote.DEFAULT, "You can enter freely, no need to pay me anything.")
                finish()
            } else {
                npcChat(npc.id, DialogueEmote.DEFAULT, "Hello!", "Are you looking to enter my cave?", "You have to pay to enter.", "You can also pay a one time fee.")
                options(
                    title = "Select an option",
                    DialogueOption("Enter fee") {
                        options(
                            title = "Select a payment option",
                            DialogueOption("Ship ticket") {
                                action { c ->
                                    if (c.checkUnlockPaid(1) > 0) {
                                        c.showNPCChat(npc.id, 591, arrayOf("You have already paid me.", "Please step into my cave."))
                                    } else if (c.getInvAmt(621) > 0 || c.getBankAmt(621) > 0) {
                                        c.addUnlocks(1, "1", if (c.checkUnlock(1)) "1" else "0")
                                        if (c.getInvAmt(621) > 0) c.deleteItem(621, 1) else c.deleteItemBank(621, 1)
                                        c.checkItemUpdate()
                                        c.showNPCChat(npc.id, 591, arrayOf("You can now step into the cave."))
                                    } else {
                                        c.showNPCChat(npc.id, 596, arrayOf("You need a ship ticket to enter my cave!"))
                                    }
                                }
                                finish()
                            },
                            DialogueOption("Coins") {
                                action { c ->
                                    val amount = c.getInvAmt(995).toLong() + c.getBankAmt(995)
                                    val total = 300_000
                                    if (amount >= total) {
                                        c.addUnlocks(1, "1", if (c.checkUnlock(1)) "1" else "0")
                                        val remain = total - c.getInvAmt(995)
                                        c.deleteItem(995, total)
                                        if (remain > 0) c.deleteItemBank(995, remain)
                                        c.showNPCChat(npc.id, 591, arrayOf("You can now step into the cave."))
                                    } else {
                                        c.showNPCChat(npc.id, 596, arrayOf("You need at least ${total - amount} more coins to enter my cave!"))
                                    }
                                }
                                finish()
                            },
                        )
                    },
                    DialogueOption("Permanent unlock") {
                        action { c ->
                            if (!c.checkUnlock(1)) {
                                val maximumTickets = 20
                                val minimumTicket = 3
                                val ticketValue = 300_000
                                var missing = (maximumTickets - minimumTicket) * ticketValue
                                if (!c.playerHasItem(621, minimumTicket)) {
                                    c.showNPCChat(npc.id, 591, arrayOf("You need a minimum of $minimumTicket ship ticket", "to unlock permanent!"))
                                } else {
                                    missing -= (c.getInvAmt(621) - minimumTicket) * ticketValue
                                    if (missing > 0) {
                                        if (c.getInvAmt(995) >= missing) {
                                            c.deleteItem(621, kotlin.math.min(c.getInvAmt(621), maximumTickets))
                                            c.deleteItem(995, missing)
                                            c.addUnlocks(1, c.checkUnlockPaid(1).toString(), "1")
                                            c.showNPCChat(npc.id, 591, arrayOf("Thank you for the payment.", "You may enter freely into my cave."))
                                        } else {
                                            c.showNPCChat(npc.id, 591, arrayOf("You do not have enough coins to do this!"))
                                        }
                                    } else {
                                        c.deleteItem(621, maximumTickets)
                                        c.addUnlocks(1, c.checkUnlockPaid(1).toString(), "1")
                                        c.showNPCChat(npc.id, 591, arrayOf("Thank you for the ship tickets.", "You may enter freely into my cave."))
                                    }
                                    c.checkItemUpdate()
                                }
                            }
                        }
                        finish()
                    },
                    DialogueOption("Nevermind") {
                        playerChat(DialogueEmote.DEFAULT, "I do not want anything.")
                        finish()
                    },
                )
            }
        }
        return true
    }

    fun onSecondClick(client: Client, npc: Npc): Boolean {
        return onFirstClick(client, npc)
    }
}
