package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Vampire {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 663, spawn = NpcSpawnDef(npcId = 1220, x = 1839, y = 4533, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 56, ranged = 0, magic = 0), hitpoints = 56)),
        SpawnEntry(index = 664, spawn = NpcSpawnDef(npcId = 1223, x = 1839, y = 4534, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 45, ranged = 0, magic = 0), hitpoints = 45)),
    )
}
