package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Vampyre {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1000, spawn = NpcSpawnDef(npcId = 3137, x = 3549, y = 3505, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1001, spawn = NpcSpawnDef(npcId = 3137, x = 3553, y = 3506, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1002, spawn = NpcSpawnDef(npcId = 3137, x = 3556, y = 3503, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1003, spawn = NpcSpawnDef(npcId = 3137, x = 3556, y = 3500, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1004, spawn = NpcSpawnDef(npcId = 3137, x = 3553, y = 3498, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1005, spawn = NpcSpawnDef(npcId = 3137, x = 3550, y = 3495, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1006, spawn = NpcSpawnDef(npcId = 3137, x = 3548, y = 3500, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1007, spawn = NpcSpawnDef(npcId = 3137, x = 3546, y = 3496, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1008, spawn = NpcSpawnDef(npcId = 3137, x = 3544, y = 3499, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1009, spawn = NpcSpawnDef(npcId = 3137, x = 3545, y = 3503, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 1010, spawn = NpcSpawnDef(npcId = 3137, x = 3552, y = 3501, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 60, defence = 45, strength = 78, hitpoints = 85, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
