package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client

internal object Vannaka {
    // Stats: 403: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 403, x = 2798, y = 3441, z = 0, face = 0),
    )

    val npcIds: IntArray = npcIdsFromEntries(entries)

    fun onFirstClick(client: Client, npc: Npc): Boolean {
        SlayerMasterDialogue.startIntro(client, npc.id)
        return true
    }

    fun onSecondClick(client: Client, npc: Npc): Boolean {
        SlayerMasterDialogue.assignTask(client, npc.id)
        return true
    }

    @Suppress("UNUSED_PARAMETER")
    fun onThirdClick(client: Client, npc: Npc): Boolean {
        client.WanneShop = 15
        return true
    }
}
