package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client
import net.dodian.uber.game.content.dialogue.DialogueEmote
import net.dodian.uber.game.content.dialogue.DialogueOption
import net.dodian.uber.game.content.dialogue.DialogueService
import net.dodian.uber.game.content.npcs.dialogue.NpcDialogueService

internal object Vannaka {
    // Stats: 403: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 403, x = 2798, y = 3441, z = 0, face = 0),
    )

    val npcIds: IntArray = entries.map { it.npcId }.distinct().toIntArray()

    fun onFirstClick(client: Client, npc: Npc): Boolean {
        DialogueService.start(client) {
            npcChat(npc.id, DialogueEmote.DEFAULT, "Need help with your slayer assignment?")
            options(
                title = "Select an option",
                DialogueOption("Yes please.") {
                    action { c ->
                        c.NpcDialogue = 11
                        c.NpcDialogueSend = false
                        c.nextDiag = -1
                        NpcDialogueService.updateNpcChat(c)
                    }
                    finish(closeInterfaces = false)
                },
                DialogueOption("No thanks.") { finish() },
            )
        }
        return true
    }
}
