package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Vulture {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1052, spawn = NpcSpawnDef(npcId = 1267, x = 3272, y = 2969, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
        SpawnEntry(index = 1058, spawn = NpcSpawnDef(npcId = 1267, x = 3266, y = 2969, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
        SpawnEntry(index = 1182, spawn = NpcSpawnDef(npcId = 1267, x = 3271, y = 2973, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
        SpawnEntry(index = 1183, spawn = NpcSpawnDef(npcId = 1267, x = 3268, y = 2965, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
        SpawnEntry(index = 1184, spawn = NpcSpawnDef(npcId = 1267, x = 3273, y = 2964, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
        SpawnEntry(index = 1185, spawn = NpcSpawnDef(npcId = 1267, x = 3277, y = 2967, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
        SpawnEntry(index = 1186, spawn = NpcSpawnDef(npcId = 1267, x = 3279, y = 2971, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
        SpawnEntry(index = 1187, spawn = NpcSpawnDef(npcId = 1267, x = 3276, y = 2974, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
        SpawnEntry(index = 1188, spawn = NpcSpawnDef(npcId = 1267, x = 3264, y = 2974, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
        SpawnEntry(index = 1189, spawn = NpcSpawnDef(npcId = 1267, x = 3262, y = 2969, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
        SpawnEntry(index = 1190, spawn = NpcSpawnDef(npcId = 1267, x = 3265, y = 2964, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 25, defence = 25, strength = 25, hitpoints = 30, ranged = 1, magic = 1), hitpoints = 50)),
    )
}
