package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Warrior {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 158, spawn = NpcSpawnDef(npcId = 2853, x = 2719, y = 9754, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 159, spawn = NpcSpawnDef(npcId = 2853, x = 2723, y = 9750, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 212, spawn = NpcSpawnDef(npcId = 2851, x = 2855, y = 3510, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 213, spawn = NpcSpawnDef(npcId = 2851, x = 2851, y = 3509, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 214, spawn = NpcSpawnDef(npcId = 2851, x = 2842, y = 3504, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 215, spawn = NpcSpawnDef(npcId = 2851, x = 2839, y = 3502, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 216, spawn = NpcSpawnDef(npcId = 2851, x = 2837, y = 3506, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 217, spawn = NpcSpawnDef(npcId = 2851, x = 2835, y = 3508, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 218, spawn = NpcSpawnDef(npcId = 2851, x = 2832, y = 3512, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 222, spawn = NpcSpawnDef(npcId = 2853, x = 2725, y = 9755, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 224, spawn = NpcSpawnDef(npcId = 2890, x = 2581, y = 3106, z = 0, face = 5, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 234, spawn = NpcSpawnDef(npcId = 2853, x = 2714, y = 9749, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 615, spawn = NpcSpawnDef(npcId = 2851, x = 2698, y = 9837, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 616, spawn = NpcSpawnDef(npcId = 2851, x = 2695, y = 9836, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 617, spawn = NpcSpawnDef(npcId = 2851, x = 2700, y = 9841, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 618, spawn = NpcSpawnDef(npcId = 2851, x = 2706, y = 9842, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 619, spawn = NpcSpawnDef(npcId = 2851, x = 2711, y = 9844, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 620, spawn = NpcSpawnDef(npcId = 2851, x = 2709, y = 9841, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 886, spawn = NpcSpawnDef(npcId = 2890, x = 2581, y = 3100, z = 0, face = 4, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 24)),
        SpawnEntry(index = 887, spawn = NpcSpawnDef(npcId = 2890, x = 2579, y = 3101, z = 0, face = 4, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 24)),
        SpawnEntry(index = 890, spawn = NpcSpawnDef(npcId = 2890, x = 2579, y = 3104, z = 0, face = 6, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 891, spawn = NpcSpawnDef(npcId = 2890, x = 2578, y = 3106, z = 0, face = 3, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 904, spawn = NpcSpawnDef(npcId = 2890, x = 2581, y = 3103, z = 0, face = 3, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 0)),
        SpawnEntry(index = 936, spawn = NpcSpawnDef(npcId = 2890, x = 2577, y = 3103, z = 0, face = 2, preset = NpcDataPreset(respawnTicks = 30, attack = 18, defence = 22, strength = 32, hitpoints = 24, ranged = 0, magic = 0), hitpoints = 24)),
    )
}
