package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Warrior {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 164, spawn = NpcSpawnDef(npcId = 2853, x = 2719, y = 9754, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 165, spawn = NpcSpawnDef(npcId = 2853, x = 2723, y = 9750, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 218, spawn = NpcSpawnDef(npcId = 2851, x = 2855, y = 3510, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 219, spawn = NpcSpawnDef(npcId = 2851, x = 2851, y = 3509, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 220, spawn = NpcSpawnDef(npcId = 2851, x = 2842, y = 3504, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 221, spawn = NpcSpawnDef(npcId = 2851, x = 2839, y = 3502, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 222, spawn = NpcSpawnDef(npcId = 2851, x = 2837, y = 3506, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 223, spawn = NpcSpawnDef(npcId = 2851, x = 2835, y = 3508, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 224, spawn = NpcSpawnDef(npcId = 2851, x = 2832, y = 3512, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 228, spawn = NpcSpawnDef(npcId = 2853, x = 2725, y = 9755, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 240, spawn = NpcSpawnDef(npcId = 2853, x = 2714, y = 9749, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 45, defence = 55, strength = 50, hitpoints = 65, ranged = 60, magic = 60), hitpoints = 60)),
        SpawnEntry(index = 393, spawn = NpcSpawnDef(npcId = 6363, x = 3328, y = 3335, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 1, ranged = 0, magic = 0), hitpoints = 1)),
        SpawnEntry(index = 394, spawn = NpcSpawnDef(npcId = 6364, x = 3330, y = 3333, z = 4, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 1, ranged = 0, magic = 0), hitpoints = 1)),
        SpawnEntry(index = 644, spawn = NpcSpawnDef(npcId = 2851, x = 2698, y = 9837, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 645, spawn = NpcSpawnDef(npcId = 2851, x = 2695, y = 9836, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 646, spawn = NpcSpawnDef(npcId = 2851, x = 2700, y = 9841, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 647, spawn = NpcSpawnDef(npcId = 2851, x = 2706, y = 9842, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 648, spawn = NpcSpawnDef(npcId = 2851, x = 2711, y = 9844, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
        SpawnEntry(index = 649, spawn = NpcSpawnDef(npcId = 2851, x = 2709, y = 9841, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 60, ranged = 0, magic = 0), hitpoints = 60)),
    )
}
