package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Watchman {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 42, spawn = NpcSpawnDef(npcId = 3251, x = 2584, y = 3102, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 43, spawn = NpcSpawnDef(npcId = 3251, x = 2579, y = 3105, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 44, spawn = NpcSpawnDef(npcId = 3251, x = 2582, y = 3101, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 45, spawn = NpcSpawnDef(npcId = 3251, x = 2585, y = 3105, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 46, spawn = NpcSpawnDef(npcId = 3251, x = 2582, y = 3105, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 48, spawn = NpcSpawnDef(npcId = 3251, x = 2580, y = 3102, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 466, spawn = NpcSpawnDef(npcId = 3251, x = 3242, y = 9894, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 28)),
        SpawnEntry(index = 467, spawn = NpcSpawnDef(npcId = 3251, x = 3244, y = 9894, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 28)),
    )
}
