package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object WhateverFuck {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 719, spawn = NpcSpawnDef(npcId = 56, x = 3229, y = 3214, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 1, attack = 0, defence = 0, strength = 0, hitpoints = 1, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
