package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Wolfman {
    // Stats: 1032: r=60 a=0 d=0 s=0 hp=100 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1032, x = 2805, y = 3427, z = 0, face = 0),
    )
}
