package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Wolfman {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 917, spawn = NpcSpawnDef(npcId = 1032, x = 2805, y = 3427, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 0, defence = 0, strength = 0, hitpoints = 100, ranged = 0, magic = 0), hitpoints = 100)),
    )
}
