package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Worker {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 380, spawn = NpcSpawnDef(npcId = 1153, x = 3489, y = 9510, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 386, spawn = NpcSpawnDef(npcId = 1153, x = 3494, y = 9509, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 387, spawn = NpcSpawnDef(npcId = 1153, x = 3498, y = 9511, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 388, spawn = NpcSpawnDef(npcId = 1153, x = 3498, y = 9517, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 389, spawn = NpcSpawnDef(npcId = 1153, x = 3503, y = 9518, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 390, spawn = NpcSpawnDef(npcId = 1153, x = 3508, y = 9519, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 391, spawn = NpcSpawnDef(npcId = 1153, x = 3509, y = 9524, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 392, spawn = NpcSpawnDef(npcId = 1153, x = 3505, y = 9526, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 393, spawn = NpcSpawnDef(npcId = 1153, x = 3501, y = 9523, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 394, spawn = NpcSpawnDef(npcId = 1153, x = 3496, y = 9525, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 395, spawn = NpcSpawnDef(npcId = 1153, x = 3490, y = 9524, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
        SpawnEntry(index = 396, spawn = NpcSpawnDef(npcId = 1153, x = 3486, y = 9526, z = 2, face = 0, preset = NpcDataPreset(respawnTicks = 30, attack = 15, defence = 10, strength = 15, hitpoints = 22, ranged = 0, magic = 0), hitpoints = 22)),
    )
}
