package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client
import net.dodian.uber.game.model.player.skills.Skill
import net.dodian.uber.game.model.player.skills.Skills
import net.dodian.uber.game.netty.listener.out.SendMessage
import java.util.Objects

internal object Wydin {
    // Stats: 557: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 557, x = 3256, y = 2780, z = 0, face = 0),
    )

    fun onFirstClick(client: Client, npc: Npc): Boolean {
        npc.requestAnim(5643, 0)
        for (skill in listOf(0, 1, 2, 4)) {
            val skillType = Objects.requireNonNull(Skill.getSkill(skill))
            val maxLevel = Skills.getLevelForExperience(client.getExperience(skillType))
            client.boost(5 + (maxLevel * 0.15).toInt(), skillType)
        }
        val ticks = (1 + Skills.getLevelForExperience(client.getExperience(Skill.HERBLORE))) * 2
        client.addEffectTime(2, 200 + ticks)
        client.send(SendMessage("The monk boost your stats!"))
        return true
    }
}
