package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Xil {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 476, spawn = NpcSpawnDef(npcId = 2193, x = 2392, y = 5098, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 60, strength = 100, hitpoints = 110, ranged = 140, magic = 0), hitpoints = 110)),
        SpawnEntry(index = 477, spawn = NpcSpawnDef(npcId = 2193, x = 2400, y = 5099, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 60, strength = 100, hitpoints = 110, ranged = 140, magic = 0), hitpoints = 110)),
        SpawnEntry(index = 478, spawn = NpcSpawnDef(npcId = 2193, x = 2406, y = 5103, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 60, strength = 100, hitpoints = 110, ranged = 140, magic = 0), hitpoints = 110)),
        SpawnEntry(index = 482, spawn = NpcSpawnDef(npcId = 2193, x = 2411, y = 5096, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 60, strength = 100, hitpoints = 110, ranged = 140, magic = 0), hitpoints = 110)),
        SpawnEntry(index = 483, spawn = NpcSpawnDef(npcId = 2193, x = 2385, y = 5099, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 60, strength = 100, hitpoints = 110, ranged = 140, magic = 0), hitpoints = 110)),
        SpawnEntry(index = 485, spawn = NpcSpawnDef(npcId = 2193, x = 2390, y = 5095, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 60, strength = 100, hitpoints = 110, ranged = 140, magic = 0), hitpoints = 110)),
        SpawnEntry(index = 488, spawn = NpcSpawnDef(npcId = 2193, x = 2407, y = 5090, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 60, strength = 100, hitpoints = 110, ranged = 140, magic = 0), hitpoints = 110)),
        SpawnEntry(index = 600, spawn = NpcSpawnDef(npcId = 2193, x = 2395, y = 5094, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 60, strength = 100, hitpoints = 110, ranged = 140, magic = 0), hitpoints = 110)),
        SpawnEntry(index = 710, spawn = NpcSpawnDef(npcId = 2193, x = 2401, y = 5094, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 60, strength = 100, hitpoints = 110, ranged = 140, magic = 0), hitpoints = 110)),
        SpawnEntry(index = 712, spawn = NpcSpawnDef(npcId = 2193, x = 2386, y = 5092, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 70, defence = 60, strength = 100, hitpoints = 110, ranged = 140, magic = 0), hitpoints = 110)),
        SpawnEntry(index = 924, spawn = NpcSpawnDef(npcId = 2167, x = 2453, y = 5146, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 925, spawn = NpcSpawnDef(npcId = 2167, x = 2449, y = 5146, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 926, spawn = NpcSpawnDef(npcId = 2167, x = 2445, y = 5144, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 927, spawn = NpcSpawnDef(npcId = 2167, x = 2441, y = 5146, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 928, spawn = NpcSpawnDef(npcId = 2167, x = 2440, y = 5142, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 929, spawn = NpcSpawnDef(npcId = 2167, x = 2445, y = 5139, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 930, spawn = NpcSpawnDef(npcId = 2167, x = 2441, y = 5135, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 931, spawn = NpcSpawnDef(npcId = 2167, x = 2451, y = 5140, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 932, spawn = NpcSpawnDef(npcId = 2167, x = 2456, y = 5143, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 933, spawn = NpcSpawnDef(npcId = 2167, x = 2459, y = 5137, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 934, spawn = NpcSpawnDef(npcId = 2167, x = 2461, y = 5142, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
        SpawnEntry(index = 935, spawn = NpcSpawnDef(npcId = 2167, x = 2454, y = 5134, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 60, attack = 130, defence = 100, strength = 100, hitpoints = 135, ranged = 0, magic = 0), hitpoints = 135)),
    )
}
