package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Yaga {
    val entries: List<SpawnEntry> = listOf(
        SpawnEntry(index = 1026, spawn = NpcSpawnDef(npcId = 3837, x = 2461, y = 3428, z = 0, face = 0, preset = NpcDataPreset(respawnTicks = 0, attack = 0, defence = 0, strength = 0, hitpoints = 0, ranged = 0, magic = 0), hitpoints = 0)),
    )
}
