package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Zogre {
    // Stats: 867: r=60 a=0 d=0 s=0 hp=50 rg=0 mg=0; 2053: r=60 a=0 d=0 s=0 hp=72 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 867, x = 2470, y = 9443, z = 0, face = 0),
        NpcSpawnDef(npcId = 867, x = 2468, y = 9446, z = 0, face = 0),
        NpcSpawnDef(npcId = 867, x = 2467, y = 9442, z = 0, face = 0),
        NpcSpawnDef(npcId = 867, x = 2473, y = 9439, z = 0, face = 0),
        NpcSpawnDef(npcId = 867, x = 2465, y = 9444, z = 0, face = 0),
        NpcSpawnDef(npcId = 867, x = 2475, y = 9445, z = 0, face = 0),
        NpcSpawnDef(npcId = 867, x = 2476, y = 9441, z = 0, face = 0),
        NpcSpawnDef(npcId = 867, x = 2467, y = 9438, z = 0, face = 0),
        NpcSpawnDef(npcId = 2053, x = 2652, y = 3294, z = 0, face = 0),
    )
}
