package net.dodian.uber.game.content.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Zombie {
    // Stats: 75: r=60 a=0 d=0 s=0 hp=30 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 75, x = 3249, y = 9900, z = 0, face = 0),
        NpcSpawnDef(npcId = 75, x = 3250, y = 9906, z = 0, face = 0),
        NpcSpawnDef(npcId = 75, x = 3256, y = 9907, z = 0, face = 0),
        NpcSpawnDef(npcId = 75, x = 3252, y = 9903, z = 0, face = 0),
        NpcSpawnDef(npcId = 75, x = 3251, y = 9897, z = 0, face = 0),
        NpcSpawnDef(npcId = 75, x = 3255, y = 9893, z = 0, face = 0),
        NpcSpawnDef(npcId = 75, x = 3266, y = 9893, z = 0, face = 0),
    )
}
