package net.dodian.uber.game.content.npcs.unknown

import net.dodian.uber.game.npc.*

import net.dodian.uber.game.npc.NpcSpawnDef
import net.dodian.uber.game.npc.npcIdsFromEntries

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object UnknownNpc3089 : NpcModule {
    // Stats: 3089: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 3089, x = 2605, y = 3111, z = 0, face = 0),
    )


    override val definition = simpleNpcDefinition(
        name = "UnknownNpc3089",
        entries = entries,
    )
}
