package net.dodian.uber.game.content.npcs

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client
import net.dodian.uber.game.content.objects.travel.LegendsGuildGateService

internal object LegendsGuard : NpcModule {
    // Stats: 3951: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 3951, x = 2727, y = 3349, z = 0, face = SOUTH),
        NpcSpawnDef(npcId = 3951, x = 2730, y = 3349, z = 0, face = SOUTH),
    )
    val npcIds: IntArray = npcIdsFromEntries(entries)


    override val definition = legacyNpcDefinition(
        name = "LegendsGuard",
        entries = entries,
        onFirstClick = ::onFirstClick,
    )

    @Suppress("UNUSED_PARAMETER")
    fun onFirstClick(client: Client, npc: Npc): Boolean {
        if (client.premium) {
            LegendsGuildGateService.allowPassage(client)
            client.showNPCChat(npc.id, 590, arrayOf("Welcome to the Guild of Legends", "Enjoy your stay."))
        } else {
            client.showNPCChat(npc.id, 595, arrayOf("You must be a premium member to enter", "Visit Dodian.net to subscribe"))
        }
        return true
    }
}
