package net.dodian.uber.game.content.npcs

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object MountainTroll : NpcModule {
    // Stats: 1107: r=60 a=0 d=0 s=0 hp=91 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 1107, x = 3375, y = 2906, z = 0, face = 0),
    )


    override val definition = simpleNpcDefinition(
        name = "MountainTroll",
        entries = entries,
    )
}
