package net.dodian.uber.game.runtime.action

enum class PlayerActionCancelReason {
    NEW_ACTION,
    MOVEMENT,
    OBJECT_INTERACTION,
    NPC_INTERACTION,
    PLAYER_INTERACTION,
    GROUND_ITEM_INTERACTION,
    ITEM_INTERACTION,
    DIALOGUE_OPENED,
    INTERFACE_CLOSED,
    LOGOUT,
    DISCONNECTED,
    DEATH,
    TELEPORT,
    COMBAT_INTERRUPTED,
    MANUAL_RESET,
}
