#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DEF = ROOT / "scripts" / "npc_Def.json"
DEFAULT_SPAWN = ROOT / "scripts" / "npc_Spawn.json"
DEFAULT_OUT = ROOT / "src" / "main" / "kotlin" / "net" / "dodian" / "uber" / "game" / "content" / "npcs" / "generated"
PKG = "net.dodian.uber.game.content.npcs.generated"


@dataclass(frozen=True)
class NpcDef:
    npc_id: int
    name: str


@dataclass(frozen=True)
class Spawn:
    npc_id: int
    x: int
    y: int
    z: int
    face: int
    rx: int
    ry: int
    rx2: int
    ry2: int
    move_chance: int
    live: bool
    hitpoints: int


def sanitize_name(raw: str, fallback_id: int | None = None) -> str:
    base = (raw or "").strip()
    if not base:
        base = f"UnknownNpc{fallback_id or 0}"
    base = re.sub(r"[^A-Za-z0-9]+", "_", base)
    parts = [p for p in base.split("_") if p]
    if not parts:
        parts = ["UnknownNpc", str(fallback_id or 0)]
    camel = "".join(p[:1].upper() + p[1:] for p in parts)
    if camel and camel[0].isdigit():
        camel = f"Npc{camel}"
    return camel


def parse_defs(path: Path) -> dict[int, NpcDef]:
    rows = json.loads(path.read_text())
    defs: dict[int, NpcDef] = {}
    for row in rows:
        npc_id = int(row.get("id", 0))
        if npc_id <= 0:
            continue
        name = str(row.get("name") or "").strip()
        defs[npc_id] = NpcDef(npc_id=npc_id, name=name)
    return defs


def parse_spawns(path: Path) -> list[Spawn]:
    rows = json.loads(path.read_text())
    out: list[Spawn] = []
    for row in rows:
        npc_id = int(row.get("id", 0))
        if npc_id <= 0:
            continue
        out.append(
            Spawn(
                npc_id=npc_id,
                x=int(row.get("x", 0)),
                y=int(row.get("y", 0)),
                z=int(row.get("height", 0)),
                face=int(row.get("face", 0)),
                rx=int(row.get("rx", 0)),
                ry=int(row.get("ry", 0)),
                rx2=int(row.get("rx2", 0)),
                ry2=int(row.get("ry2", 0)),
                move_chance=int(row.get("movechance", 0)),
                live=int(row.get("live", 1)) == 1,
                hitpoints=int(row.get("hitpoints", 0)),
            )
        )
    return out


def group_spawns(defs: dict[int, NpcDef], spawns: Iterable[Spawn]) -> dict[str, list[Spawn]]:
    grouped: dict[str, list[Spawn]] = defaultdict(list)
    for spawn in sorted(spawns, key=lambda s: (s.npc_id, s.x, s.y, s.z, s.face)):
        npc_def = defs.get(spawn.npc_id)
        class_name = sanitize_name(npc_def.name if npc_def else "", spawn.npc_id)
        grouped[class_name].append(spawn)
    return dict(sorted(grouped.items(), key=lambda kv: kv[0]))


def render_module(class_name: str, spawns: list[Spawn]) -> str:
    ids = sorted({s.npc_id for s in spawns})
    stats = "; ".join(f"{npc_id}: hp={max((s.hitpoints for s in spawns if s.npc_id == npc_id), default=0)}" for npc_id in ids)
    entry_lines = []
    for s in spawns:
        entry_lines.append(
            "        NpcSpawnDef("
            f"npcId = {s.npc_id}, x = {s.x}, y = {s.y}, z = {s.z}, face = {s.face}, "
            f"rx = {s.rx}, ry = {s.ry}, rx2 = {s.rx2}, ry2 = {s.ry2}, moveChance = {s.move_chance}, live = {str(s.live).lower()}"
            "),"
        )

    return "\n".join(
        [
            f"package {PKG}",
            "",
            "import net.dodian.uber.game.content.npcs.*",
            "",
            "// AUTO-GENERATED by game-server/scripts/generate_npc_modules.py",
            f"internal object {class_name} : NpcModule {{",
            f"    // Stats: {stats}",
            "",
            "    val entries: List<NpcSpawnDef> = listOf(",
            *entry_lines,
            "    )",
            "    val npcIds: IntArray = npcIdsFromEntries(entries)",
            "",
            "    override val definition = simpleNpcDefinition(",
            f"        name = \"{class_name}\",",
            "        npcIds = npcIds,",
            "        entries = entries,",
            "    )",
            "}",
            "",
        ]
    )


def render_index(class_names: list[str]) -> str:
    lines = [
        f"package {PKG}",
        "",
        "import net.dodian.uber.game.content.npcs.NpcModule",
        "",
        "// AUTO-GENERATED by game-server/scripts/generate_npc_modules.py",
        "internal object GeneratedNpcModules {",
        "    val modules: List<NpcModule> = listOf(",
    ]
    for i, name in enumerate(class_names):
        suffix = "," if i < len(class_names) - 1 else ""
        lines.append(f"        {name}{suffix}")
    lines.extend(["    )", "}", ""])
    return "\n".join(lines)


def write_modules(out_dir: Path, grouped: dict[str, list[Spawn]], select_name: str | None, select_id: int | None) -> list[str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    emitted: list[str] = []
    for class_name, rows in grouped.items():
        if select_name and class_name.lower() != sanitize_name(select_name).lower():
            continue
        if select_id is not None and all(s.npc_id != select_id for s in rows):
            continue
        module_path = out_dir / f"{class_name}.kt"
        module_path.write_text(render_module(class_name, rows))
        emitted.append(class_name)

    emitted.sort()
    if not select_name and select_id is None:
        (out_dir / "GeneratedNpcModules.kt").write_text(render_index(emitted))
    return emitted


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate typed Kotlin NPC modules from npc_Def.json + npc_Spawn.json")
    parser.add_argument("--defs", type=Path, default=DEFAULT_DEF)
    parser.add_argument("--spawns", type=Path, default=DEFAULT_SPAWN)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--npc-id", type=int, default=None)
    parser.add_argument("--name", type=str, default=None)
    args = parser.parse_args()

    defs = parse_defs(args.defs)
    spawns = parse_spawns(args.spawns)
    grouped = group_spawns(defs, spawns)
    emitted = write_modules(args.out, grouped, args.name, args.npc_id)

    if args.name or args.npc_id is not None:
        target = args.name if args.name else str(args.npc_id)
        print(f"Generated {len(emitted)} module(s) for selector={target}")
    else:
        print(f"Generated {len(emitted)} module(s) into {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
