package net.dodian.uber.game.plugin

import net.dodian.uber.game.content.items.ItemContent
import net.dodian.uber.game.content.npcs.spawns.NpcModuleDefinitionBuilder
import net.dodian.uber.game.content.npcs.spawns.NpcContentDefinition
import net.dodian.uber.game.content.objects.ObjectContent
import net.dodian.uber.game.systems.ui.buttons.InterfaceButtonContent

object GeneratedPluginModuleIndex {
    @JvmField
    val interfaceButtons: List<InterfaceButtonContent> = listOf(
        net.dodian.uber.game.content.interfaces.appearance.AppearanceInterfaceButtons,
        net.dodian.uber.game.content.interfaces.bank.BankInterfaceButtons,
        net.dodian.uber.game.content.interfaces.combat.CombatInterfaceButtons,
        net.dodian.uber.game.content.interfaces.crafting.CraftingInterfaceButtons,
        net.dodian.uber.game.content.interfaces.dialogue.DialogueInterfaceButtons,
        net.dodian.uber.game.content.interfaces.duel.DuelInterfaceButtons,
        net.dodian.uber.game.content.interfaces.emotes.EmoteInterfaceButtons,
        net.dodian.uber.game.content.interfaces.fletching.FletchingInterfaceButtons,
        net.dodian.uber.game.content.interfaces.magic.MagicInterfaceButtons,
        net.dodian.uber.game.content.interfaces.partyroom.PartyRoomInterfaceButtons,
        net.dodian.uber.game.content.interfaces.prayer.PrayerInterfaceButtons,
        net.dodian.uber.game.content.interfaces.quests.QuestInterfaceButtons,
        net.dodian.uber.game.content.interfaces.rewards.RewardInterfaceButtons,
        net.dodian.uber.game.content.interfaces.settings.SettingsInterfaceButtons,
        net.dodian.uber.game.content.interfaces.skillguide.SkillGuideInterfaceButtons,
        net.dodian.uber.game.content.interfaces.slots.SlotsInterfaceButtons,
        net.dodian.uber.game.content.interfaces.smithing.SmithingInterfaceButtons,
        net.dodian.uber.game.content.interfaces.trade.TradeInterfaceButtons,
        net.dodian.uber.game.content.interfaces.travel.TravelInterfaceButtons,
        net.dodian.uber.game.content.interfaces.ui.UiInterfaceButtons
    )

    @JvmField
    val objectContents: List<Pair<String, ObjectContent>> = listOf(
        "BarbarianCourseObjectBindings" to net.dodian.uber.game.content.skills.agility.objects.BarbarianCourseObjectBindings,
        "GnomeCourseObjectBindings" to net.dodian.uber.game.content.skills.agility.objects.GnomeCourseObjectBindings,
        "WerewolfCourseObjectBindings" to net.dodian.uber.game.content.skills.agility.objects.WerewolfCourseObjectBindings,
        "WildernessCourseObjectBindings" to net.dodian.uber.game.content.skills.agility.objects.WildernessCourseObjectBindings,
        "BankBoothObjects" to net.dodian.uber.game.content.objects.banking.BankBoothObjects,
        "BankChestObjects" to net.dodian.uber.game.content.objects.banking.BankChestObjects,
        "RangeObjects" to net.dodian.uber.game.content.skills.cooking.objects.RangeObjects,
        "ResourceFillingObjects" to net.dodian.uber.game.content.skills.crafting.objects.ResourceFillingObjects,
        "SpinningWheelObjects" to net.dodian.uber.game.content.skills.crafting.objects.SpinningWheelObjects,
        "DoorToggleObjects" to net.dodian.uber.game.content.objects.doors.DoorToggleObjects,
        "PartyRoomObjectBindings" to net.dodian.uber.game.content.objects.events.PartyRoomObjectBindings,
        "CompostBinObjects" to net.dodian.uber.game.content.skills.farming.objects.CompostBinObjects,
        "FarmingPatchGuideObjects" to net.dodian.uber.game.content.skills.farming.objects.FarmingPatchGuideObjects,
        "FarmingPatchObjects" to net.dodian.uber.game.content.skills.farming.objects.FarmingPatchObjects,
        "GemRocksObjectBindings" to net.dodian.uber.game.content.skills.mining.objects.GemRocksObjectBindings,
        "MiningRocksObjects" to net.dodian.uber.game.content.skills.mining.objects.MiningRocksObjects,
        "SpecialMiningObjectBindings" to net.dodian.uber.game.content.skills.mining.objects.SpecialMiningObjectBindings,
        "AltarObjects" to net.dodian.uber.game.content.skills.prayer.objects.AltarObjects,
        "RunecraftingObjectBindings" to net.dodian.uber.game.content.skills.runecrafting.objects.RunecraftingObjectBindings,
        "AnvilObjects" to net.dodian.uber.game.content.skills.smithing.objects.AnvilObjects,
        "FurnaceObjects" to net.dodian.uber.game.content.skills.smithing.objects.FurnaceObjects,
        "ChestObjects" to net.dodian.uber.game.content.skills.thieving.objects.ChestObjects,
        "PlunderObjects" to net.dodian.uber.game.content.skills.thieving.objects.PlunderObjects,
        "StallObjects" to net.dodian.uber.game.content.skills.thieving.objects.StallObjects,
        "LadderObjects" to net.dodian.uber.game.content.objects.travel.LadderObjects,
        "PassageObjects" to net.dodian.uber.game.content.objects.travel.PassageObjects,
        "StaircaseObjects" to net.dodian.uber.game.content.objects.travel.StaircaseObjects,
        "TeleportObjects" to net.dodian.uber.game.content.objects.travel.TeleportObjects,
        "VerticalTeleportObjects" to net.dodian.uber.game.content.objects.travel.VerticalTeleportObjects,
        "WebObstacleObjects" to net.dodian.uber.game.content.objects.travel.WebObstacleObjects,
        "WoodcuttingTreesObjects" to net.dodian.uber.game.content.skills.woodcutting.objects.WoodcuttingTreesObjects
    )

    @JvmField
    val itemContents: List<ItemContent> = listOf(
        net.dodian.uber.game.content.items.admin.StaffToolItems,
        net.dodian.uber.game.content.items.consumables.DrinkItems,
        net.dodian.uber.game.content.items.consumables.FoodItems,
        net.dodian.uber.game.content.items.consumables.PotionItems,
        net.dodian.uber.game.content.items.cosmetics.ToyItems,
        net.dodian.uber.game.content.items.equipment.RepairHintItems,
        net.dodian.uber.game.content.items.events.EventInfoItems,
        net.dodian.uber.game.content.items.events.EventPackageItems,
        net.dodian.uber.game.content.skills.herblore.items.GrimyHerbItems,
        net.dodian.uber.game.content.skills.herblore.items.HerbloreSuppliesItems,
        net.dodian.uber.game.content.skills.prayer.items.BuryBonesItems,
        net.dodian.uber.game.content.items.rewards.LampRewardItems,
        net.dodian.uber.game.content.skills.runecrafting.items.RunePouchItems,
        net.dodian.uber.game.content.skills.slayer.items.SlayerGemItems,
        net.dodian.uber.game.content.skills.slayer.items.SlayerMaskItems,
        net.dodian.uber.game.content.items.utility.GuideBookItems
    )

    @JvmField
    val npcContents: List<NpcContentDefinition> = listOf(
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.AberrantSpectre, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.AbyssalDemon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.AbyssalGuardian, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.AbyssalLeech, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.AgilityWerewolfMaster, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.AlbinoBat, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.AliHag, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.AncestralGlyph, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ArmourSalesman, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Aubury, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BabaYaga, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BabyKraken, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Bandit, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BanditBoss, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Banker, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Banshee, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BattleMage, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BeginnerStore, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BerserkBarbarianSpirit, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BigSnake, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BillyGoat, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BlackDemon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BlackDragon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BlackKnightTitan, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BloodBlamishSnail, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Bloodveld, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BlueDragon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BowArrowSalesman, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.BruiseBlamishSnail, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.CaptainRovin, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.CaptainTobias, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.CaveBugLarva, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.CaveHorror, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Chadwell, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ChaosDruid, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ChaosDruidWarrior, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ChaosDwarf, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Chicken, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Cow, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.CrawlingHand, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Crocodile, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.CustomsOfficer, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Dad, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Dagannoth, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.DagannothPrime, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.DeadlyRedSpider, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.DeathSpawn, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.DesertLizard, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.DesertWolf, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Diango, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.DoorMan, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Dori, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Druid, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.DukeHoracio, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Duradel, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Dwarf, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.DwarfGangMember, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Dwayne, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ElderWerewolf, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.EscapingSlave, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Farmer, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.FinalBoss, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.FireGiant, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.FishSpot, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Gargoyle, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Gerrant, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Ghost, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Ghoul, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.GiantRat, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.GiantSpider, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Glough, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.GnomeBaller, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.GnomeTrainer, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Goat, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.GreaterDemon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.GreenDragon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Guard, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.HeadMourner, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Hellhound, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Hero, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Highwayman, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.HillGiant, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Horvik, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Ian, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.IceGiant, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.IceQueen, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.IceWarrior, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.InfernalMage, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Jackal, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.JalTokJad, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Jatix, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Jelly, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.JungleDemon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.JungleHorror, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.KalphiteGuardian, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.KalphiteKing, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.KalphiteQueen, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.KalphiteSoldier, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.KalphiteWorker, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.KingBlackDragon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Knight, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.KnightArdougne, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Koftik, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Kolodion, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.LegendsGuard, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.LesserDemon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Lizard, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.LocustRiderMelee, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.LocustRiderRanged, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Mac, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Mahogany, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.MakeoverMage, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Man, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.MasterFarmer, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Mazchna, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.MenaphiteThug, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.MenaphiteThugBoss, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.MithrilDragon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Monk, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.MossGiant, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.MountainTroll, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.MountedTerrorbirdGnome, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Mummy, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.MyreBlamishSnail, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Nathifa, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Nechryael, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.OchreBlamishSnail, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.OgreChieftain, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.OgreShaman, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.OgreTrader, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PartyAnnouncer, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PartyPete, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PeeHat, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Peksa, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PiratePete, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PlaceHolderDrop, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PlaceholderNpc, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PlagueWarning, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PollnivneachBandit, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PollnivneachBanditBoss, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PopulationAnnouncer, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PostiePete, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.PremiumStore, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Pyrefiend, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.RedDragon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.RiverTroll, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.RockCrab, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Rufu, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.RugMerchant, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.SanTojalon, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.SandCrab, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.SandSnake, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.SandSnakeHard, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Saniboch, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ScarabMage, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Scorpion, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Sedridor, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ShadowWarrior, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Shantay, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Sheep, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ShopAssistant, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ShopKeeper, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.SigbertAdventurer, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Skeleton, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.SkeletonHellhound, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.SlashBash, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.SurvivalExpert, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.SwordMummy, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Tanner, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Terrorbird, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ThievingSkillcapeShop, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.ThrowerTroll, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.TokXil, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.TowerAdvisor, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Turael, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.TzhaarKet, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.TzhaarKetZuh, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.TzhaarMej, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.TzhaarMejJal, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.TzhaarXil, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.TztokJad, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Ungadulu, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc1597, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc2692, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc2745, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc3089, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc4637, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc4639, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc5961, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc6771, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc6777, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc683, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc6990, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.UnknownNpc8059, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Vampyre, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Vannaka, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Venenati, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Vulture, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Watcher, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Watchman, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.WatchtowerWizard, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Werewolf, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.WizardCromperty, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.WizardDistentor, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Wolf, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Wolfman, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Wydin, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.YtMejkot, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Zahra, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Zahur, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Zogre, explicitName = "", ownsSpawnDefinitions = false),
        NpcModuleDefinitionBuilder.fromModule(module = net.dodian.uber.game.content.npcs.spawns.Zombie, explicitName = "", ownsSpawnDefinitions = false)
    )

    @JvmField
    val eventBootstraps: List<() -> Unit> = listOf(
        { net.dodian.uber.game.event.bootstrap.EventBusProbeBootstrap.bootstrap() },
        { net.dodian.uber.game.event.bootstrap.PlayerLifecycleTickBootstrap.bootstrap() }
    )
}
