package net.dodian.uber.game.npc.unknown

import net.dodian.uber.game.npc.*

import net.dodian.uber.game.npc.NpcSpawnDef
import net.dodian.uber.game.npc.npcIdsFromEntries

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object UnknownNpc6771 : NpcModule {
    // Stats: 6771: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 6771, x = 3152, y = 2911, z = 0, face = 0),
    )


    override val definition = simpleNpcDefinition(
        name = "UnknownNpc6771",
        entries = entries,
    )
}
