package net.dodian.uber.game.npc.unknown

import net.dodian.uber.game.npc.*

import net.dodian.uber.game.npc.NpcSpawnDef
import net.dodian.uber.game.npc.npcIdsFromEntries

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object UnknownNpc5961 : NpcModule {
    // Stats: 5961: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 5961, x = 2908, y = 4388, z = 0, face = 0),
    )


    override val definition = simpleNpcDefinition(
        name = "UnknownNpc5961",
        entries = entries,
    )
}
