package net.dodian.uber.game.npc.unknown

import net.dodian.uber.game.npc.*

import net.dodian.uber.game.npc.NpcSpawnDef
import net.dodian.uber.game.npc.npcIdsFromEntries

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object UnknownNpc2692 : NpcModule {
    // Stats: 2692: unknown

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 2692, x = 2748, y = 3471, z = 0, face = 0),
        NpcSpawnDef(npcId = 2692, x = 2746, y = 3472, z = 0, face = 0),
        NpcSpawnDef(npcId = 2692, x = 2750, y = 3475, z = 0, face = 0),
        NpcSpawnDef(npcId = 2692, x = 2745, y = 3475, z = 0, face = 0),
        NpcSpawnDef(npcId = 2692, x = 2748, y = 3476, z = 0, face = 0),
        NpcSpawnDef(npcId = 2692, x = 2749, y = 3473, z = 0, face = 0),
        NpcSpawnDef(npcId = 2692, x = 2747, y = 3474, z = 0, face = 0),
    )


    override val definition = simpleNpcDefinition(
        name = "UnknownNpc2692",
        entries = entries,
    )
}
