package net.dodian.uber.game.content.npcs.store

import net.dodian.uber.game.npc.*

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.npc.NpcSpawnDef
import net.dodian.uber.game.npc.npcIdsFromEntries
import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client

internal object UnknownNpc556Shop : NpcModule {
    // Stats: 556: unknown

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 556, x = 3205, y = 3417, z = 0, face = 0),
    )
    val npcIds: IntArray = npcIdsFromEntries(entries)


    override val definition = legacyNpcDefinition(
        name = "UnknownNpc556Shop",
        entries = entries,
        onFirstClick = ::onFirstClick,
    )

    @Suppress("UNUSED_PARAMETER")
    fun onFirstClick(client: Client, npc: Npc): Boolean {
        client.WanneShop = 31
        return true
    }
}
