package net.dodian.uber.game.content.entities.npcs.spawns

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ShopKeeper {
    // Stats: 506: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 555: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val npcIds: IntArray = npcIds(520, 506)

    val entries: List<NpcSpawnDef> = listOf(
        NpcSpawnDef(npcId = 506, x = 2595, y = 3104, z = 0, face = 0),
        NpcSpawnDef(npcId = 506, x = 3216, y = 3416, z = 0, face = 0),
    )
    val definition =
        npcPlugin("ShopKeeper") {
            ids(*npcIds)
            spawns(entries)
            ownsSpawns(true)
            options {
                talkTo {
                    whenCondition(
                        predicate = { npc.id == 520 },
                        thenBlock = {
                            action {
                                custom { client, _ ->
                                    client.NpcWanneTalk = 19
                                    client.convoId = 4
                                }
                            }
                        },
                    ) otherwise {
                        npc("Can I help you at all?")
                        choice("Select an Option") {
                            "Yes please. What are you selling?" {
                                finishThen {
                                    openShop(3)
                                }
                            }
                            "No thanks." {
                                player("No thanks.")
                            }
                        }
                    }
                }

                trade {
                    openShop(3)
                }
            }
        }
}
